# Dependencies

In [3]:
import numpy as np

In [4]:
# prevent printing the returned object in each cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'none'

# NumPy - Array
Docs:
   - [numpy.org/doc/stable/reference/routines.array-creation.html](https://numpy.org/doc/stable/reference/routines.array-creation.html)
   - [numpy.org/doc/stable/reference/arrays.dtypes.html](https://numpy.org/doc/stable/reference/arrays.dtypes.html)

## 0D array (Known as scalar)

In [61]:
arr_1 = np.array(2)

# log
print(f"arr_1        : {arr_1}")
print(f"arr_1.shape  : {arr_1.shape}")
print(f"arr_1.dtype  : {arr_1.dtype}")
print(f"arr_1.nbytes : {arr_1.nbytes}")
print(f"type(arr_1)  : {type(arr_1)}")

arr_1        : 2
arr_1.shape  : ()
arr_1.dtype  : int32
arr_1.nbytes : 4
type(arr_1)  : <class 'numpy.ndarray'>


In [60]:
arr_2 = np.array(.1)

# log
print(f"arr_2        : {arr_2}")
print(f"arr_2.shape  : {arr_2.shape}")
print(f"arr_2.dtype  : {arr_2.dtype}")
print(f"arr_2.nbytes : {arr_2.nbytes}")
print(f"type(arr_2)  : {type(arr_2)}")

arr_2        : 0.1
arr_2.shape  : ()
arr_2.dtype  : float64
arr_2.nbytes : 8
type(arr_2)  : <class 'numpy.ndarray'>


## 1D array (Known as vector)

In [62]:
avg_scores = np.array([15, 13, 20, 19, 0, 11, 18, 15])

# log
print(f"avg_scores        : {avg_scores}")
print(f"avg_scores.shape  : {avg_scores.shape}")
print(f"avg_scores.dtype  : {avg_scores.dtype}")
print(f"avg_scores.nbytes : {avg_scores.nbytes}")
print(f"type(avg_scores)  : {type(avg_scores)}")

avg_scores        : [15 13 20 19  0 11 18 15]
avg_scores.shape  : (8,)
avg_scores.dtype  : int32
avg_scores.nbytes : 32
type(avg_scores)  : <class 'numpy.ndarray'>


In [63]:
audio = (3.0517578e-05, 3.1726351e-05, 2.1638528e-02, 4.8217773e-03)  # tuple
mono_audio = np.array(audio)

# log
print(f"mono_audio        : {mono_audio}")
print(f"mono_audio.shape  : {mono_audio.shape}")
print(f"mono_audio.dtype  : {mono_audio.dtype}")
print(f"mono_audio.nbytes : {mono_audio.nbytes}")
print(f"type(mono_audio)  : {type(mono_audio)}")

mono_audio        : [3.0517578e-05 3.1726351e-05 2.1638528e-02 4.8217773e-03]
mono_audio.shape  : (4,)
mono_audio.dtype  : float64
mono_audio.nbytes : 32
type(mono_audio)  : <class 'numpy.ndarray'>


## 2D array (known as matrix)

In [65]:
stereo_audio = np.array([[0.000e+0, 1.831e-4], [3.051e-4, 0.000e+0], [2.441e-4, 0.000e+0]])

# log
print(f"stereo_audio :\n{stereo_audio}", end='\n\n')
print(f"stereo_audio.shape  : {stereo_audio.shape}")
print(f"stereo_audio.dtype  : {stereo_audio.dtype}")
print(f"stereo_audio.nbytes : {stereo_audio.nbytes}")
print(f"type(stereo_audio)  : {type(stereo_audio)}")

stereo_audio :
[[0.        0.0001831]
 [0.0003051 0.       ]
 [0.0002441 0.       ]]

stereo_audio.shape  : (3, 2)
stereo_audio.dtype  : float64
stereo_audio.nbytes : 48
type(stereo_audio)  : <class 'numpy.ndarray'>


In [66]:
gs_img = np.array(
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12],
        [13, 14, 15, 16]
    ]
)

# log
print(f"gs_img :\n{gs_img}", end='\n\n')
print(f"gs_img.shape  : {gs_img.shape}")
print(f"gs_img.dtype  : {gs_img.dtype}")
print(f"gs_img.nbytes : {gs_img.nbytes}")
print(f"type(gs_img)  : {type(gs_img)}")

gs_img :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

gs_img.shape  : (4, 4)
gs_img.dtype  : int32
gs_img.nbytes : 64
type(gs_img)  : <class 'numpy.ndarray'>


## 3D array

In [67]:
rgb_image = np.array([[[255, 129, 255], [249, 230, 115]], [[255, 79, 79], [104, 203, 248]]])

# print
print(f"rgb_image :\n{rgb_image}", end="\n\n")
print(f"rgb_image.shape  : {rgb_image.shape}")
print(f"rgb_image.dtype  : {rgb_image.dtype}")
print(f"rgb_image.nbytes : {rgb_image.nbytes}")
print(f"type(rgb_image)  : {type(rgb_image)}")

rgb_image :
[[[255 129 255]
  [249 230 115]]

 [[255  79  79]
  [104 203 248]]]

rgb_image.shape  : (2, 2, 3)
rgb_image.dtype  : int32
rgb_image.nbytes : 48
type(rgb_image)  : <class 'numpy.ndarray'>


In [68]:
gs_video = np.array([
    [[203, 28, 91], [47, 124, 40], [19, 250, 51]],
    [[174, 87, 89], [15, 71, 231], [10, 12, 121]],
    [[193, 55, 81], [173, 19, 76], [1, 134, 250]],
    [[210, 50, 80], [180, 40, 60], [111, 32, 57]],
])

# log
print(f"gs_video :\n{gs_video}", end='\n\n')
print(f"gs_video.shape  : {gs_video.shape}")
print(f"gs_video.dtype  : {gs_video.dtype}")
print(f"gs_video.nbytes : {gs_video.nbytes}")
print(f"type(gs_video)  : {type(gs_video)}")

gs_video :
[[[203  28  91]
  [ 47 124  40]
  [ 19 250  51]]

 [[174  87  89]
  [ 15  71 231]
  [ 10  12 121]]

 [[193  55  81]
  [173  19  76]
  [  1 134 250]]

 [[210  50  80]
  [180  40  60]
  [111  32  57]]]

gs_video.shape  : (4, 3, 3)
gs_video.dtype  : int32
gs_video.nbytes : 144
type(gs_video)  : <class 'numpy.ndarray'>


## 4D array

In [69]:
arr = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]])

# print
print(f"rgb_image :\n{arr}", end='\n\n')
print(f"rgb_image.shape  : {rgb_image.shape}")
print(f"rgb_image.dtype  : {rgb_image.dtype}")
print(f"rgb_image.nbytes : {rgb_image.nbytes}")
print(f"type(rgb_image)  : {type(rgb_image)}")

rgb_image :
[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]

rgb_image.shape  : (2, 2, 3)
rgb_image.dtype  : int32
rgb_image.nbytes : 48
type(rgb_image)  : <class 'numpy.ndarray'>
