📝 **Author:** Amirhossein Heydari - 📧 **Email:** <amirhosseinheydari78@gmail.com> - 📍 **Origin:** [mr-pylin/numpy-workshop](https://github.com/mr-pylin/numpy-workshop)

---


# Dependencies


In [1]:
import numpy as np

# NumPy Basics

- **NumPy** is a powerful library for numerical computing in Python, optimized for high-performance array operations.
- **Arrays** in NumPy provide efficient storage and are the primary data structure, supporting fast mathematical computations over large datasets.

📝 **Docs**:

- NumPy Overview: [numpy.org/doc/stable/user/quickstart.html](https://numpy.org/doc/stable/user/quickstart.html)
- Array creation routines: [numpy.org/doc/stable/reference/routines.array-creation.html](https://numpy.org/doc/stable/reference/routines.array-creation.html)
- `numpy.array`: [numpy.org/doc/stable/reference/generated/numpy.array.html#numpy.array](https://numpy.org/doc/stable/reference/generated/numpy.array.html)
- Data type objects (`dtype`): [numpy.org/doc/stable/reference/arrays.dtypes.html](https://numpy.org/doc/stable/reference/arrays.dtypes.html)


## 0D array (Known as scalar)


In [2]:
arr_0d_1 = np.array(2)

# log
print(f"arr_0d_1        : {arr_0d_1}")
print(f"arr_0d_1.shape  : {arr_0d_1.shape}")
print(f"arr_0d_1.dtype  : {arr_0d_1.dtype}")
print(f"arr_0d_1.nbytes : {arr_0d_1.nbytes}")
print(f"type(arr_0d_1)  : {type(arr_0d_1)}")

arr_0d_1        : 2
arr_0d_1.shape  : ()
arr_0d_1.dtype  : int64
arr_0d_1.nbytes : 8
type(arr_0d_1)  : <class 'numpy.ndarray'>


In [3]:
arr_0d_2 = np.array(0.1)

# log
print(f"arr_0d_2        : {arr_0d_2}")
print(f"arr_0d_2.shape  : {arr_0d_2.shape}")
print(f"arr_0d_2.dtype  : {arr_0d_2.dtype}")
print(f"arr_0d_2.nbytes : {arr_0d_2.nbytes}")
print(f"type(arr_0d_2)  : {type(arr_0d_2)}")

arr_0d_2        : 0.1
arr_0d_2.shape  : ()
arr_0d_2.dtype  : float64
arr_0d_2.nbytes : 8
type(arr_0d_2)  : <class 'numpy.ndarray'>


## 1D array (Known as vector)


In [4]:
arr_1d_1 = np.array([15, 13, 20, 19, 0, 11, 18, 15])

# log
print(f"arr_1d_1        : {arr_1d_1}")
print(f"arr_1d_1.shape  : {arr_1d_1.shape}")
print(f"arr_1d_1.dtype  : {arr_1d_1.dtype}")
print(f"arr_1d_1.nbytes : {arr_1d_1.nbytes}")
print(f"type(arr_1d_1)  : {type(arr_1d_1)}")

arr_1d_1        : [15 13 20 19  0 11 18 15]
arr_1d_1.shape  : (8,)
arr_1d_1.dtype  : int64
arr_1d_1.nbytes : 64
type(arr_1d_1)  : <class 'numpy.ndarray'>


In [5]:
tuple_1 = (3.0517578e-05, 3.1726351e-05, 2.1638528e-02, 4.8217773e-03)
arr_1d_2 = np.array(tuple_1)

# log
print(f"arr_1d_2        : {arr_1d_2}")
print(f"arr_1d_2.shape  : {arr_1d_2.shape}")
print(f"arr_1d_2.dtype  : {arr_1d_2.dtype}")
print(f"mono_audio.nbytes : {arr_1d_2.nbytes}")
print(f"type(arr_1d_2)  : {type(arr_1d_2)}")

arr_1d_2        : [3.0517578e-05 3.1726351e-05 2.1638528e-02 4.8217773e-03]
arr_1d_2.shape  : (4,)
arr_1d_2.dtype  : float64
mono_audio.nbytes : 32
type(arr_1d_2)  : <class 'numpy.ndarray'>


## 2D array (known as matrix)


In [6]:
arr_2d_1 = np.array([[0.000e0, 1.831e-4], [3.051e-4, 0.000e0], [2.441e-4, 0.000e0]])

# log
print(f"arr_2d_1 :\n{arr_2d_1}", end="\n\n")
print(f"arr_2d_1.shape  : {arr_2d_1.shape}")
print(f"arr_2d_1.dtype  : {arr_2d_1.dtype}")
print(f"arr_2d_1.nbytes : {arr_2d_1.nbytes}")
print(f"type(arr_2d_1)  : {type(arr_2d_1)}")

arr_2d_1 :
[[0.        0.0001831]
 [0.0003051 0.       ]
 [0.0002441 0.       ]]

arr_2d_1.shape  : (3, 2)
arr_2d_1.dtype  : float64
arr_2d_1.nbytes : 48
type(arr_2d_1)  : <class 'numpy.ndarray'>


In [7]:
arr_2d_2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

# log
print(f"arr_2d_2 :\n{arr_2d_2}", end="\n\n")
print(f"arr_2d_2.shape  : {arr_2d_2.shape}")
print(f"arr_2d_2.dtype  : {arr_2d_2.dtype}")
print(f"arr_2d_2.nbytes : {arr_2d_2.nbytes}")
print(f"type(arr_2d_2)  : {type(arr_2d_2)}")

arr_2d_2 :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

arr_2d_2.shape  : (4, 4)
arr_2d_2.dtype  : int64
arr_2d_2.nbytes : 128
type(arr_2d_2)  : <class 'numpy.ndarray'>


## 3D array


In [8]:
arr_3d_1 = np.array([[[255, 129, 255], [249, 230, 115]], [[255, 79, 79], [104, 203, 248]]])

# print
print(f"arr_3d_1 :\n{arr_3d_1}", end="\n\n")
print(f"arr_3d_1.shape  : {arr_3d_1.shape}")
print(f"arr_3d_1.dtype  : {arr_3d_1.dtype}")
print(f"arr_3d_1.nbytes : {arr_3d_1.nbytes}")
print(f"type(arr_3d_1)  : {type(arr_3d_1)}")

arr_3d_1 :
[[[255 129 255]
  [249 230 115]]

 [[255  79  79]
  [104 203 248]]]

arr_3d_1.shape  : (2, 2, 3)
arr_3d_1.dtype  : int64
arr_3d_1.nbytes : 96
type(arr_3d_1)  : <class 'numpy.ndarray'>


In [9]:
arr_3d_2 = np.array(
    [
        [[203, 28, 91], [47, 124, 40], [19, 250, 51]],
        [[174, 87, 89], [15, 71, 231], [10, 12, 121]],
        [[193, 55, 81], [173, 19, 76], [1, 134, 250]],
        [[210, 50, 80], [180, 40, 60], [111, 32, 57]],
    ]
)

# log
print(f"arr_3d_2 :\n{arr_3d_2}", end="\n\n")
print(f"arr_3d_2.shape  : {arr_3d_2.shape}")
print(f"arr_3d_2.dtype  : {arr_3d_2.dtype}")
print(f"arr_3d_2.nbytes : {arr_3d_2.nbytes}")
print(f"type(arr_3d_2)  : {type(arr_3d_2)}")

arr_3d_2 :
[[[203  28  91]
  [ 47 124  40]
  [ 19 250  51]]

 [[174  87  89]
  [ 15  71 231]
  [ 10  12 121]]

 [[193  55  81]
  [173  19  76]
  [  1 134 250]]

 [[210  50  80]
  [180  40  60]
  [111  32  57]]]

arr_3d_2.shape  : (4, 3, 3)
arr_3d_2.dtype  : int64
arr_3d_2.nbytes : 288
type(arr_3d_2)  : <class 'numpy.ndarray'>


## 4D array


In [10]:
arr_4d_1 = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]])

# print
print(f"arr_4d_1 :\n{arr_4d_1}", end="\n\n")
print(f"arr_4d_1.shape  : {arr_4d_1.shape}")
print(f"arr_4d_1.dtype  : {arr_4d_1.dtype}")
print(f"arr_4d_1.nbytes : {arr_4d_1.nbytes}")
print(f"type(arr_4d_1)  : {type(arr_4d_1)}")

arr_4d_1 :
[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]

arr_4d_1.shape  : (2, 2, 2, 2)
arr_4d_1.dtype  : int64
arr_4d_1.nbytes : 128
type(arr_4d_1)  : <class 'numpy.ndarray'>
