# Dependencies

In [1]:
import numpy as np

# NumPy - Arithmetic Operations
Doc:
   - [numpy.org/doc/stable/reference/routines.math.html#arithmetic-operations](https://numpy.org/doc/stable/reference/routines.math.html#arithmetic-operations)

## Array & Scalar
Broadcasting:
   - It allows arrays of different shapes to be used together in arithmetic operations
   - The smaller array is “broadcast” across the larger array so that they have compatible shapes

In [2]:
arr_1d_1 = np.array([1, 2, 3, 4])

aso_1 = arr_1d_1 + 2   # np.add
aso_2 = arr_1d_1 - 1   # np.subtract
aso_3 = arr_1d_1 * 2   # np.multiply
aso_4 = arr_1d_1 / 2   # np.divide
aso_5 = arr_1d_1 // 2  # np.floor_divide
aso_6 = arr_1d_1 ** 2  # np.power
aso_7 = arr_1d_1 % 2   # np.mod | np.remainder

# log
for i in range(1, 8):
    print(f"aso_{i} : {eval(f'aso_{i}')}", end='\n')

aso_1 : [3 4 5 6]
aso_2 : [0 1 2 3]
aso_3 : [2 4 6 8]
aso_4 : [0.5 1.  1.5 2. ]
aso_5 : [0 1 1 2]
aso_6 : [ 1  4  9 16]
aso_7 : [1 0 1 0]


In [3]:
arr_2d_1 = np.array([[1, 2], [3, 4]])

aso_8 = arr_2d_1 + 2
aso_9 = arr_2d_1 - 1
aso_10 = arr_2d_1 * 2
aso_11 = arr_2d_1 / 2
aso_12 = arr_2d_1 // 2
aso_13 = arr_2d_1 ** 2
aso_14 = arr_2d_1 % 2

# log
for i in range(8, 15):
    print(f"aso_{i} :\n{eval(f'aso_{i}')}", end='\n\n')

aso_8 :
[[3 4]
 [5 6]]

aso_9 :
[[0 1]
 [2 3]]

aso_10 :
[[2 4]
 [6 8]]

aso_11 :
[[0.5 1. ]
 [1.5 2. ]]

aso_12 :
[[0 1]
 [1 2]]

aso_13 :
[[ 1  4]
 [ 9 16]]

aso_14 :
[[1 0]
 [1 0]]



## Array & Array
   - Operations are element-wise

In [4]:
arr_1d_2 = np.array([1, 2, 3, 4])
arr_1d_3 = np.array([4, 1, 2, 3])

aao_1 = arr_1d_2 + arr_1d_3
aao_2 = arr_1d_2 - arr_1d_3
aao_3 = arr_1d_2 * arr_1d_3
aao_4 = arr_1d_2 / arr_1d_3
aao_5 = arr_1d_2 // arr_1d_3
aao_6 = arr_1d_2 ** arr_1d_3
aao_7 = arr_1d_2 % arr_1d_3

# log
for i in range(1, 8):
    print(f"aao_{i} : {eval(f'aao_{i}')}", end="\n")

aao_1 : [5 3 5 7]
aao_2 : [-3  1  1  1]
aao_3 : [ 4  2  6 12]
aao_4 : [0.25       2.         1.5        1.33333333]
aao_5 : [0 2 1 1]
aao_6 : [ 1  2  9 64]
aao_7 : [1 0 1 1]


In [5]:
arr_2d_2 = np.array([[1, 2], [3, 4]])
arr_2d_3 = np.array([[2, 2], [3, 3]])

aao_8 = arr_2d_2 + arr_2d_3
aao_9 = arr_2d_2 - arr_2d_3
aao_10 = arr_2d_2 * arr_2d_3
aao_11 = arr_2d_2 / arr_2d_3
aao_12 = arr_2d_2 // arr_2d_3
aao_13 = arr_2d_2 ** arr_2d_3
aao_14 = arr_2d_2 % arr_2d_3

# log
for i in range(8, 15):
    print(f"aao_{i} :\n{eval(f'aao_{i}')}", end="\n\n")

aao_8 :
[[3 4]
 [6 7]]

aao_9 :
[[-1  0]
 [ 0  1]]

aao_10 :
[[ 2  4]
 [ 9 12]]

aao_11 :
[[0.5        1.        ]
 [1.         1.33333333]]

aao_12 :
[[0 1]
 [1 1]]

aao_13 :
[[ 1  4]
 [27 64]]

aao_14 :
[[1 0]
 [0 1]]

