# Dependencies

In [1]:
import numpy as np

In [2]:
# prevent printing the returned object in each cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'none'

# NumPy - Arithmetic Operations
Doc:
   - [numpy.org/doc/stable/reference/routines.math.html#arithmetic-operations](https://numpy.org/doc/stable/reference/routines.math.html#arithmetic-operations)

## Array & Scalar
Broadcasting:
   - It allows arrays of different shapes to be used together in arithmetic operations
   - The smaller array is “broadcast” across the larger array so that they have compatible shapes

In [7]:
arr_1 = np.array([1, 2, 3, 4])

aso1 = arr_1 + 2
aso2 = arr_1 - 1
aso3 = arr_1 * 2
aso4 = arr_1 / 2
aso5 = arr_1 // 2
aso6 = arr_1 ** 2
aso7 = arr_1 % 2

# log
for i in range(1, 8):
    print(f"aso{i} : {eval(f'aso{i}')}", end='\n')

aso1 : [3 4 5 6]
aso2 : [0 1 2 3]
aso3 : [2 4 6 8]
aso4 : [0.5 1.  1.5 2. ]
aso5 : [0 1 1 2]
aso6 : [ 1  4  9 16]
aso7 : [1 0 1 0]


In [9]:
arr_2 = np.array([[1, 2], [3, 4]])

aso8 = arr_2 + 2
aso9 = arr_2 - 1
aso10 = arr_2 * 2
aso11 = arr_2 / 2
aso12 = arr_2 // 2
aso13 = arr_2 ** 2
aso14 = arr_2 % 2

# log
for i in range(8, 15):
    print(f"aso{i} :\n{eval(f'aso{i}')}", end='\n\n')

aso8 :
[[3 4]
 [5 6]]

aso9 :
[[0 1]
 [2 3]]

aso10 :
[[2 4]
 [6 8]]

aso11 :
[[0.5 1. ]
 [1.5 2. ]]

aso12 :
[[0 1]
 [1 2]]

aso13 :
[[ 1  4]
 [ 9 16]]

aso14 :
[[1 0]
 [1 0]]



## Array & Array

In [12]:
arr_1 = np.array([1, 2, 3, 4])
arr_2 = np.array([4, 1, 2, 3])

aao1 = arr_1 + arr_2
aao2 = arr_1 - arr_2
aao3 = arr_1 * arr_2
aao4 = arr_1 / arr_2
aao5 = arr_1 // arr_2
aao6 = arr_1 ** arr_2
aao7 = arr_1 % arr_2

# log
for i in range(1, 8):
    print(f"aao{i} : {eval(f'aao{i}')}", end="\n")

aao1 : [5 3 5 7]
aao2 : [-3  1  1  1]
aao3 : [ 4  2  6 12]
aao4 : [0.25       2.         1.5        1.33333333]
aao5 : [0 2 1 1]
aao6 : [ 1  2  9 64]
aao7 : [1 0 1 1]


In [13]:
arr_3 = np.array([[1, 2], [3, 4]])
arr_4 = np.array([[2, 2], [3, 3]])

aao8 = arr_3 + arr_4
aao9 = arr_3 - arr_4
aao10 = arr_3 * arr_4
aao11 = arr_3 / arr_4
aao12 = arr_3 // arr_4
aao13 = arr_3 ** arr_4
aao14 = arr_3 % arr_4

# log
for i in range(8, 15):
    print(f"aao{i} :\n{eval(f'aao{i}')}", end="\n\n")

aao8 :
[[3 4]
 [6 7]]

aao9 :
[[-1  0]
 [ 0  1]]

aao10 :
[[ 2  4]
 [ 9 12]]

aao11 :
[[0.5        1.        ]
 [1.         1.33333333]]

aao12 :
[[0 1]
 [1 1]]

aao13 :
[[ 1  4]
 [27 64]]

aao14 :
[[1 0]
 [0 1]]

