# Dependencies

In [31]:
import numpy as np

In [32]:
# prevent printing the returned object in each cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'none'

# NumPy - Index
Doc:
   - [numpy.org/doc/stable/user/basics.indexing.html#basic-indexing](https://numpy.org/doc/stable/user/basics.indexing.html#basic-indexing)

In [33]:
arr_1d = np.array([8, 9, 0, 3, 1, 6, 4, 2])

idx_11 = arr_1d[0]   # 8
idx_12 = arr_1d[2]   # 0
idx_13 = arr_1d[4]   # 1
idx_14 = arr_1d[7]   # 2
idx_15 = arr_1d[-8]  # 8
idx_16 = arr_1d[-6]  # 0
idx_17 = arr_1d[-4]  # 1
idx_18 = arr_1d[-1]  # 2

# log
print(f"arr_1d[0]  : {idx_11}")
print(f"arr_1d[2]  : {idx_12}")
print(f"arr_1d[4]  : {idx_13}")
print(f"arr_1d[7]  : {idx_14}")
print(f"arr_1d[-8] : {idx_15}")
print(f"arr_1d[-6] : {idx_16}")
print(f"arr_1d[-4] : {idx_17}")
print(f"arr_1d[-1] : {idx_18}")

arr_1d[0]  : 8
arr_1d[2]  : 0
arr_1d[4]  : 1
arr_1d[7]  : 2
arr_1d[-8] : 8
arr_1d[-6] : 0
arr_1d[-4] : 1
arr_1d[-1] : 2


In [34]:
arr_2d = np.array([[2, 3, 4], [7, 9, 8], [6, 5, 0]])

idx_21 = arr_2d[0]      # [2 3 4]
idx_22 = arr_2d[1]      # [7 9 8]
idx_23 = arr_2d[2]      # [6 5 0]
idx_24 = arr_2d[0, 1]  # 3
idx_25 = arr_2d[1, 1]  # 9
idx_26 = arr_2d[-1, 0]  # 6

# log
print(f"arr_2d[0]     : {idx_21}")
print(f"arr_2d[1]     : {idx_22}")
print(f"arr_2d[2]     : {idx_23}")
print(f"arr_2d[0, 1]  : {idx_24}")
print(f"arr_2d[1, 1]  : {idx_25}")
print(f"arr_2d[-1, 0] : {idx_26}")

arr_2d[0]     : [2 3 4]
arr_2d[1]     : [7 9 8]
arr_2d[2]     : [6 5 0]
arr_2d[0, 1]  : 3
arr_2d[1, 1]  : 9
arr_2d[-1, 0] : 6


In [35]:
arr_3d = np.array([[[2, 3], [0, 4]], [[7, 8], [4, 2]]])

idx31 = arr_3d[0]        # [[2 3] [0 4]]
idx32 = arr_3d[-1]       # [[7 8] [4 2]]
idx33 = arr_3d[0,  0]   # [2 3]
idx34 = arr_3d[0, -1]   # [0 4]
idx35 = arr_3d[-1,  1]   # [4 2]
idx36 = arr_3d[0, 0, 0]  # 2
idx37 = arr_3d[1, 0, 1]  # 8

# log
print(f"arr_3d[0] :\n{idx31}", end='\n\n')
print(f"arr_3d[-1] :\n{idx32}", end='\n\n')
print(f"arr_3d[0, 0] :\n{idx33}", end='\n\n')
print(f"arr_3d[0, -1] :\n{idx34}", end='\n\n')
print(f"arr_3d[-1, 1] :\n{idx35}", end='\n\n')
print(f"arr_3d[0, 0, 0] :\n{idx36}", end='\n\n')
print(f"arr_3d[1, 0, 1] :\n{idx37}", end='\n\n')

arr_3d[0] :
[[2 3]
 [0 4]]

arr_3d[-1] :
[[7 8]
 [4 2]]

arr_3d[0, 0] :
[2 3]

arr_3d[0, -1] :
[0 4]

arr_3d[-1, 1] :
[4 2]

arr_3d[0, 0, 0] :
2

arr_3d[1, 0, 1] :
8



# NumPy - Slice
Doc:
   - [numpy.org/doc/stable/user/basics.indexing.html#slicing-and-striding](https://numpy.org/doc/stable/user/basics.indexing.html#slicing-and-striding)

In [36]:
arr_1d = np.array([8, 9, 0, 3, 1, 6, 4, 2])

slc_11 = arr_1d[0:3]      # [8 9 0]
slc_12 = arr_1d[:3]       # [8 9 0]
slc_13 = arr_1d[:3:]      # [8 9 0]
slc_14 = arr_1d[:3:1]     # [8 9 0]
slc_15 = arr_1d[0:3:1]    # [8 9 0]
slc_16 = arr_1d[5:8]      # [6 4 2]
slc_17 = arr_1d[5:]       # [6 4 2]
slc_18 = arr_1d[5:8:]     # [6 4 2]
slc_19 = arr_1d[5::]      # [6 4 2]
slc_110 = arr_1d[5::1]    # [6 4 2]
slc_111 = arr_1d[5:1000]  # [6 4 2]

# log
print(f"arr_1d[0:3]    : {slc_11}")
print(f"arr_1d[:3]     : {slc_12}")
print(f"arr_1d[:3:]    : {slc_13}")
print(f"arr_1d[:3:1]   : {slc_14}")
print(f"arr_1d[0:3:1]  : {slc_15}")
print(f"arr_1d[5:8]    : {slc_16}")
print(f"arr_1d[5:]     : {slc_17}")
print(f"arr_1d[5:8:]   : {slc_18}")
print(f"arr_1d[5::]    : {slc_19}")
print(f"arr_1d[5::1]   : {slc_110}")
print(f"arr_1d[5:1000] : {slc_111}")

arr_1d[0:3]    : [8 9 0]
arr_1d[:3]     : [8 9 0]
arr_1d[:3:]    : [8 9 0]
arr_1d[:3:1]   : [8 9 0]
arr_1d[0:3:1]  : [8 9 0]
arr_1d[5:8]    : [6 4 2]
arr_1d[5:]     : [6 4 2]
arr_1d[5:8:]   : [6 4 2]
arr_1d[5::]    : [6 4 2]
arr_1d[5::1]   : [6 4 2]
arr_1d[5:1000] : [6 4 2]


In [37]:
arr_2d = np.array([[2, 3, 4], [7, 9, 8], [6, 5, 0]])

slc_21 = arr_2d[0, 0:2]    # [2 3]
slc_22 = arr_2d[0, :2]     # [2 3]
slc_23 = arr_2d[0:2, 1:3]  # [[3 4] [9 8]]
slc_24 = arr_2d[:2, 1:]    # [[3 4] [9 8]]
slc_25 = arr_2d[0:3, 1]    # [3 9 5]
slc_26 = arr_2d[:3, 1]     # [3 9 5]
slc_27 = arr_2d[0:, 1]     # [3 9 5]
slc_28 = arr_2d[:, 1]      # [3 9 5]

# log
print(f"arr_1d[0, 0:2] :\n{slc_21}", end='\n\n')
print(f"arr_1d[0, :2] :\n{slc_22}", end='\n\n')
print(f"arr_1d[0:2, 1:3] :\n{slc_23}", end='\n\n')
print(f"arr_1d[:2, 1:] :\n{slc_24}", end='\n\n')
print(f"arr_1d[0:3, 1] :\n{slc_25}", end='\n\n')
print(f"arr_1d[:3, 1] :\n{slc_26}", end='\n\n')
print(f"arr_1d[0:, 1] :\n{slc_27}", end='\n\n')
print(f"arr_1d[:, 1] :\n{slc_28}")

arr_1d[0, 0:2] :
[2 3]

arr_1d[0, :2] :
[2 3]

arr_1d[0:2, 1:3] :
[[3 4]
 [9 8]]

arr_1d[:2, 1:] :
[[3 4]
 [9 8]]

arr_1d[0:3, 1] :
[3 9 5]

arr_1d[:3, 1] :
[3 9 5]

arr_1d[0:, 1] :
[3 9 5]

arr_1d[:, 1] :
[3 9 5]


In [38]:
arr_3d = np.array([[[2, 3], [0, 4]], [[7, 8], [4, 2]]])

slc_31 = arr_3d[0, 0, 0:2]    # [2 3]
slc_32 = arr_3d[0, 0, 0:]     # [2 3]
slc_33 = arr_3d[0, 0, :2]     # [2 3]
slc_34 = arr_3d[0, 0, :]      # [2 3]
slc_35 = arr_3d[0, 0:2, 1]    # [3 4]
slc_36 = arr_3d[0, :, 1]      # [3 4]
slc_37 = arr_3d[0, :, :]      # [[2 3] [0 4]]  /  Same as <arr_3d[0, ...]>
slc_38 = arr_3d[0]            # [[2 3] [0 4]]
slc_39 = arr_3d[0:2, 0, 0:2]  # [[2 3] [7 8]]
slc_310 = arr_3d[:, 0, :]     # [[2 3] [7 8]]

# log
print(f"arr_1d[0, 0, 0:2] :\n{slc_31}", end='\n\n')
print(f"arr_1d[0, 0, 0:] :\n{slc_32}", end='\n\n')
print(f"arr_1d[0, 0, :2] :\n{slc_33}", end='\n\n')
print(f"arr_1d[0, 0, :] :\n{slc_34}", end='\n\n')
print(f"arr_1d[0, 0:2, 1] :\n{slc_35}", end='\n\n')
print(f"arr_1d[0, :, 1] :\n{slc_36}", end='\n\n')
print(f"arr_1d[0, :, :] :\n{slc_37}", end='\n\n')
print(f"arr_1d[0] :\n{slc_38}", end='\n\n')
print(f"arr_1d[0:2, 0, 0:2] :\n{slc_39}", end='\n\n')
print(f"arr_1d[:, 0, :] :\n{slc_310}")

arr_1d[0, 0, 0:2] :
[2 3]

arr_1d[0, 0, 0:] :
[2 3]

arr_1d[0, 0, :2] :
[2 3]

arr_1d[0, 0, :] :
[2 3]

arr_1d[0, 0:2, 1] :
[3 4]

arr_1d[0, :, 1] :
[3 4]

arr_1d[0, :, :] :
[[2 3]
 [0 4]]

arr_1d[0] :
[[2 3]
 [0 4]]

arr_1d[0:2, 0, 0:2] :
[[2 3]
 [7 8]]

arr_1d[:, 0, :] :
[[2 3]
 [7 8]]


# NumPy - Mask & Filter

In [39]:
arr1 = np.array([1, 5, 2, 4, 2])
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [40]:
# Python way
filtered_arr1 = list(filter(lambda v: v > 2, arr1.tolist()))
filtered_arr2 = list(filter(lambda v: v % 2 == 0, arr2.ravel().tolist()))

# log
print(f"filtered_arr1 : {filtered_arr1}")
print(f"filtered_arr2 : {filtered_arr2}")

filtered_arr1 : [5, 4]
filtered_arr2 : [2, 4, 6, 8]


In [41]:
# NumPy way
filtered_arr3 = arr1[arr1 > 2]
filtered_arr4 = arr2[arr2 % 2 == 0]

# log
print(f"filtered_arr3 : {filtered_arr3}")
print(f"filtered_arr4 : {filtered_arr4}")

filtered_arr3 : [5 4]
filtered_arr4 : [2 4 6 8]


# NumPy - Advanced index & Slice
Doc:
   - [numpy.org/doc/stable/user/basics.indexing.html#advanced-indexing](https://numpy.org/doc/stable/user/basics.indexing.html#advanced-indexing)

## Integer array indexing

In [42]:
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

iai_11 = arr_1d[[0, 1, 2]]            # [1 2 3]
iai_12 = arr_1d[np.array([0, 1, 2])]  # [1 2 3]
iai_13 = arr_1d[[0, 4, 7]]            # [1 5 8]
iai_14 = arr_1d[[-1, -2, -3]]         # [9 8 7]

# log
print(f"arr_1d[[0, 1, 2]]           : {iai_11}")
print(f"arr_1d[np.array([0, 1, 2])] : {iai_12}")
print(f"arr_1d[[0, 4, 7]]           : {iai_13}")
print(f"arr_1d[[-1, -2, -3]]        : {iai_14}")

arr_1d[[0, 1, 2]]           : [1 2 3]
arr_1d[np.array([0, 1, 2])] : [1 2 3]
arr_1d[[0, 4, 7]]           : [1 5 8]
arr_1d[[-1, -2, -3]]        : [9 8 7]


In [43]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

iai_21 = arr_2d[[0, 2]]                              # [[1 2 3] [7 8 9]]
iai_22 = arr_2d[[0, 2], 0]                           # [1 7]
iai_23 = arr_2d[[0, 2], [1, 2]]                      # [2 9]
iai_24 = arr_2d[1, [0, 2]]                           # [4 6]
iai_25 = arr_2d[[[0, 0], [2, 2]], [[0, 2], [0, 2]]]  # [[1 3] [7 9]]

# log
print(f"arr_2d[[0, 2]] :\n{iai_21}", end='\n\n')
print(f"arr_2d[[0, 2], 0] :\n{iai_21}", end='\n\n')
print(f"arr_2d[[0, 2], [1, 2]] :\n{iai_21}", end='\n\n')
print(f"arr_2d[1, [0, 2]] :\n{iai_21}", end='\n\n')
print(f"arr_2d[[[0, 0], [2, 2]], [[0, 2], [0, 2]]] :\n{iai_21}", end='\n\n')

arr_2d[[0, 2]] :
[[1 2 3]
 [7 8 9]]

arr_2d[[0, 2], 0] :
[[1 2 3]
 [7 8 9]]

arr_2d[[0, 2], [1, 2]] :
[[1 2 3]
 [7 8 9]]

arr_2d[1, [0, 2]] :
[[1 2 3]
 [7 8 9]]

arr_2d[[[0, 0], [2, 2]], [[0, 2], [0, 2]]] :
[[1 2 3]
 [7 8 9]]



## Boolean array indexing

In [56]:
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# boolean indexing
boolean_idx_1 = arr_1d % 2 == 0  # [False True False True False True False True False]
boolean_idx_2 = arr_1d > 5       # [False False False False False True True True True]
boolean_idx_3 = [True, True, False, False, True, True, False, False, True]

# indexing
bai_11 = arr_1d[boolean_idx_1]  # [2 4 6 8]
bai_12 = arr_1d[boolean_idx_2]  # [6 7 8 9]
bai_13 = arr_1d[boolean_idx_3]  # [1 2 5 6 9]

# log
print(f"arr_1d[boolean_idx_1] : {bai_11}")
print(f"arr_1d[boolean_idx_2] : {bai_12}")
print(f"arr_1d[boolean_idx_3] : {bai_13}")

arr_1d[boolean_idx_1] : [2 4 6 8]
arr_1d[boolean_idx_2] : [6 7 8 9]
arr_1d[boolean_idx_3] : [1 2 5 6 9]


In [55]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# boolean indexing
boolean_idx_4 = arr_2d > 3                   # [False False False True True True True True True]
boolean_idx_5 = np.sum(arr_2d, axis=1) < 15  # [True False False]
boolean_idx_6 = np.sum(arr_2d, axis=0) < 16  # [True True  False]

# indexing
bai_21 = arr_2d[boolean_idx_4]
bai_22 = arr_2d[boolean_idx_5, boolean_idx_6]

# log
print(f"arr_2d[boolean_idx_4]                : {bai_21}")
print(f"arr_2d[boolean_idx_5, boolean_idx_6] : {bai_22}")

arr_2d[boolean_idx_4]                : [4 5 6 7 8 9]
arr_2d[boolean_idx_5, boolean_idx_6] : [1 2]
