# Dependencies

In [1]:
import numpy as np

# NumPy - Index
Doc:
   - [numpy.org/doc/stable/user/basics.indexing.html#basic-indexing](https://numpy.org/doc/stable/user/basics.indexing.html#basic-indexing)

In [2]:
arr_1d_1 = np.array([8, 9, 0, 3, 1, 6, 4, 2])

idx_1 = arr_1d_1[0]   # 8
idx_2 = arr_1d_1[2]   # 0
idx_3 = arr_1d_1[4]   # 1
idx_4 = arr_1d_1[7]   # 2
idx_5 = arr_1d_1[-8]  # 8
idx_6 = arr_1d_1[-6]  # 0
idx_7 = arr_1d_1[-4]  # 1
idx_8 = arr_1d_1[-1]  # 2

# log
print(f"arr_1d_1[0]  : {idx_1}")
print(f"arr_1d_1[2]  : {idx_2}")
print(f"arr_1d_1[4]  : {idx_3}")
print(f"arr_1d_1[7]  : {idx_4}")
print(f"arr_1d_1[-8] : {idx_5}")
print(f"arr_1d_1[-6] : {idx_6}")
print(f"arr_1d_1[-4] : {idx_7}")
print(f"arr_1d_1[-1] : {idx_8}")

arr_1d_1[0]  : 8
arr_1d_1[2]  : 0
arr_1d_1[4]  : 1
arr_1d_1[7]  : 2
arr_1d_1[-8] : 8
arr_1d_1[-6] : 0
arr_1d_1[-4] : 1
arr_1d_1[-1] : 2


In [3]:
arr_2d_1 = np.array([[2, 3, 4], [7, 9, 8], [6, 5, 0]])

idx_9 = arr_2d_1[0]       # [2 3 4]
idx_10 = arr_2d_1[1]      # [7 9 8]
idx_11 = arr_2d_1[2]      # [6 5 0]
idx_12 = arr_2d_1[0, 1]   # 3
idx_13 = arr_2d_1[1, 1]   # 9
idx_14 = arr_2d_1[-1, 0]  # 6

# log
print(f"arr_2d_1[0]     : {idx_9}")
print(f"arr_2d_1[1]     : {idx_10}")
print(f"arr_2d_1[2]     : {idx_11}")
print(f"arr_2d_1[0, 1]  : {idx_12}")
print(f"arr_2d_1[1, 1]  : {idx_13}")
print(f"arr_2d_1[-1, 0] : {idx_14}")

arr_2d_1[0]     : [2 3 4]
arr_2d_1[1]     : [7 9 8]
arr_2d_1[2]     : [6 5 0]
arr_2d_1[0, 1]  : 3
arr_2d_1[1, 1]  : 9
arr_2d_1[-1, 0] : 6


In [4]:
arr_3d_1 = np.array([[[2, 3], [0, 4]], [[7, 8], [4, 2]]])

idx_15 = arr_3d_1[0]        # [[2 3] [0 4]]
idx_16 = arr_3d_1[-1]       # [[7 8] [4 2]]
idx_17 = arr_3d_1[0,  0]    # [2 3]
idx_18 = arr_3d_1[0, -1]    # [0 4]
idx_19 = arr_3d_1[-1,  1]   # [4 2]
idx_20 = arr_3d_1[0, 0, 0]  # 2
idx_21 = arr_3d_1[1, 0, 1]  # 8

# log
print(f"arr_3d_1[0] :\n{idx_15}", end='\n\n')
print(f"arr_3d_1[-1] :\n{idx_16}", end='\n\n')
print(f"arr_3d_1[0, 0] :\n{idx_17}", end='\n\n')
print(f"arr_3d_1[0, -1] :\n{idx_18}", end='\n\n')
print(f"arr_3d_1[-1, 1] :\n{idx_19}", end='\n\n')
print(f"arr_3d_1[0, 0, 0] :\n{idx_20}", end='\n\n')
print(f"arr_3d_1[1, 0, 1] :\n{idx_21}")

arr_3d_1[0] :
[[2 3]
 [0 4]]

arr_3d_1[-1] :
[[7 8]
 [4 2]]

arr_3d_1[0, 0] :
[2 3]

arr_3d_1[0, -1] :
[0 4]

arr_3d_1[-1, 1] :
[4 2]

arr_3d_1[0, 0, 0] :
2

arr_3d_1[1, 0, 1] :
8


# NumPy - Slice
Doc:
   - [numpy.org/doc/stable/user/basics.indexing.html#slicing-and-striding](https://numpy.org/doc/stable/user/basics.indexing.html#slicing-and-striding)

In [5]:
arr_1d_2 = np.array([8, 9, 0, 3, 1, 6, 4, 2])

slc_1 = arr_1d_2[0:3]      # [8 9 0]
slc_2 = arr_1d_2[:3]       # [8 9 0]
slc_3 = arr_1d_2[:3:]      # [8 9 0]
slc_4 = arr_1d_2[:3:1]     # [8 9 0]
slc_5 = arr_1d_2[0:3:1]    # [8 9 0]
slc_6 = arr_1d_2[5:8]      # [6 4 2]
slc_7 = arr_1d_2[5:]       # [6 4 2]
slc_8 = arr_1d_2[5:8:]     # [6 4 2]
slc_9 = arr_1d_2[5::]      # [6 4 2]
slc_10 = arr_1d_2[5::1]    # [6 4 2]
slc_11 = arr_1d_2[5:1000]  # [6 4 2]

# log
print(f"arr_1d_2[0:3]    : {slc_1}")
print(f"arr_1d_2[:3]     : {slc_2}")
print(f"arr_1d_2[:3:]    : {slc_3}")
print(f"arr_1d_2[:3:1]   : {slc_4}")
print(f"arr_1d_2[0:3:1]  : {slc_5}")
print(f"arr_1d_2[5:8]    : {slc_6}")
print(f"arr_1d_2[5:]     : {slc_7}")
print(f"arr_1d_2[5:8:]   : {slc_8}")
print(f"arr_1d_2[5::]    : {slc_9}")
print(f"arr_1d_2[5::1]   : {slc_10}")
print(f"arr_1d_2[5:1000] : {slc_11}")

arr_1d_2[0:3]    : [8 9 0]
arr_1d_2[:3]     : [8 9 0]
arr_1d_2[:3:]    : [8 9 0]
arr_1d_2[:3:1]   : [8 9 0]
arr_1d_2[0:3:1]  : [8 9 0]
arr_1d_2[5:8]    : [6 4 2]
arr_1d_2[5:]     : [6 4 2]
arr_1d_2[5:8:]   : [6 4 2]
arr_1d_2[5::]    : [6 4 2]
arr_1d_2[5::1]   : [6 4 2]
arr_1d_2[5:1000] : [6 4 2]


In [6]:
arr_2d_2 = np.array([[2, 3, 4], [7, 9, 8], [6, 5, 0]])

slc_12 = arr_2d_2[0, 0:2]    # [2 3]
slc_13 = arr_2d_2[0, :2]     # [2 3]
slc_14 = arr_2d_2[0:2, 1:3]  # [[3 4] [9 8]]
slc_15 = arr_2d_2[:2, 1:]    # [[3 4] [9 8]]
slc_16 = arr_2d_2[0:3, 1]    # [3 9 5]
slc_17 = arr_2d_2[:3, 1]     # [3 9 5]
slc_18 = arr_2d_2[0:, 1]     # [3 9 5]
slc_19 = arr_2d_2[:, 1]      # [3 9 5]

# log
print(f"arr_2d_2[0, 0:2] :\n{slc_12}", end='\n\n')
print(f"arr_2d_2[0, :2] :\n{slc_13}", end='\n\n')
print(f"arr_2d_2[0:2, 1:3] :\n{slc_14}", end='\n\n')
print(f"arr_2d_2[:2, 1:] :\n{slc_15}", end='\n\n')
print(f"arr_2d_2[0:3, 1] :\n{slc_16}", end='\n\n')
print(f"arr_2d_2[:3, 1] :\n{slc_17}", end='\n\n')
print(f"arr_2d_2[0:, 1] :\n{slc_18}", end='\n\n')
print(f"arr_2d_2[:, 1] :\n{slc_19}")

arr_2d_2[0, 0:2] :
[2 3]

arr_2d_2[0, :2] :
[2 3]

arr_2d_2[0:2, 1:3] :
[[3 4]
 [9 8]]

arr_2d_2[:2, 1:] :
[[3 4]
 [9 8]]

arr_2d_2[0:3, 1] :
[3 9 5]

arr_2d_2[:3, 1] :
[3 9 5]

arr_2d_2[0:, 1] :
[3 9 5]

arr_2d_2[:, 1] :
[3 9 5]


In [7]:
arr_3d_2 = np.array([[[2, 3], [0, 4]], [[7, 8], [4, 2]]])

slc_20 = arr_3d_2[0, 0, 0:2]    # [2 3]
slc_21 = arr_3d_2[0, 0, 0:]     # [2 3]
slc_22 = arr_3d_2[0, 0, :2]     # [2 3]
slc_23 = arr_3d_2[0, 0, :]      # [2 3]
slc_24 = arr_3d_2[0, 0:2, 1]    # [3 4]
slc_25 = arr_3d_2[0, :, 1]      # [3 4]
slc_26 = arr_3d_2[0, :, :]      # [[2 3] [0 4]]  /  Same as <arr_3d[0, ...]>
slc_27 = arr_3d_2[0]            # [[2 3] [0 4]]
slc_28 = arr_3d_2[0:2, 0, 0:2]  # [[2 3] [7 8]]
slc_29 = arr_3d_2[:, 0, :]      # [[2 3] [7 8]]

# log
print(f"arr_3d_2[0, 0, 0:2] :\n{slc_20}", end='\n\n')
print(f"arr_3d_2[0, 0, 0:] :\n{slc_21}", end='\n\n')
print(f"arr_3d_2[0, 0, :2] :\n{slc_22}", end='\n\n')
print(f"arr_3d_2[0, 0, :] :\n{slc_23}", end='\n\n')
print(f"arr_3d_2[0, 0:2, 1] :\n{slc_24}", end='\n\n')
print(f"arr_3d_2[0, :, 1] :\n{slc_25}", end='\n\n')
print(f"arr_3d_2[0, :, :] :\n{slc_26}", end='\n\n')
print(f"arr_3d_2[0] :\n{slc_27}", end='\n\n')
print(f"arr_3d_2[0:2, 0, 0:2] :\n{slc_28}", end='\n\n')
print(f"arr_3d_2[:, 0, :] :\n{slc_29}")

arr_3d_2[0, 0, 0:2] :
[2 3]

arr_3d_2[0, 0, 0:] :
[2 3]

arr_3d_2[0, 0, :2] :
[2 3]

arr_3d_2[0, 0, :] :
[2 3]

arr_3d_2[0, 0:2, 1] :
[3 4]

arr_3d_2[0, :, 1] :
[3 4]

arr_3d_2[0, :, :] :
[[2 3]
 [0 4]]

arr_3d_2[0] :
[[2 3]
 [0 4]]

arr_3d_2[0:2, 0, 0:2] :
[[2 3]
 [7 8]]

arr_3d_2[:, 0, :] :
[[2 3]
 [7 8]]


# NumPy - Mask & Filter

In [8]:
arr_1d_3 = np.array([1, 5, 2, 4, 2])
arr_2d_3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [9]:
# Python way
filtered_1 = list(filter(lambda v: v > 2, arr_1d_3.tolist()))
filtered_2 = list(filter(lambda v: v % 2 == 0, arr_2d_3.ravel().tolist()))

# log
print(f"filtered_1 : {filtered_1}")
print(f"filtered_2 : {filtered_2}")

filtered_1 : [5, 4]
filtered_2 : [2, 4, 6, 8]


In [10]:
# NumPy way
filtered_3 = arr_1d_3[arr_1d_3 > 2]
filtered_4 = arr_2d_3[arr_2d_3 % 2 == 0]

# log
print(f"filtered_3 : {filtered_3}")
print(f"filtered_4 : {filtered_4}")

filtered_3 : [5 4]
filtered_4 : [2 4 6 8]


# NumPy - Advanced index & Slice
Doc:
   - [numpy.org/doc/stable/user/basics.indexing.html#advanced-indexing](https://numpy.org/doc/stable/user/basics.indexing.html#advanced-indexing)

## Integer array indexing

In [11]:
arr_1d_4 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

iai_1 = arr_1d_4[[0, 1, 2]]            # [1 2 3]
iai_2 = arr_1d_4[np.array([0, 1, 2])]  # [1 2 3]
iai_3 = arr_1d_4[[0, 4, 7]]            # [1 5 8]
iai_4 = arr_1d_4[[-1, -2, -3]]         # [9 8 7]

# log
print(f"arr_1d_4[[0, 1, 2]]           : {iai_1}")
print(f"arr_1d_4[np.array([0, 1, 2])] : {iai_2}")
print(f"arr_1d_4[[0, 4, 7]]           : {iai_3}")
print(f"arr_1d_4[[-1, -2, -3]]        : {iai_4}")

arr_1d_4[[0, 1, 2]]           : [1 2 3]
arr_1d_4[np.array([0, 1, 2])] : [1 2 3]
arr_1d_4[[0, 4, 7]]           : [1 5 8]
arr_1d_4[[-1, -2, -3]]        : [9 8 7]


In [12]:
arr_2d_4 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

iai_5 = arr_2d_4[[0, 2]]                              # [[1 2 3] [7 8 9]]
iai_6 = arr_2d_4[[0, 2], 0]                           # [1 7]
iai_7 = arr_2d_4[[0, 2], [1, 2]]                      # [2 9]
iai_8 = arr_2d_4[1, [0, 2]]                           # [4 6]
iai_9 = arr_2d_4[[[0, 0], [2, 2]], [[0, 2], [0, 2]]]  # [[1 3] [7 9]]

# log
print(f"arr_2d_4[[0, 2]] :\n{iai_5}", end='\n\n')
print(f"arr_2d_4[[0, 2], 0] :\n{iai_6}", end='\n\n')
print(f"arr_2d_4[[0, 2], [1, 2]] :\n{iai_7}", end='\n\n')
print(f"arr_2d_4[1, [0, 2]] :\n{iai_8}", end='\n\n')
print(f"arr_2d_4[[[0, 0], [2, 2]], [[0, 2], [0, 2]]] :\n{iai_9}")

arr_2d_4[[0, 2]] :
[[1 2 3]
 [7 8 9]]

arr_2d_4[[0, 2], 0] :
[1 7]

arr_2d_4[[0, 2], [1, 2]] :
[2 9]

arr_2d_4[1, [0, 2]] :
[4 6]

arr_2d_4[[[0, 0], [2, 2]], [[0, 2], [0, 2]]] :
[[1 3]
 [7 9]]


## Boolean array indexing

In [13]:
arr_1d_5 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# boolean indexing
boolean_idx_1 = arr_1d_5 % 2 == 0  # [False True False True False True False True False]
boolean_idx_2 = arr_1d_5 > 5       # [False False False False False True True True True]
boolean_idx_3 = [True, True, False, False, True, True, False, False, True]

# indexing
bai_1 = arr_1d_5[boolean_idx_1]  # [2 4 6 8]
bai_2 = arr_1d_5[boolean_idx_2]  # [6 7 8 9]
bai_3 = arr_1d_5[boolean_idx_3]  # [1 2 5 6 9]

# log
print(f"arr_1d_5[boolean_idx_1] : {bai_1}")
print(f"arr_1d_5[boolean_idx_2] : {bai_2}")
print(f"arr_1d_5[boolean_idx_3] : {bai_3}")

arr_1d_5[boolean_idx_1] : [2 4 6 8]
arr_1d_5[boolean_idx_2] : [6 7 8 9]
arr_1d_5[boolean_idx_3] : [1 2 5 6 9]


In [14]:
arr_2d_5 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# boolean indexing
boolean_idx_4 = arr_2d_5 > 3                   # [False False False True True True True True True]
boolean_idx_5 = np.sum(arr_2d_5, axis=1) < 15  # [True False False]
boolean_idx_6 = np.sum(arr_2d_5, axis=0) < 16  # [True True  False]

# indexing
bai_4 = arr_2d_5[boolean_idx_4]
bai_5 = arr_2d_5[boolean_idx_5, boolean_idx_6]

# log
print(f"arr_2d_5[boolean_idx_4]                : {bai_4}")
print(f"arr_2d_5[boolean_idx_5, boolean_idx_6] : {bai_5}")

arr_2d_5[boolean_idx_4]                : [4 5 6 7 8 9]
arr_2d_5[boolean_idx_5, boolean_idx_6] : [1 2]
