# Dependencies

In [1]:
import numpy as np

# NumPy - Axes
Doc:
   - [numpy.org/doc/stable/glossary.html#term-axis](https://numpy.org/doc/stable/glossary.html#term-axis)

## 1-dimensional array

In [2]:
# The 1st axis has 8 elements
arr_1d_1 = np.array([15, 13, 20, 19, 0, 11, 18, 15])

# log
print(f"arr_1d_1.shape : {arr_1d_1.shape}")
print(f"arr_1d_1.ndim  : {arr_1d_1.ndim}")

arr_1d_1.shape : (8,)
arr_1d_1.ndim  : 1


In [3]:
# The 1st axis has 8 elements
arr_1d_2 = np.array(
    [
        15, 13, 20, 19, 0, 11, 18, 15
    ]
)

# log
print(f"arr_1d_2.shape : {arr_1d_2.shape}")
print(f"arr_1d_2.ndim  : {arr_1d_2.ndim}")

arr_1d_2.shape : (8,)
arr_1d_2.ndim  : 1


## 2-dimensional array

In [4]:
# The 1st axis has 3 elements
# The 2nd axis has 4 elements
arr_2d_1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# log
print(f"arr_2d_1.shape : {arr_2d_1.shape}")
print(f"arr_2d_1.ndim  : {arr_2d_1.ndim}")

arr_2d_1.shape : (3, 4)
arr_2d_1.ndim  : 2


In [5]:
# The 1st axis has 3 elements
# The 2nd axis has 4 elements
arr_2d_2 = np.array(
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ]
)

# log
print(f"arr_2d_2.shape : {arr_2d_2.shape}")
print(f"arr_2d_2.ndim  : {arr_2d_2.ndim}")

arr_2d_2.shape : (3, 4)
arr_2d_2.ndim  : 2


## 3-dimensional array

In [6]:
# The 1st axis has 2 elements
# The 2nd axis has 2 elements
# The 3rd axis has 3 elements
arr_3d_1 = np.array([[[255, 129, 255], [249, 230, 115]], [[255, 79, 79], [104, 203, 248]]])

# log
print(f"arr_3d_1.shape : {arr_3d_1.shape}")
print(f"arr_3d_1.ndim  : {arr_3d_1.ndim}")

arr_3d_1.shape : (2, 2, 3)
arr_3d_1.ndim  : 3


In [7]:
# The 1st axis has 2 elements
# The 2nd axis has 2 elements
# The 3rd axis has 3 elements
arr_3d_2 = np.array(
    [
        [
            [255, 129, 255],
            [249, 230, 115]
        ],
        [
            [255, 79, 79],
            [104, 203, 248]
        ]
    ]
)

# log
print(f"arr_3d_2.shape : {arr_3d_2.shape}")
print(f"arr_3d_2.ndim  : {arr_3d_2.ndim}")

arr_3d_2.shape : (2, 2, 3)
arr_3d_2.ndim  : 3


## 4-dimensional array

In [8]:
# The 1st axis has 2 elements
# The 2nd axis has 2 elements
# The 3rd axis has 2 elements
# The 4th axis has 2 elements
arr_4d_1 = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]])

# log
print(f"arr_4d_1.shape : {arr_4d_1.shape}")
print(f"arr_4d_1.ndim  : {arr_4d_1.ndim}")

arr_4d_1.shape : (2, 2, 2, 2)
arr_4d_1.ndim  : 4


In [9]:
# The 1st axis has 2 elements
# The 2nd axis has 2 elements
# The 3rd axis has 2 elements
# The 4th axis has 2 elements
arr_4d_2 = np.array(
    [
        [
            [
                [1, 2],
                [3, 4]
            ],
            [
                [5, 6],
                [7, 8]
            ]
        ],
        [
            [
                [9, 10],
                [11, 12]
            ],
            [
                [13, 14],
                [15, 16]
            ]
        ]
    ]
)

# log
print(f"arr_4d_2.shape : {arr_4d_2.shape}")
print(f"arr_4d_2.ndim  : {arr_4d_2.ndim}")

arr_4d_2.shape : (2, 2, 2, 2)
arr_4d_2.ndim  : 4


## Operations on different axes

In [10]:
arr_3d_3 = np.array([[[255, 129, 255], [249, 230, 115]], [[255, 79, 79], [104, 203, 248]]])

# np.array(
#     [
#         [
#             [255, 129, 255],
#             [249, 230, 115]
#         ],
#         [
#             [255, 79, 79],
#             [104, 203, 248]
#         ]
#     ]
# )

# sum
sres_1 = arr_3d_3.sum()  # arr_3d_3.sum(axis=None)
sres_2 = arr_3d_3.sum(axis=0)
sres_3 = arr_3d_3.sum(axis=1)
sres_4 = arr_3d_3.sum(axis=2)

# log
print(f"arr_3d_3.sum():\n{sres_1}", end='\n\n')
print(f"arr_3d_3.sum(axis=0):\n{sres_2}", end='\n\n')
print(f"arr_3d_3.sum(axis=1):\n{sres_3}", end='\n\n')
print(f"arr_3d_3.sum(axis=2):\n{sres_4}")

arr_3d_3.sum():
2201

arr_3d_3.sum(axis=0):
[[510 208 334]
 [353 433 363]]

arr_3d_3.sum(axis=1):
[[504 359 370]
 [359 282 327]]

arr_3d_3.sum(axis=2):
[[639 594]
 [413 555]]
