📝 **Author:** Amirhossein Heydari - 📧 **Email:** AmirhosseinHeydari78@gmail.com - 📍 **Linktree:** [linktr.ee/mr_pylin](https://linktr.ee/mr_pylin)

---

# Dependencies

In [1]:
import numpy as np

# NumPy - Modifications
Doc:
   - [numpy.org/doc/stable/reference/routines.array-manipulation.html](https://numpy.org/doc/stable/reference/routines.array-manipulation.html)

## Update values

### Update values by index

In [2]:
arr_1d_1 = np.array([0, 0, 0, 0])
arr_1d_2 = arr_1d_1  # this is not a copy of <arr>!

# update values by index
arr_1d_1[0] = 1
arr_1d_1[-3] = 2
arr_1d_1[2] = 3
arr_1d_1[-1] = 4

# log
print(f"arr_1d_1 : {arr_1d_1}")
print(f"arr_1d_2 : {arr_1d_2}")

arr_1d_1 : [1 2 3 4]
arr_1d_2 : [1 2 3 4]


### Update values by slice

In [3]:
arr_1d_3 = np.array([0, 0, 0, 0])

In [4]:
arr_1d_3[0:2] = 1
arr_1d_3[2:] = 2

# log
print(f"arr_1d_3 : {arr_1d_3}")

arr_1d_3 : [1 1 2 2]


In [5]:
arr_1d_3[:] = 10

# log
print(f"arr_1d_3 : {arr_1d_3}")

arr_1d_3 : [10 10 10 10]


In [6]:
arr_1d_3[2:1000] = 4

# log
print(f"arr_1d_3 : {arr_1d_3}")

arr_1d_3 : [10 10  4  4]


## numpy.append
Appends values to the end of an array, creating a new array.
```python
numpy.append(arr, values, axis)
```
Doc:
   - [numpy.org/doc/stable/reference/generated/numpy.append.html](https://numpy.org/doc/stable/reference/generated/numpy.append.html)

In [7]:
arr_1d_4 = np.array([0, 0, 0])

# append
append_1 = np.append(arr_1d_4, 1)
append_2 = np.append(arr_1d_4, [3, 2])
append_3 = np.append(arr_1d_4, [1, 1, 1])

# log
print(f"append_1 : {append_1}")
print(f"append_2 : {append_2}")
print(f"append_3 : {append_3}")

append_1 : [0 0 0 1]
append_2 : [0 0 0 3 2]
append_3 : [0 0 0 1 1 1]


In [8]:
arr_2d_1 = np.array([[0, 0], [1, 1]])

# append
append_4 = np.append(arr_2d_1, 2)
append_5 = np.append(arr_2d_1, [2, 2])
append_6 = np.append(arr_2d_1, [[2, 2]], axis=0)
append_7 = np.append(arr_2d_1, values=[[2], [3]], axis=1)

# log
print(f"append_4 :\n{append_4}", end='\n\n')
print(f"append_5 :\n{append_5}", end='\n\n')
print(f"append_6 :\n{append_6}", end='\n\n')
print(f"append_7 :\n{append_7}")

append_4 :
[0 0 1 1 2]

append_5 :
[0 0 1 1 2 2]

append_6 :
[[0 0]
 [1 1]
 [2 2]]

append_7 :
[[0 0 2]
 [1 1 3]]


## numpy.insert
Inserts values into an array at specified indices, creating a new array.
```python
numpy.insert(arr, obj, values, axis)
```
Doc:
   - [numpy.org/doc/stable/reference/generated/numpy.insert.html](https://numpy.org/doc/stable/reference/generated/numpy.insert.html)

In [9]:
arr_1d_5 = np.array([0, 0, 0])

# insert
insert_1 = np.insert(arr_1d_5, 0, 5)
insert_2 = np.insert(arr_1d_5, 1, [1, 1])
insert_3 = np.insert(arr_1d_5, 3, [1, 1])

# log
print(f"insert_1: {insert_1}")
print(f"insert_2: {insert_2}")
print(f"insert_3: {insert_3}")

insert_1: [5 0 0 0]
insert_2: [0 1 1 0 0]
insert_3: [0 0 0 1 1]


In [10]:
arr_2d_2 = np.array([[0, 0], [1, 1]])

# insert
insert_4 = np.insert(arr_2d_2, 0, 2)
insert_5 = np.insert(arr_2d_2, 0, [2, 2])
insert_6 = np.insert(arr_2d_2, obj=4, values=[2, 2])
insert_7 = np.insert(arr_2d_2, obj=0, values=[[2, 2]], axis=0)
insert_8 = np.insert(arr_2d_2, obj=2, values=[[2, 2]], axis=0)
insert_9 = np.insert(arr_2d_2, obj=0, values=[[2, 3]], axis=1)
insert_10 = np.insert(arr_2d_2, obj=2, values=[[2, 3]], axis=1)

# log
print(f"insert_4 :\n{insert_4}", end='\n\n')
print(f"insert_5 :\n{insert_5}", end='\n\n')
print(f"insert_6 :\n{insert_6}", end='\n\n')
print(f"insert_7 :\n{insert_7}", end='\n\n')
print(f"insert_8 :\n{insert_8}", end='\n\n')
print(f"insert_9 :\n{insert_9}", end='\n\n')
print(f"insert_10 :\n{insert_10}")

insert_4 :
[2 0 0 1 1]

insert_5 :
[2 2 0 0 1 1]

insert_6 :
[0 0 1 1 2 2]

insert_7 :
[[2 2]
 [0 0]
 [1 1]]

insert_8 :
[[0 0]
 [1 1]
 [2 2]]

insert_9 :
[[2 0 0]
 [3 1 1]]

insert_10 :
[[0 0 2]
 [1 1 3]]


## numpy.concatenate
Joins a sequence of arrays along an existing axis.
```python
numpy.concatenate(arrays, /, axis, ...)
```
Doc:
   - [numpy.org/doc/stable/reference/generated/numpy.concatenate.html](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html)

In [11]:
arr_1d_6 = np.array([1, 2, 3])
arr_1d_7 = np.array([4, 5, 6])
arr_2d_3 = np.array([[0, 1]])
arr_2d_4 = np.array([[4, 5], [6, 7]])
arr_2d_5 = np.array([[8, 9], [1, 2]])

# concatenate
concat_1 = np.concatenate((arr_1d_6, arr_1d_7))
concat_2 = np.concatenate((arr_1d_7, arr_1d_6))
concat_3 = np.concatenate((arr_1d_6, arr_1d_7, arr_1d_6))
concat_4 = np.concatenate((arr_2d_3, arr_2d_4))
concat_5 = np.concatenate((arr_2d_4, arr_2d_5))
concat_6 = np.concatenate((arr_2d_4, arr_2d_5), axis=0)
concat_7 = np.concatenate((arr_2d_4, arr_2d_5), axis=1)

# log
print(f"concat_1 :\n{concat_1}", end='\n\n')
print(f"concat_2 :\n{concat_2}", end='\n\n')
print(f"concat_3 :\n{concat_3}", end='\n\n')
print(f"concat_4 :\n{concat_4}", end='\n\n')
print(f"concat_5 :\n{concat_5}", end='\n\n')
print(f"concat_6 :\n{concat_6}", end='\n\n')
print(f"concat_7 :\n{concat_7}")

concat_1 :
[1 2 3 4 5 6]

concat_2 :
[4 5 6 1 2 3]

concat_3 :
[1 2 3 4 5 6 1 2 3]

concat_4 :
[[0 1]
 [4 5]
 [6 7]]

concat_5 :
[[4 5]
 [6 7]
 [8 9]
 [1 2]]

concat_6 :
[[4 5]
 [6 7]
 [8 9]
 [1 2]]

concat_7 :
[[4 5 8 9]
 [6 7 1 2]]


## numpy.hstack & numpy.vstack & numpy.dstack
hstack:
   - Stacks arrays horizontally (column-wise).
   - ```python
     numpy.hstack(tup, ...)
     ```

vstack:
   - Stacks arrays vertically (row-wise).
   - ```python
     numpy.vstack(tup, ...)
     ```

dstack:
   - Stacks arrays depth-wise (along the third axis).
   - ```python
     numpy.dstack(tup)
     ```

Doc:
   - [numpy.org/doc/stable/reference/routines.array-manipulation.html#joining-arrays](https://numpy.org/doc/stable/reference/routines.array-manipulation.html#joining-arrays)

In [12]:
arr_1d_8 = np.array([1, 2, 3])
arr_1d_9 = np.array([4, 5, 6])
arr_2d_6 = np.array([[4, 5], [6, 7]])
arr_2d_7 = np.array([[8, 9], [1, 2]])

In [13]:
# hstack
hstack_1 = np.hstack((arr_1d_8, arr_1d_9))
hstack_2 = np.hstack((arr_2d_6, arr_2d_7))

# log
print(f"hstack_1:\n{hstack_1}", end='\n\n')
print(f"hstack_2:\n{hstack_2}")

hstack_1:
[1 2 3 4 5 6]

hstack_2:
[[4 5 8 9]
 [6 7 1 2]]


In [14]:
# vstack
vstack_1 = np.vstack((arr_1d_8, arr_1d_9))
vstack_2 = np.vstack((arr_2d_6, arr_2d_7))

# log
print(f"vstack_1:\n{vstack_1}", end='\n\n')
print(f"vstack_2:\n{vstack_2}")

vstack_1:
[[1 2 3]
 [4 5 6]]

vstack_2:
[[4 5]
 [6 7]
 [8 9]
 [1 2]]


In [15]:
# dstack
dstack_1 = np.dstack((arr_1d_8, arr_1d_9))
dstack_2 = np.dstack((arr_2d_6, arr_2d_7, arr_2d_6))

# log
print(f"dstack_1:\n{dstack_1}", end='\n\n')
print(f"dstack_2:\n{dstack_2}")

dstack_1:
[[[1 4]
  [2 5]
  [3 6]]]

dstack_2:
[[[4 8 4]
  [5 9 5]]

 [[6 1 6]
  [7 2 7]]]


## numpy.delete
Deletes specified sub-arrays from an array along a given axis.
```python
numpy.delete(arr, obj, axis)
numpy.argwhere(a)
```
Docs:
   - [numpy.org/doc/stable/reference/generated/numpy.delete.html](https://numpy.org/doc/stable/reference/generated/numpy.delete.html)
   - [numpy.org/doc/stable/reference/generated/numpy.argwhere.html](https://numpy.org/doc/stable/reference/generated/numpy.argwhere.html)

### Delete by index

In [16]:
arr_1d_10 = np.array([1, 2, 3])

# delete
delete_1 = np.delete(arr_1d_10, 0)
delete_2 = np.delete(arr_1d_10, obj=2)

# log
print(f"delete_1: {delete_1}")
print(f"delete_2: {delete_2}")

delete_1: [2 3]
delete_2: [1 2]


In [17]:
arr_2d_8 = np.array([[1, 2, 3], [4, 5, 6]])

# delete
delete_3 = np.delete(arr_2d_8, 0)
delete_4 = np.delete(arr_2d_8, obj=1)
delete_5 = np.delete(arr_2d_8, obj=0, axis=0)
delete_6 = np.delete(arr_2d_8, obj=1, axis=0)
delete_7 = np.delete(arr_2d_8, obj=0, axis=1)
delete_8 = np.delete(arr_2d_8, obj=2, axis=1)

# log
print(f"delete_3:\n{delete_3}", end='\n\n')
print(f"delete_4:\n{delete_4}", end='\n\n')
print(f"delete_5:\n{delete_5}", end='\n\n')
print(f"delete_6:\n{delete_6}", end='\n\n')
print(f"delete_7:\n{delete_7}", end='\n\n')
print(f"delete_8:\n{delete_8}")

delete_3:
[2 3 4 5 6]

delete_4:
[1 3 4 5 6]

delete_5:
[[4 5 6]]

delete_6:
[[1 2 3]]

delete_7:
[[2 3]
 [5 6]]

delete_8:
[[1 2]
 [4 5]]


### Delete by value using numpy.argwhere

In [18]:
arr_1d_11 = np.array([1, 2, 3])

In [19]:
# find index
idx_1 = np.argwhere(arr_1d_11 == 2)

# delete
delete_9 = np.delete(arr_1d_11, idx_1)

# log
print(f"delete_9: {delete_9}")

delete_9: [1 3]


In [20]:
# find index
idx_2 = np.argwhere(arr_1d_11 == 3)

# delete
delete_10 = np.delete(arr_1d_11, idx_2)

# log
print(f"delete_10: {delete_10}")

delete_10: [1 2]


## numpy.reshape
Reshapes an array without changing its data.
```python
numpy.reshape(a, newshape, ...)
```
Doc:
   - [numpy.org/doc/stable/reference/generated/numpy.reshape.html](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)

In [21]:
arr_1d_12 = np.array([8, 9, 0, 3, 1, 6, 4, 2])

# reshape
reshape_1 = np.reshape(arr_1d_12, (2, 4))
reshape_2 = np.reshape(arr_1d_12, (2, 2, 2))
reshape_3 = np.reshape(arr_1d_12, newshape=(4, 2))

# log
print(f"reshape_1 :\n{reshape_1}")
print(f"reshape_1.ndim: {reshape_1.ndim}")
print(f"reshape_1.shape: {reshape_1.shape}", end='\n\n')
print(f"reshape_2 :\n{reshape_2}")
print(f"reshape_2.ndim: {reshape_2.ndim}")
print(f"reshape_2.shape: {reshape_2.shape}", end='\n\n')
print(f"reshape_3 :\n{reshape_3}")
print(f"reshape_3.ndim: {reshape_3.ndim}")
print(f"reshape_3.shape: {reshape_3.shape}")

reshape_1 :
[[8 9 0 3]
 [1 6 4 2]]
reshape_1.ndim: 2
reshape_1.shape: (2, 4)

reshape_2 :
[[[8 9]
  [0 3]]

 [[1 6]
  [4 2]]]
reshape_2.ndim: 3
reshape_2.shape: (2, 2, 2)

reshape_3 :
[[8 9]
 [0 3]
 [1 6]
 [4 2]]
reshape_3.ndim: 2
reshape_3.shape: (4, 2)


In [22]:
arr_2d_9 = np.array([[2, 3, 4], [7, 8, 9], [6, 5, 0]])

# reshape
reshape_4 = np.reshape(arr_2d_9, (9))
reshape_5 = np.reshape(arr_2d_9, (1, 9))

# log
print(f"reshape_4 :\n{reshape_4}")
print(f"reshape_4.ndim: {reshape_4.ndim}")
print(f"reshape_4.shape: {reshape_4.shape}", end='\n\n')
print(f"reshape_5 :\n{reshape_5}")
print(f"reshape_5.ndim: {reshape_5.ndim}")
print(f"reshape_5.shape: {reshape_5.shape}")

reshape_4 :
[2 3 4 7 8 9 6 5 0]
reshape_4.ndim: 1
reshape_4.shape: (9,)

reshape_5 :
[[2 3 4 7 8 9 6 5 0]]
reshape_5.ndim: 2
reshape_5.shape: (1, 9)


In [23]:
arr_3d_1 = np.array([[[2, 3], [0, 4]], [[7, 4], [4, 2]]])

# reshape
reshape_6 = np.reshape(arr_3d_1, (8))
reshape_7 = np.reshape(arr_3d_1, (2, 4))

# log
print(f"reshape_6 :\n{reshape_6}")
print(f"reshape_6.ndim: {reshape_6.ndim}")
print(f"reshape_6.shape: {reshape_6.shape}", end='\n\n')
print(f"reshape_7 :\n{reshape_7}")
print(f"reshape_7.ndim: {reshape_7.ndim}")
print(f"reshape_7.shape: {reshape_7.shape}")

reshape_6 :
[2 3 0 4 7 4 4 2]
reshape_6.ndim: 1
reshape_6.shape: (8,)

reshape_7 :
[[2 3 0 4]
 [7 4 4 2]]
reshape_7.ndim: 2
reshape_7.shape: (2, 4)


## numpy.ravel
Returns a contiguous flattened array.
```python
numpy.ravel(a, ...)
```
Doc:
   - [numpy.org/doc/stable/reference/generated/numpy.ravel.html](https://numpy.org/doc/stable/reference/generated/numpy.ravel.html)

In [24]:
arr_2d_10 = np.array([[2, 3, 4], [7, 8, 9], [6, 5, 0]])

# ravel
ravel_1 = np.ravel(arr_2d_10)
ravel_2 = np.ravel(arr_2d_10, order='F')

# log
print(f"ravel_1 :\n{ravel_1}")
print(f"ravel_1.ndim: {ravel_1.ndim}")
print(f"ravel_1.shape: {ravel_1.shape}", end='\n\n')
print(f"ravel_2 :\n{ravel_2}")
print(f"ravel_2.ndim: {ravel_2.ndim}")
print(f"ravel_2.shape: {ravel_2.shape}", end='\n\n')

ravel_1 :
[2 3 4 7 8 9 6 5 0]
ravel_1.ndim: 1
ravel_1.shape: (9,)

ravel_2 :
[2 7 6 3 8 5 4 9 0]
ravel_2.ndim: 1
ravel_2.shape: (9,)



In [25]:
arr_3d_2 = np.array([[[2, 3], [0, 4]], [[7, 4], [4, 2]]])

# ravel
ravel_3 = np.ravel(arr_3d_2)

# log
print(f"ravel_3 :\n{ravel_3}")
print(f"ravel_3.ndim: {ravel_3.ndim}")
print(f"ravel_3.shape: {ravel_3.shape}")

ravel_3 :
[2 3 0 4 7 4 4 2]
ravel_3.ndim: 1
ravel_3.shape: (8,)


## numpy.swapaxes
Interchanges two axes of an array.
```python
numpy.swapaxes(a, axis1, axis2)
```
Doc:
   - [numpy.org/doc/stable/reference/generated/numpy.swapaxes.html](https://numpy.org/doc/stable/reference/generated/numpy.swapaxes.html)

In [26]:
arr_2d_11 = np.array([[1, 2, 3], [4, 5, 6]])

# swapaxes
swapaxes_1 = np.swapaxes(arr_2d_11, 0, 1)

# log
print(f"swapaxes_1:\n{swapaxes_1}")
print(f"swapaxes_1.shape: {swapaxes_1.shape}")

swapaxes_1:
[[1 4]
 [2 5]
 [3 6]]
swapaxes_1.shape: (3, 2)


In [27]:
arr_3d_3 = np.array([[[1, 5], [2, 6]], [[3, 7], [4, 8]]])

# swapaxes
swapaxes_2 = np.swapaxes(arr_3d_3, 0, 1)
swapaxes_3 = np.swapaxes(arr_3d_3, 0, 2)
swapaxes_4 = np.swapaxes(arr_3d_3, 1, 2)

# log
print(f"swapaxes_2:\n{swapaxes_2}")
print(f"swapaxes_2.shape: {swapaxes_2.shape}", end='\n\n')
print(f"swapaxes_3:\n{swapaxes_3}")
print(f"swapaxes_3.shape: {swapaxes_3.shape}", end='\n\n')
print(f"swapaxes_4:\n{swapaxes_4}")
print(f"swapaxes_4.shape: {swapaxes_4.shape}")

swapaxes_2:
[[[1 5]
  [3 7]]

 [[2 6]
  [4 8]]]
swapaxes_2.shape: (2, 2, 2)

swapaxes_3:
[[[1 3]
  [2 4]]

 [[5 7]
  [6 8]]]
swapaxes_3.shape: (2, 2, 2)

swapaxes_4:
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
swapaxes_4.shape: (2, 2, 2)


## np.newaxis
Increases the dimensions of an array by one more dimension, when used with slicing.
```python
numpy.newaxis
```
Doc:
   - [numpy.org/devdocs/reference/constants.html#numpy.newaxis](https://numpy.org/devdocs/reference/constants.html#numpy.newaxis)

In [28]:
arr_1d_13 = np.array([1, 2, 3])

# newaxis
newaxis_1 = arr_1d_13[:,   np.newaxis]
newaxis_2 = arr_1d_13[..., np.newaxis]
newaxis_3 = arr_1d_13[:,   None]
newaxis_4 = arr_1d_13[..., None]

# log
print(f"newaxis_1 :\n{newaxis_1}", end='\n\n')
print(f"newaxis_2 :\n{newaxis_2}", end='\n\n')
print(f"newaxis_3 :\n{newaxis_3}", end='\n\n')
print(f"newaxis_4 :\n{newaxis_4}")

newaxis_1 :
[[1]
 [2]
 [3]]

newaxis_2 :
[[1]
 [2]
 [3]]

newaxis_3 :
[[1]
 [2]
 [3]]

newaxis_4 :
[[1]
 [2]
 [3]]


In [29]:
arr_2d_12 = np.array([[1, 2, 3], [4, 5, 6]])

# newaxis
newaxis_5 = arr_2d_12[:, np.newaxis, :]
newaxis_6 = arr_2d_12[..., None, :]
newaxis_7 = arr_2d_12[..., np.newaxis, :]
newaxis_8 = arr_2d_12[:, None, ...]

# log
print(f"newaxis_5 :\n{newaxis_5}", end='\n\n')
print(f"newaxis_6 :\n{newaxis_6}", end='\n\n')
print(f"newaxis_7 :\n{newaxis_7}", end='\n\n')
print(f"newaxis_8 :\n{newaxis_8}")

newaxis_5 :
[[[1 2 3]]

 [[4 5 6]]]

newaxis_6 :
[[[1 2 3]]

 [[4 5 6]]]

newaxis_7 :
[[[1 2 3]]

 [[4 5 6]]]

newaxis_8 :
[[[1 2 3]]

 [[4 5 6]]]


## numpy.expand_dims
Expands the shape of an array by inserting a new axis at a specified position.
```python
numpy.expand_dims(a, axis)
```
Doc:
   - [numpy.org/doc/stable/reference/generated/numpy.expand_dims.html](https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html)

In [30]:
arr_1d_14 = np.array([1, 2, 3])

# expand_dim
expand_dim_1 = np.expand_dims(arr_1d_14, axis=1)
expand_dim_2 = np.expand_dims(arr_1d_14, axis=0)

# log
print(f"expand_dim_1:\n{expand_dim_1}", end='\n\n')
print(f"expand_dim_2:\n{expand_dim_2}")

expand_dim_1:
[[1]
 [2]
 [3]]

expand_dim_2:
[[1 2 3]]


## numpy.squeeze
Removes single-dimensional entries from the shape of an array.
```python
numpy.squeeze(a, axis)
```
Doc:
   - [numpy.org/doc/stable/reference/generated/numpy.squeeze.html](https://numpy.org/doc/stable/reference/generated/numpy.squeeze.html)

In [31]:
arr_3d_4 = np.array([[[0], [1], [2], [3]]])

# squeeze
squeeze_1 = np.squeeze(arr_3d_4)

# log
print(f"squeeze_1: {squeeze_1}")

squeeze_1: [0 1 2 3]


## numpy.tile
Constructs a new array by repeating the input array the specified number of times.
```python
numpy.tile(A, reps)
```
Doc:
   - [numpy.org/doc/stable/reference/generated/numpy.tile.html#numpy.tile](https://numpy.org/doc/stable/reference/generated/numpy.tile.html#numpy.tile)

In [32]:
arr_1d_15 = np.array([1, 2, 3])
arr_2d_13 = np.array([[4, 2], [5, 1]])

# tile
tile_1 = np.tile(arr_1d_15, reps=2)
tile_2 = np.tile(arr_1d_15, (3, 2))
tile_3 = np.tile(arr_2d_13, 2)
tile_4 = np.tile(arr_2d_13, (2, 3))

# log
print(f"tile_1 :\n{tile_1}", end='\n\n')
print(f"tile_2 :\n{tile_2}", end='\n\n')
print(f"tile_3 :\n{tile_3}", end='\n\n')
print(f"tile_4 :\n{tile_4}")

tile_1 :
[1 2 3 1 2 3]

tile_2 :
[[1 2 3 1 2 3]
 [1 2 3 1 2 3]
 [1 2 3 1 2 3]]

tile_3 :
[[4 2 4 2]
 [5 1 5 1]]

tile_4 :
[[4 2 4 2 4 2]
 [5 1 5 1 5 1]
 [4 2 4 2 4 2]
 [5 1 5 1 5 1]]


## numpy.repeat
Repeats elements of an array along a specified axis.
```python
numpy.repeat(a, repeats, axis)
```
Doc:
   - [numpy.org/doc/stable/reference/generated/numpy.repeat.html#numpy.repeat](https://numpy.org/doc/stable/reference/generated/numpy.repeat.html#numpy.repeat)

In [33]:
arr_1d_16 = np.array([1, 2, 3])
arr_2d_13 = np.array([[4, 2], [5, 1]])

# repeat
repeat_1 = np.repeat(arr_1d_16, repeats=2)
repeat_2 = np.repeat(arr_2d_13, 2)
repeat_3 = np.repeat(arr_2d_13, 2, axis=0)
repeat_4 = np.repeat(arr_2d_13, 3, axis=1)

# log
print(f"repeat_1 :\n{repeat_1}", end='\n\n')
print(f"repeat_2 :\n{repeat_2}", end='\n\n')
print(f"repeat_3 :\n{repeat_3}", end='\n\n')
print(f"repeat_4 :\n{repeat_4}")

repeat_1 :
[1 1 2 2 3 3]

repeat_2 :
[4 4 2 2 5 5 1 1]

repeat_3 :
[[4 2]
 [4 2]
 [5 1]
 [5 1]]

repeat_4 :
[[4 4 4 2 2 2]
 [5 5 5 1 1 1]]
