📝 **Author:** Amirhossein Heydari - 📧 **Email:** AmirhosseinHeydari78@gmail.com - 📍 **Linktree:** [linktr.ee/mr_pylin](https://linktr.ee/mr_pylin)

---

# Dependencies

In [155]:
import numpy as np

# NumPy - Manipulation
   - A comprehensive details on functions for reshaping, joining, splitting, and modifying arrays.

📝 Doc:
   - Array manipulation routines: [numpy.org/doc/stable/reference/routines.array-manipulation.html](https://numpy.org/doc/stable/reference/routines.array-manipulation.html)

## Changing array shape

<table style="margin: 0 auto;">
   <thead>
      <tr>
         <th style="text-align: center;">Command</th>
         <th style="text-align: center;">Description</th>
         <th style="text-align: center;">Details</th>
      </tr>
   </thead>
   <tbody>
      <tr>
         <td><code>np.reshape(...)</code></td>
         <td>Gives a new shape to an array without changing its data</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.reshape.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.ravel(...)</code></td>
         <td>Return a contiguous flattened array</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.ravel.html">link</a></td>
      </tr>
      <tr>
         <td><code>ndarray.flatten(...)</code></td>
         <td>Return a copy of the array collapsed into one dimension</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html">link</a></td>
      </tr>
   </tbody>
</table>

### numpy.reshape
   - Changes the shape of an array without altering its data.
   - It returns a new view of the original array if possible, otherwise a copy.
   - The total number of elements must remain the same

In [156]:
arr_1d_1 = np.array([8, 9, 0, 3, 1, 6, 4, 2])

# reshape
reshape_1 = np.reshape(arr_1d_1, (2, 4))
reshape_2 = np.reshape(arr_1d_1, (2, 2, 2))
reshape_3 = np.reshape(arr_1d_1, shape=(4, 2))

# log
print(f"reshape_1 :\n{reshape_1}")
print(f"reshape_1.ndim: {reshape_1.ndim}")
print(f"reshape_1.shape: {reshape_1.shape}", end=f"\n{'-' * 50}\n")
print(f"reshape_2 :\n{reshape_2}")
print(f"reshape_2.ndim: {reshape_2.ndim}")
print(f"reshape_2.shape: {reshape_2.shape}", end=f"\n{'-' * 50}\n")
print(f"reshape_3 :\n{reshape_3}")
print(f"reshape_3.ndim: {reshape_3.ndim}")
print(f"reshape_3.shape: {reshape_3.shape}")

reshape_1 :
[[8 9 0 3]
 [1 6 4 2]]
reshape_1.ndim: 2
reshape_1.shape: (2, 4)
--------------------------------------------------
reshape_2 :
[[[8 9]
  [0 3]]

 [[1 6]
  [4 2]]]
reshape_2.ndim: 3
reshape_2.shape: (2, 2, 2)
--------------------------------------------------
reshape_3 :
[[8 9]
 [0 3]
 [1 6]
 [4 2]]
reshape_3.ndim: 2
reshape_3.shape: (4, 2)


In [157]:
arr_2d_1 = np.array([[2, 3, 4], [7, 8, 9], [6, 5, 0]])

# reshape
reshape_4 = np.reshape(arr_2d_1, (9))
reshape_5 = np.reshape(arr_2d_1, (1, 9))

# log
print(f"reshape_4 :\n{reshape_4}")
print(f"reshape_4.ndim: {reshape_4.ndim}")
print(f"reshape_4.shape: {reshape_4.shape}", end=f"\n{'-' * 50}\n")
print(f"reshape_5 :\n{reshape_5}")
print(f"reshape_5.ndim: {reshape_5.ndim}")
print(f"reshape_5.shape: {reshape_5.shape}")

reshape_4 :
[2 3 4 7 8 9 6 5 0]
reshape_4.ndim: 1
reshape_4.shape: (9,)
--------------------------------------------------
reshape_5 :
[[2 3 4 7 8 9 6 5 0]]
reshape_5.ndim: 2
reshape_5.shape: (1, 9)


In [158]:
arr_3d_1 = np.array([[[2, 3], [0, 4]], [[7, 4], [4, 2]]])

# reshape
reshape_6 = np.reshape(arr_3d_1, (8))
reshape_7 = np.reshape(arr_3d_1, (2, 4))

# log
print(f"reshape_6 :\n{reshape_6}")
print(f"reshape_6.ndim: {reshape_6.ndim}")
print(f"reshape_6.shape: {reshape_6.shape}", end=f"\n{'-' * 50}\n")
print(f"reshape_7 :\n{reshape_7}")
print(f"reshape_7.ndim: {reshape_7.ndim}")
print(f"reshape_7.shape: {reshape_7.shape}")

reshape_6 :
[2 3 0 4 7 4 4 2]
reshape_6.ndim: 1
reshape_6.shape: (8,)
--------------------------------------------------
reshape_7 :
[[2 3 0 4]
 [7 4 4 2]]
reshape_7.ndim: 2
reshape_7.shape: (2, 4)


### numpy.ravel
   - Returns a flattened view of the array if possible, otherwise returns a copy.

In [159]:
arr_2d_2 = np.array([[2, 3, 4], [7, 8, 9], [6, 5, 0]])

# ravel
ravel_1 = np.ravel(arr_2d_2)
ravel_2 = np.ravel(arr_2d_2, order="F")

# log
print(f"ravel_1 :\n{ravel_1}")
print(f"ravel_1.ndim: {ravel_1.ndim}")
print(f"ravel_1.shape: {ravel_1.shape}", end=f"\n{'-' * 50}\n")
print(f"ravel_2 :\n{ravel_2}")
print(f"ravel_2.ndim: {ravel_2.ndim}")
print(f"ravel_2.shape: {ravel_2.shape}")

ravel_1 :
[2 3 4 7 8 9 6 5 0]
ravel_1.ndim: 1
ravel_1.shape: (9,)
--------------------------------------------------
ravel_2 :
[2 7 6 3 8 5 4 9 0]
ravel_2.ndim: 1
ravel_2.shape: (9,)


In [160]:
arr_3d_2 = np.array([[[2, 3], [0, 4]], [[7, 4], [4, 2]]])

# ravel
ravel_3 = np.ravel(arr_3d_2)

# log
print(f"ravel_3 :\n{ravel_3}")
print(f"ravel_3.ndim: {ravel_3.ndim}")
print(f"ravel_3.shape: {ravel_3.shape}")

ravel_3 :
[2 3 0 4 7 4 4 2]
ravel_3.ndim: 1
ravel_3.shape: (8,)


### numpy.ndarray.flatten
   - Always returns a copy of the array, ensuring a new, independent one-dimensional array

In [161]:
arr_2d_3 = np.array([[2, 3, 4], [7, 8, 9], [6, 5, 0]])

# ravel
flatten_1 = arr_2d_3.flatten()
flatten_2 = arr_2d_3.flatten(order="F")

# log
print(f"flatten_1 :\n{flatten_1}")
print(f"flatten_1.ndim: {flatten_1.ndim}")
print(f"flatten_1.shape: {flatten_1.shape}", end=f"\n{'-' * 50}\n")
print(f"flatten_2 :\n{flatten_2}")
print(f"flatten_2.ndim: {flatten_2.ndim}")
print(f"flatten_2.shape: {flatten_2.shape}")

flatten_1 :
[2 3 4 7 8 9 6 5 0]
flatten_1.ndim: 1
flatten_1.shape: (9,)
--------------------------------------------------
flatten_2 :
[2 7 6 3 8 5 4 9 0]
flatten_2.ndim: 1
flatten_2.shape: (9,)


## Transpose-like operations

<table style="margin: 0 auto;">
   <thead>
      <tr>
         <th style="text-align: center;">Command</th>
         <th style="text-align: center;">Alias</th>
         <th style="text-align: center;">Description</th>
         <th style="text-align: center;">Details</th>
      </tr>
   </thead>
   <tbody>
      <tr>
         <td><code>np.moveaxis(...)</code></td>
         <td><code>-</code></td>
         <td>Move axes of an array to new positions</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.moveaxis.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.swapaxis(...)</code></td>
         <td><code>-</code></td>
         <td>Interchange two axes of an array</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.swapaxes.html">link</a></td>
      </tr>
      <tr>
         <td><code>ndarray.T</code></td>
         <td><code>-</code></td>
         <td>View of the transposed array</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.ndarray.T.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.transpose(...)</code></td>
         <td><code>np.permute_dims(...)</code></td>
         <td>Returns an array with axes transposed</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.transpose.html">link</a></td>
      </tr>
   </tbody>
</table>

### numpy.moveaxis

In [162]:
arr_3d_3 = np.array([[[1, 2, 3], [4, 5, 6]]])

# moveaxis
moveaxis_1 = np.moveaxis(arr_3d_3, 0, 1)
moveaxis_2 = np.moveaxis(arr_3d_3, 0, 2)
moveaxis_3 = np.moveaxis(arr_3d_3, [1, 0], [2, 1])

# log
print(f"arr_3d_3:\n{arr_3d_3}")
print(f"arr_3d_3.shape: {arr_3d_3.shape}", end=f"\n{'-' * 50}\n")
print(f"moveaxis_1:\n{moveaxis_1}")
print(f"moveaxis_1.shape: {moveaxis_1.shape}", end=f"\n{'-' * 50}\n")
print(f"moveaxis_2:\n{moveaxis_2}")
print(f"moveaxis_2.shape: {moveaxis_2.shape}", end=f"\n{'-' * 50}\n")
print(f"moveaxis_3:\n{moveaxis_3}")
print(f"moveaxis_3.shape: {moveaxis_3.shape}")

arr_3d_3:
[[[1 2 3]
  [4 5 6]]]
arr_3d_3.shape: (1, 2, 3)
--------------------------------------------------
moveaxis_1:
[[[1 2 3]]

 [[4 5 6]]]
moveaxis_1.shape: (2, 1, 3)
--------------------------------------------------
moveaxis_2:
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
moveaxis_2.shape: (2, 3, 1)
--------------------------------------------------
moveaxis_3:
[[[1 4]]

 [[2 5]]

 [[3 6]]]
moveaxis_3.shape: (3, 1, 2)


### numpy.swapaxes

In [163]:
arr_2d_4 = np.array([[1, 2, 3], [4, 5, 6]])

# swapaxes
swapaxes_1 = np.swapaxes(arr_2d_4, 0, 1)

# log
print(f"swapaxes_1:\n{swapaxes_1}")
print(f"swapaxes_1.shape: {swapaxes_1.shape}")

swapaxes_1:
[[1 4]
 [2 5]
 [3 6]]
swapaxes_1.shape: (3, 2)


In [164]:
arr_3d_4 = np.array([[[1, 5], [2, 6]], [[3, 7], [4, 8]]])

# swapaxes
swapaxes_2 = np.swapaxes(arr_3d_4, 0, 1)
swapaxes_3 = np.swapaxes(arr_3d_4, 0, 2)
swapaxes_4 = np.swapaxes(arr_3d_4, 1, 2)

# log
print(f"swapaxes_2:\n{swapaxes_2}")
print(f"swapaxes_2.shape: {swapaxes_2.shape}", end=f"\n{'-' * 50}\n")
print(f"swapaxes_3:\n{swapaxes_3}")
print(f"swapaxes_3.shape: {swapaxes_3.shape}", end=f"\n{'-' * 50}\n")
print(f"swapaxes_4:\n{swapaxes_4}")
print(f"swapaxes_4.shape: {swapaxes_4.shape}")

swapaxes_2:
[[[1 5]
  [3 7]]

 [[2 6]
  [4 8]]]
swapaxes_2.shape: (2, 2, 2)
--------------------------------------------------
swapaxes_3:
[[[1 3]
  [2 4]]

 [[5 7]
  [6 8]]]
swapaxes_3.shape: (2, 2, 2)
--------------------------------------------------
swapaxes_4:
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
swapaxes_4.shape: (2, 2, 2)


### numpy.ndarray.T

In [165]:
arr_2d_5 = np.array([[1, 2, 3], [4, 5, 6]])

# ndarray.T
ndarray_t_1 = arr_2d_5.T

# log
print(f"ndarray_t_1:\n{ndarray_t_1}")
print(f"ndarray_t_1.shape: {ndarray_t_1.shape}")

ndarray_t_1:
[[1 4]
 [2 5]
 [3 6]]
ndarray_t_1.shape: (3, 2)


### numpy.transpose (numpy.permute_dims)

In [166]:
arr_3d_5 = np.array([[[1, 2, 3], [4, 5, 6]]])

# transpose
transpose_1 = np.transpose(arr_3d_5, [0, 1, 2])
transpose_2 = np.transpose(arr_3d_5, [2, 1, 0])
transpose_3 = np.transpose(arr_3d_5, [1, 2, 0])

# log
print(f"arr_3d_5:\n{arr_3d_5}")
print(f"arr_3d_5.shape: {arr_3d_5.shape}", end=f"\n{'-' * 50}\n")
print(f"transpose_1:\n{transpose_1}")
print(f"transpose_1.shape: {transpose_1.shape}", end=f"\n{'-' * 50}\n")
print(f"transpose_2:\n{transpose_2}")
print(f"transpose_2.shape: {transpose_2.shape}", end=f"\n{'-' * 50}\n")
print(f"transpose_3:\n{transpose_3}")
print(f"transpose_3.shape: {transpose_3.shape}")

arr_3d_5:
[[[1 2 3]
  [4 5 6]]]
arr_3d_5.shape: (1, 2, 3)
--------------------------------------------------
transpose_1:
[[[1 2 3]
  [4 5 6]]]
transpose_1.shape: (1, 2, 3)
--------------------------------------------------
transpose_2:
[[[1]
  [4]]

 [[2]
  [5]]

 [[3]
  [6]]]
transpose_2.shape: (3, 2, 1)
--------------------------------------------------
transpose_3:
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
transpose_3.shape: (2, 3, 1)


## Changing number of dimensions

<table style="margin: 0 auto;">
   <thead>
      <tr>
         <th style="text-align: center;">Command</th>
         <th style="text-align: center;">Description</th>
         <th style="text-align: center;">Details</th>
      </tr>
   </thead>
   <tbody>
      <tr>
         <td><code>np.newaxis</code></td>
         <td>A convenient alias for <code>None</code>, useful for indexing arrays</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/2.1/reference/constants.html#numpy.newaxis">link</a></td>
      </tr>
      <tr>
         <td><code>np.expand_dims(...)</code></td>
         <td>Expand the shape of an array</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.squeeze(...)</code></td>
         <td>Remove axes of length one from a</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.squeeze.html">link</a></td>
      </tr>
   </tbody>
</table>

### numpy.newaxis

In [167]:
arr_1d_2 = np.array([1, 2, 3])

# newaxis
newaxis_1 = arr_1d_2[:, np.newaxis]
newaxis_2 = arr_1d_2[..., np.newaxis]
newaxis_3 = arr_1d_2[:, None]
newaxis_4 = arr_1d_2[..., None]

# log
print(f"newaxis_1 :\n{newaxis_1}", end=f"\n{'-' * 50}\n")
print(f"newaxis_2 :\n{newaxis_2}", end=f"\n{'-' * 50}\n")
print(f"newaxis_3 :\n{newaxis_3}", end=f"\n{'-' * 50}\n")
print(f"newaxis_4 :\n{newaxis_4}")

newaxis_1 :
[[1]
 [2]
 [3]]
--------------------------------------------------
newaxis_2 :
[[1]
 [2]
 [3]]
--------------------------------------------------
newaxis_3 :
[[1]
 [2]
 [3]]
--------------------------------------------------
newaxis_4 :
[[1]
 [2]
 [3]]


In [168]:
arr_2d_6 = np.array([[1, 2, 3], [4, 5, 6]])

# newaxis
newaxis_5 = arr_2d_6[:, np.newaxis, :]
newaxis_6 = arr_2d_6[..., None, :]
newaxis_7 = arr_2d_6[..., np.newaxis, :]
newaxis_8 = arr_2d_6[:, None, ...]

# log
print(f"newaxis_5 :\n{newaxis_5}", end=f"\n{'-' * 50}\n")
print(f"newaxis_6 :\n{newaxis_6}", end=f"\n{'-' * 50}\n")
print(f"newaxis_7 :\n{newaxis_7}", end=f"\n{'-' * 50}\n")
print(f"newaxis_8 :\n{newaxis_8}")

newaxis_5 :
[[[1 2 3]]

 [[4 5 6]]]
--------------------------------------------------
newaxis_6 :
[[[1 2 3]]

 [[4 5 6]]]
--------------------------------------------------
newaxis_7 :
[[[1 2 3]]

 [[4 5 6]]]
--------------------------------------------------
newaxis_8 :
[[[1 2 3]]

 [[4 5 6]]]


### numpy.expand_dims

In [169]:
arr_1d_3 = np.array([1, 2, 3])

# expand_dim
expand_dim_1 = np.expand_dims(arr_1d_3, axis=1)
expand_dim_2 = np.expand_dims(arr_1d_3, axis=0)

# log
print(f"expand_dim_1:\n{expand_dim_1}")
print(f"expand_dim_1.shape: {expand_dim_1.shape}", end=f"\n{'-' * 50}\n")
print(f"expand_dim_2:\n{expand_dim_2}")
print(f"expand_dim_2.shape: {expand_dim_2.shape}")

expand_dim_1:
[[1]
 [2]
 [3]]
expand_dim_1.shape: (3, 1)
--------------------------------------------------
expand_dim_2:
[[1 2 3]]
expand_dim_2.shape: (1, 3)


### numpy.squeeze

In [170]:
arr_3d_6 = np.array([[[0], [1], [2], [3]]])

# squeeze
squeeze_1 = np.squeeze(arr_3d_6)

# log
print(f"squeeze_1       : {squeeze_1}")
print(f"squeeze_1.shape : {squeeze_1.shape}")

squeeze_1       : [0 1 2 3]
squeeze_1.shape : (4,)


## Joining arrays

<table style="margin: 0 auto;">
   <thead>
      <tr>
         <th style="text-align: center;">Command</th>
         <th style="text-align: center;">Alias</th>
         <th style="text-align: center;">Description</th>
         <th style="text-align: center;">Details</th>
      </tr>
   </thead>
   <tbody>
      <tr>
         <td><code>np.concatenate(...)</code></td>
         <td><code>np.concat(...)</code></td>
         <td>Join a sequence of arrays along an existing axis</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.stack(...)</code></td>
         <td><code>-</code></td>
         <td>Join a sequence of arrays along a new axis</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.stack.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.vstack(...)</code></td>
         <td><code>-</code></td>
         <td>Stack arrays in sequence vertically (row wise)</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.vstack.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.hstack(...)</code></td>
         <td><code>-</code></td>
         <td>Stack arrays in sequence horizontally (column wise)</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.hstack.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.dstack(...)</code></td>
         <td><code>-</code></td>
         <td>Stack arrays in sequence depth wise (along third axis)</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.dstack.html">link</a></td>
      </tr>
   </tbody>
</table>

### numpy.concatenate

In [171]:
arr_1d_4 = np.array([1, 2, 3])
arr_1d_5 = np.array([4, 5, 6])
arr_2d_7 = np.array([[0, 1]])
arr_2d_8 = np.array([[4, 5], [6, 7]])
arr_2d_9 = np.array([[8, 9], [1, 2]])

# concatenate
concat_1 = np.concatenate((arr_1d_4, arr_1d_5))
concat_2 = np.concatenate((arr_1d_5, arr_1d_4))
concat_3 = np.concatenate((arr_1d_4, arr_1d_5, arr_1d_4))
concat_4 = np.concatenate((arr_2d_7, arr_2d_8))
concat_5 = np.concatenate((arr_2d_8, arr_2d_9))
concat_6 = np.concatenate((arr_2d_8, arr_2d_9), axis=0)
concat_7 = np.concatenate((arr_2d_8, arr_2d_9), axis=1)

# log
print(f"concat_1 :\n{concat_1}", end=f"\n{'-' * 50}\n")
print(f"concat_2 :\n{concat_2}", end=f"\n{'-' * 50}\n")
print(f"concat_3 :\n{concat_3}", end=f"\n{'-' * 50}\n")
print(f"concat_4 :\n{concat_4}", end=f"\n{'-' * 50}\n")
print(f"concat_5 :\n{concat_5}", end=f"\n{'-' * 50}\n")
print(f"concat_6 :\n{concat_6}", end=f"\n{'-' * 50}\n")
print(f"concat_7 :\n{concat_7}")

concat_1 :
[1 2 3 4 5 6]
--------------------------------------------------
concat_2 :
[4 5 6 1 2 3]
--------------------------------------------------
concat_3 :
[1 2 3 4 5 6 1 2 3]
--------------------------------------------------
concat_4 :
[[0 1]
 [4 5]
 [6 7]]
--------------------------------------------------
concat_5 :
[[4 5]
 [6 7]
 [8 9]
 [1 2]]
--------------------------------------------------
concat_6 :
[[4 5]
 [6 7]
 [8 9]
 [1 2]]
--------------------------------------------------
concat_7 :
[[4 5 8 9]
 [6 7 1 2]]


### numpy.stack

In [172]:
arr_2d_10 = np.array([[4, 5], [6, 7]])
arr_2d_11 = np.array([[8, 9], [1, 2]])
arr_2d_12 = np.array([[3, 3], [4, 4]])

# stack
stack_1 = np.stack((arr_2d_10, arr_2d_11, arr_2d_12), axis=0)
stack_2 = np.stack((arr_2d_10, arr_2d_11, arr_2d_12), axis=1)

# log
print(f"stack_1:\n{stack_1}")
print(f"stack_1.shape: {stack_1.shape}", end=f"\n{'-' * 50}\n")
print(f"stack_2:\n{stack_2}")
print(f"stack_2.shape: {stack_2.shape}")

stack_1:
[[[4 5]
  [6 7]]

 [[8 9]
  [1 2]]

 [[3 3]
  [4 4]]]
stack_1.shape: (3, 2, 2)
--------------------------------------------------
stack_2:
[[[4 5]
  [8 9]
  [3 3]]

 [[6 7]
  [1 2]
  [4 4]]]
stack_2.shape: (2, 3, 2)


#### numpy.vstack

In [173]:
arr_2d_10 = np.array([[4, 5], [6, 7]])
arr_2d_11 = np.array([[8, 9], [1, 2]])
arr_2d_12 = np.array([[3, 3], [4, 4]])

# vstack
vstack_1 = np.vstack((arr_2d_10, arr_2d_11, arr_2d_12))

# log
print(f"vstack_1:\n{vstack_1}")
print(f"vstack_1.shape: {vstack_1.shape}")

vstack_1:
[[4 5]
 [6 7]
 [8 9]
 [1 2]
 [3 3]
 [4 4]]
vstack_1.shape: (6, 2)


#### numpy.hstack

In [174]:
arr_2d_10 = np.array([[4, 5], [6, 7]])
arr_2d_11 = np.array([[8, 9], [1, 2]])
arr_2d_12 = np.array([[3, 3], [4, 4]])

# hstack
hstack_1 = np.hstack((arr_2d_10, arr_2d_11, arr_2d_12))

# log
print(f"hstack_1:\n{hstack_1}")
print(f"hstack_1.shape: {hstack_1.shape}")

hstack_1:
[[4 5 8 9 3 3]
 [6 7 1 2 4 4]]
hstack_1.shape: (2, 6)


#### numpy.dstack

In [175]:
arr_2d_10 = np.array([[4, 5], [6, 7]])
arr_2d_11 = np.array([[8, 9], [1, 2]])
arr_2d_12 = np.array([[3, 3], [4, 4]])

# vstack
dstack_1 = np.dstack((arr_2d_10, arr_2d_11, arr_2d_12))

# log
print(f"dstack_1:\n{dstack_1}")
print(f"dstack_1.shape: {dstack_1.shape}")

dstack_1:
[[[4 8 3]
  [5 9 3]]

 [[6 1 4]
  [7 2 4]]]
dstack_1.shape: (2, 2, 3)


## Splitting arrays

<table style="margin: 0 auto;">
   <thead>
      <tr>
         <th style="text-align: center;">Command</th>
         <th style="text-align: center;">Description</th>
         <th style="text-align: center;">Details</th>
      </tr>
   </thead>
   <tbody>
      <tr>
         <td><code>np.split(...)</code></td>
         <td>Split an array into multiple sub-arrays as views into ary</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.split.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.vsplit(...)</code></td>
         <td>Split an array into multiple sub-arrays vertically (row-wise)</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.vsplit.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.hsplit(...)</code></td>
         <td>Split an array into multiple sub-arrays horizontally (column-wise)</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.hsplit.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.dsplit(...)</code></td>
         <td>Split array into multiple sub-arrays along the 3rd axis (depth)</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.dsplit.html">link</a></td>
      </tr>
   </tbody>
</table>

### numpy.split

In [176]:
arr_2d_13 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

# split
split_1 = np.split(arr_2d_13, 2, 0)
split_2 = np.split(arr_2d_13, 2, 1)

# log
print(f"split_1: {split_1}", end=f"\n{'-' * 50}\n")
print(f"split_2: {split_2}")

split_1: [array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]
--------------------------------------------------
split_2: [array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]


#### numpy.vsplit

In [177]:
arr_2d_13 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

# vsplit
vsplit_1 = np.vsplit(arr_2d_13, 2)

# log
print(f"vsplit_1:\n{vsplit_1}")

vsplit_1:
[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]


#### numpy.hsplit

In [178]:
arr_2d_13 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

# vsplit
hsplit_1 = np.hsplit(arr_2d_13, 2)

# log
print(f"hsplit_1:\n{hsplit_1}")

hsplit_1:
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]


#### numpy.dsplit

In [179]:
arr_3d_7 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
dsplit_1 = np.dsplit(arr_3d_7, 2)

# log
print(f"dsplit_1:\n{dsplit_1}")

dsplit_1:
[array([[[ 1],
        [ 3]],

       [[ 5],
        [ 7]],

       [[ 9],
        [11]]]), array([[[ 2],
        [ 4]],

       [[ 6],
        [ 8]],

       [[10],
        [12]]])]


## Tiling arrays

<table style="margin: 0 auto;">
   <thead>
      <tr>
         <th style="text-align: center;">Command</th>
         <th style="text-align: center;">Description</th>
         <th style="text-align: center;">Details</th>
      </tr>
   </thead>
   <tbody>
      <tr>
         <td><code>np.tile(...)</code></td>
         <td>Construct an array by repeating A the number of times given by reps</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.tile.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.repeat(...)</code></td>
         <td>Repeat each element of an array after themselves</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.repeat.html">link</a></td>
      </tr>
   </tbody>
</table>

### numpy.tile

In [180]:
arr_1d_6 = np.array([1, 2, 3])
arr_2d_14 = np.array([[4, 2], [5, 1]])

# tile
tile_1 = np.tile(arr_1d_6, reps=2)
tile_2 = np.tile(arr_1d_6, (3, 2))
tile_3 = np.tile(arr_2d_14, 2)
tile_4 = np.tile(arr_2d_14, (2, 3))

# log
print(f"tile_1 :\n{tile_1}", end=f"\n{'-' * 50}\n")
print(f"tile_2 :\n{tile_2}", end=f"\n{'-' * 50}\n")
print(f"tile_3 :\n{tile_3}", end=f"\n{'-' * 50}\n")
print(f"tile_4 :\n{tile_4}")

tile_1 :
[1 2 3 1 2 3]
--------------------------------------------------
tile_2 :
[[1 2 3 1 2 3]
 [1 2 3 1 2 3]
 [1 2 3 1 2 3]]
--------------------------------------------------
tile_3 :
[[4 2 4 2]
 [5 1 5 1]]
--------------------------------------------------
tile_4 :
[[4 2 4 2 4 2]
 [5 1 5 1 5 1]
 [4 2 4 2 4 2]
 [5 1 5 1 5 1]]


### numpy.repeat

In [181]:
arr_1d_7 = np.array([1, 2, 3])
arr_2d_15 = np.array([[4, 2], [5, 1]])

# repeat
repeat_1 = np.repeat(arr_1d_7, repeats=2)
repeat_2 = np.repeat(arr_2d_15, 2)
repeat_3 = np.repeat(arr_2d_15, 2, axis=0)
repeat_4 = np.repeat(arr_2d_15, 3, axis=1)

# log
print(f"repeat_1 :\n{repeat_1}", end=f"\n{'-' * 50}\n")
print(f"repeat_2 :\n{repeat_2}", end=f"\n{'-' * 50}\n")
print(f"repeat_3 :\n{repeat_3}", end=f"\n{'-' * 50}\n")
print(f"repeat_4 :\n{repeat_4}")

repeat_1 :
[1 1 2 2 3 3]
--------------------------------------------------
repeat_2 :
[4 4 2 2 5 5 1 1]
--------------------------------------------------
repeat_3 :
[[4 2]
 [4 2]
 [5 1]
 [5 1]]
--------------------------------------------------
repeat_4 :
[[4 4 4 2 2 2]
 [5 5 5 1 1 1]]


## Adding and removing elements

<table style="margin: 0 auto;">
   <thead>
      <tr>
         <th style="text-align: center;">Command</th>
         <th style="text-align: center;">Description</th>
         <th style="text-align: center;">Details</th>
      </tr>
   </thead>
   <tbody>
      <tr>
         <td><code>np.delete(...)</code></td>
         <td>Return a new array with sub-arrays along an axis deleted</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.delete.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.insert(...)</code></td>
         <td>Insert values along the given axis before the given indices</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.insert.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.append(...)</code></td>
         <td>Append values to the end of an array</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.append.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.resize(...)</code></td>
         <td>Return a new array with the specified shape</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.resize.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.unique(...)</code></td>
         <td>Find the unique elements of an array</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.unique.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.pad(...)</code></td>
         <td>Pad an array</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.pad.html">link</a></td>
      </tr>
   </tbody>
</table>

### numpy.append

In [182]:
arr_1d_8 = np.array([0, 0, 0])

# append
append_1 = np.append(arr_1d_8, 1)
append_2 = np.append(arr_1d_8, [3, 2])
append_3 = np.append(arr_1d_8, [1, 1, 1])

# log
print(f"append_1 : {append_1}")
print(f"append_2 : {append_2}")
print(f"append_3 : {append_3}")

append_1 : [0 0 0 1]
append_2 : [0 0 0 3 2]
append_3 : [0 0 0 1 1 1]


In [183]:
arr_2d_16 = np.array([[0, 0], [1, 1]])

# append
append_4 = np.append(arr_2d_16, 2)
append_5 = np.append(arr_2d_16, [2, 2])
append_6 = np.append(arr_2d_16, [[2, 2]], axis=0)
append_7 = np.append(arr_2d_16, values=[[2], [3]], axis=1)

# log
print(f"append_4 :\n{append_4}", end=f"\n{'-' * 50}\n")
print(f"append_5 :\n{append_5}", end=f"\n{'-' * 50}\n")
print(f"append_6 :\n{append_6}", end=f"\n{'-' * 50}\n")
print(f"append_7 :\n{append_7}")

append_4 :
[0 0 1 1 2]
--------------------------------------------------
append_5 :
[0 0 1 1 2 2]
--------------------------------------------------
append_6 :
[[0 0]
 [1 1]
 [2 2]]
--------------------------------------------------
append_7 :
[[0 0 2]
 [1 1 3]]


### numpy.insert

In [184]:
arr_1d_9 = np.array([0, 0, 0])

# insert
insert_1 = np.insert(arr_1d_9, 0, 5)
insert_2 = np.insert(arr_1d_9, 1, [1, 1])
insert_3 = np.insert(arr_1d_9, 3, [1, 1])

# log
print(f"insert_1: {insert_1}")
print(f"insert_2: {insert_2}")
print(f"insert_3: {insert_3}")

insert_1: [5 0 0 0]
insert_2: [0 1 1 0 0]
insert_3: [0 0 0 1 1]


In [185]:
arr_2d_17 = np.array([[0, 0], [1, 1]])

# insert
insert_4 = np.insert(arr_2d_17, 0, 2)
insert_5 = np.insert(arr_2d_17, 0, [2, 2])
insert_6 = np.insert(arr_2d_17, obj=4, values=[2, 2])
insert_7 = np.insert(arr_2d_17, obj=0, values=[[2, 2]], axis=0)
insert_8 = np.insert(arr_2d_17, obj=2, values=[[2, 2]], axis=0)
insert_9 = np.insert(arr_2d_17, obj=0, values=[[2, 3]], axis=1)
insert_10 = np.insert(arr_2d_17, obj=2, values=[[2, 3]], axis=1)

# log
print(f"insert_4 :\n{insert_4}", end=f"\n{'-' * 50}\n")
print(f"insert_5 :\n{insert_5}", end=f"\n{'-' * 50}\n")
print(f"insert_6 :\n{insert_6}", end=f"\n{'-' * 50}\n")
print(f"insert_7 :\n{insert_7}", end=f"\n{'-' * 50}\n")
print(f"insert_8 :\n{insert_8}", end=f"\n{'-' * 50}\n")
print(f"insert_9 :\n{insert_9}", end=f"\n{'-' * 50}\n")
print(f"insert_10 :\n{insert_10}")

insert_4 :
[2 0 0 1 1]
--------------------------------------------------
insert_5 :
[2 2 0 0 1 1]
--------------------------------------------------
insert_6 :
[0 0 1 1 2 2]
--------------------------------------------------
insert_7 :
[[2 2]
 [0 0]
 [1 1]]
--------------------------------------------------
insert_8 :
[[0 0]
 [1 1]
 [2 2]]
--------------------------------------------------
insert_9 :
[[2 0 0]
 [3 1 1]]
--------------------------------------------------
insert_10 :
[[0 0 2]
 [1 1 3]]


### numpy.delete

📝 Docs:
   - [numpy.org/doc/stable/reference/generated/numpy.delete.html](https://numpy.org/doc/stable/reference/generated/numpy.delete.html)
   - [numpy.org/doc/stable/reference/generated/numpy.argwhere.html](https://numpy.org/doc/stable/reference/generated/numpy.argwhere.html)

#### Delete by index

In [186]:
arr_1d_10 = np.array([1, 2, 3])

# delete
delete_1 = np.delete(arr_1d_10, 0)
delete_2 = np.delete(arr_1d_10, obj=2)

# log
print(f"delete_1: {delete_1}")
print(f"delete_2: {delete_2}")

delete_1: [2 3]
delete_2: [1 2]


In [187]:
arr_2d_18 = np.array([[1, 2, 3], [4, 5, 6]])

# delete
delete_3 = np.delete(arr_2d_18, 0)
delete_4 = np.delete(arr_2d_18, obj=1)
delete_5 = np.delete(arr_2d_18, obj=0, axis=0)
delete_6 = np.delete(arr_2d_18, obj=1, axis=0)
delete_7 = np.delete(arr_2d_18, obj=0, axis=1)
delete_8 = np.delete(arr_2d_18, obj=2, axis=1)

# log
print(f"delete_3:\n{delete_3}", end=f"\n{'-' * 50}\n")
print(f"delete_4:\n{delete_4}", end=f"\n{'-' * 50}\n")
print(f"delete_5:\n{delete_5}", end=f"\n{'-' * 50}\n")
print(f"delete_6:\n{delete_6}", end=f"\n{'-' * 50}\n")
print(f"delete_7:\n{delete_7}", end=f"\n{'-' * 50}\n")
print(f"delete_8:\n{delete_8}")

delete_3:
[2 3 4 5 6]
--------------------------------------------------
delete_4:
[1 3 4 5 6]
--------------------------------------------------
delete_5:
[[4 5 6]]
--------------------------------------------------
delete_6:
[[1 2 3]]
--------------------------------------------------
delete_7:
[[2 3]
 [5 6]]
--------------------------------------------------
delete_8:
[[1 2]
 [4 5]]


#### Delete by value using numpy.argwhere

In [188]:
arr_1d_11 = np.array([1, 2, 3])

In [189]:
# find index
idx_1 = np.argwhere(arr_1d_11 == 2)

# delete
delete_9 = np.delete(arr_1d_11, idx_1)

# log
print(f"delete_9: {delete_9}")

delete_9: [1 3]


In [190]:
# find index
idx_2 = np.argwhere(arr_1d_11 == 3)

# delete
delete_10 = np.delete(arr_1d_11, idx_2)

# log
print(f"delete_10: {delete_10}")

delete_10: [1 2]


### numpy.resize

In [191]:
arr_1d_12 = np.array([8, 9, 0, 3, 1, 6, 4, 2])

# resize
resize_1 = np.resize(arr_1d_12, (2, 3))
resize_2 = np.resize(arr_1d_12, (2, 2, 2))
resize_3 = np.resize(arr_1d_12, (4, 3))

# log
print(f"resize_1 :\n{resize_1}")
print(f"resize_1.ndim: {resize_1.ndim}")
print(f"resize_1.shape: {resize_1.shape}", end=f"\n{'-' * 50}\n")
print(f"resize_2 :\n{resize_2}")
print(f"resize_2.ndim: {resize_2.ndim}")
print(f"resize_2.shape: {resize_2.shape}", end=f"\n{'-' * 50}\n")
print(f"resize_3 :\n{resize_3}")
print(f"resize_3.ndim: {resize_3.ndim}")
print(f"resize_3.shape: {resize_3.shape}")

resize_1 :
[[8 9 0]
 [3 1 6]]
resize_1.ndim: 2
resize_1.shape: (2, 3)
--------------------------------------------------
resize_2 :
[[[8 9]
  [0 3]]

 [[1 6]
  [4 2]]]
resize_2.ndim: 3
resize_2.shape: (2, 2, 2)
--------------------------------------------------
resize_3 :
[[8 9 0]
 [3 1 6]
 [4 2 8]
 [9 0 3]]
resize_3.ndim: 2
resize_3.shape: (4, 3)


### numpy.unique

In [192]:
arr_1d_13 = np.array([1, 2, 2, 3, 4, 4, 4, 5])

# unique
unique_elements = np.unique(arr_1d_13)
unique_elements_with_indices = np.unique(arr_1d_13, return_index=True)
unique_elements_with_counts = np.unique(arr_1d_13, return_counts=True)

# log
print(f"unique_elements              : {unique_elements}")
print(f"unique_elements_with_indices : {unique_elements_with_indices}")
print(f"unique_elements_with_counts  : {unique_elements_with_counts}")

unique_elements              : [1 2 3 4 5]
unique_elements_with_indices : (array([1, 2, 3, 4, 5]), array([0, 1, 3, 4, 7]))
unique_elements_with_counts  : (array([1, 2, 3, 4, 5]), array([1, 2, 1, 3, 1]))


### numpy.pad

In [193]:
# Example array
arr_2d_19 = np.array([[1, 2], [3, 4]])

# pad with constant value
padded_constant = np.pad(arr_2d_19, pad_width=1, mode="constant", constant_values=0)

# pad with edge values
padded_edge = np.pad(arr_2d_19, pad_width=1, mode="edge")

# pad with linear ramp
padded_linear_ramp = np.pad(arr_2d_19, pad_width=1, mode="linear_ramp", end_values=10)

# log
print(f"padded_constant:\n{padded_constant}", end=f"\n{'-' * 50}\n")
print(f"padded_edge:\n{padded_edge}", end=f"\n{'-' * 50}\n")
print(f"padded_linear_ramp:\n{padded_linear_ramp}")

padded_constant:
[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]
--------------------------------------------------
padded_edge:
[[1 1 2 2]
 [1 1 2 2]
 [3 3 4 4]
 [3 3 4 4]]
--------------------------------------------------
padded_linear_ramp:
[[10 10 10 10]
 [10  1  2 10]
 [10  3  4 10]
 [10 10 10 10]]


## Rearranging elements

<table style="margin: 0 auto;">
   <thead>
      <tr>
         <th style="text-align: center;">Command</th>
         <th style="text-align: center;">Description</th>
         <th style="text-align: center;">Details</th>
      </tr>
   </thead>
   <tbody>
      <tr>
         <td><code>np.flip(...)</code></td>
         <td>Reverse the order of elements in an array along the given axis</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.flip.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.reshape(...)</code></td>
         <td>Gives a new shape to an array without changing its data</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.reshape.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.roll(...)</code></td>
         <td>Roll array elements along a given axis</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.roll.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.rot90(...)</code></td>
         <td>Rotate an array by 90 degrees in the plane specified by axes</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.rot90.html">link</a></td>
      </tr>
   </tbody>
</table>

### numpy.flip

In [194]:
arr_2d_20 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# flip
flip_1 = np.flip(arr_2d_20, axis=0)
flip_2 = np.flip(arr_2d_20, axis=1)

# log
print(f"flip_1:\n{flip_1}", end=f"\n{'-' * 50}\n")
print(f"flip_2:\n{flip_2}")

flip_1:
[[7 8 9]
 [4 5 6]
 [1 2 3]]
--------------------------------------------------
flip_2:
[[3 2 1]
 [6 5 4]
 [9 8 7]]


### numpy.roll

In [195]:
arr_2d_20 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# roll
roll_1 = np.roll(arr_2d_20, shift=2, axis=0)
roll_2 = np.roll(arr_2d_20, shift=-1, axis=1)

# log
print(f"roll_1:\n{roll_1}", end=f"\n{'-' * 50}\n")
print(f"roll_2:\n{roll_2}")

roll_1:
[[4 5 6]
 [7 8 9]
 [1 2 3]]
--------------------------------------------------
roll_2:
[[2 3 1]
 [5 6 4]
 [8 9 7]]


### numpy.rot90

In [196]:
arr_2d_20 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# rotate 90
rot90_1 = np.rot90(arr_2d_20)
rot90_2 = np.rot90(arr_2d_20, k=-1)

# log
print(f"rot90_1:\n{rot90_1}", end=f"\n{'-' * 50}\n")
print(f"rot90_2:\n{rot90_2}")

rot90_1:
[[3 6 9]
 [2 5 8]
 [1 4 7]]
--------------------------------------------------
rot90_2:
[[7 4 1]
 [8 5 2]
 [9 6 3]]
