📝 **Author:** Amirhossein Heydari - 📧 **Email:** AmirhosseinHeydari78@gmail.com - 📍 **Linktree:** [linktr.ee/mr_pylin](https://linktr.ee/mr_pylin)

---

# Dependencies

In [1]:
import numpy as np

# NumPy - NdArray Properties
Docs:
   - [numpy.org/doc/stable/reference/generated/numpy.ndarray.html](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)

In [2]:
arr_1d_1 = np.array([1, 2, 3, 4, 5, 6, 7])

# ndarray properties
shape_1 = arr_1d_1.shape
dtype_1 = arr_1d_1.dtype
size_1 = arr_1d_1.size
ndim_1 = arr_1d_1.ndim
T_1 = arr_1d_1.T
nbytes_1 = arr_1d_1.nbytes
real_1 = arr_1d_1.real
imag_1 = arr_1d_1.imag

# log
print(f"arr_1d_1.shape  : {shape_1}")
print(f"arr_1d_1.dtype  : {dtype_1}")
print(f"arr_1d_1.size   : {size_1}")
print(f"arr_1d_1.ndim   : {ndim_1}")
print(f"arr_1d_1.T      : {T_1}")
print(f"arr_1d_1.nbytes : {nbytes_1}")
print(f"arr_1d_1.real   : {real_1}")
print(f"arr_1d_1.imag   : {imag_1}")

arr_1d_1.shape  : (7,)
arr_1d_1.dtype  : int64
arr_1d_1.size   : 7
arr_1d_1.ndim   : 1
arr_1d_1.T      : [1 2 3 4 5 6 7]
arr_1d_1.nbytes : 56
arr_1d_1.real   : [1 2 3 4 5 6 7]
arr_1d_1.imag   : [0 0 0 0 0 0 0]


In [3]:
arr_2d_1 = np.array([[1, 4, 3, 2], [3, 1, 4, 2]])

# ndarray properties
shape_2 = arr_2d_1.shape
dtype_2 = arr_2d_1.dtype
size_2 = arr_2d_1.size
ndim_2 = arr_2d_1.ndim
T_2 = arr_2d_1.T
nbytes_2 = arr_2d_1.nbytes
real_2 = arr_2d_1.real
imag_2 = arr_2d_1.imag

# log
print(f"arr_2d_1.shape : {shape_2}")
print(f"arr_2d_1.dtype : {dtype_2}")
print(f"arr_2d_1.size  : {size_2}")
print(f"arr_2d_1.ndim  : {ndim_2}")
print(f"arr_2d_1.T      : {T_2}")
print(f"arr_2d_1.nbytes : {nbytes_2}")
print(f"arr_2d_1.real   : {real_2}")
print(f"arr_2d_1.imag   : {imag_2}")

arr_2d_1.shape : (2, 4)
arr_2d_1.dtype : int64
arr_2d_1.size  : 8
arr_2d_1.ndim  : 2
arr_2d_1.T      : [[1 3]
 [4 1]
 [3 4]
 [2 2]]
arr_2d_1.nbytes : 64
arr_2d_1.real   : [[1 4 3 2]
 [3 1 4 2]]
arr_2d_1.imag   : [[0 0 0 0]
 [0 0 0 0]]


# NumPy - NdArray Methods
Docs:
   - https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html

## min
   - Return the minimum along a given axis.
   - ```python
      numpy.ndarray.min(axis, ...)
      ```

In [4]:
arr_2d_2 = np.array([[5, 7, 1, 6], [9, 2, 4, 3]])

# min
min_1 = arr_2d_2.min()
min_2 = arr_2d_2.min(0)
min_3 = arr_2d_2.min(1)

# log
print(f"min_1: {min_1}")
print(f"min_2: {min_2}")
print(f"min_3: {min_3}")

min_1: 1
min_2: [5 2 1 3]
min_3: [1 2]


## max
   - Return the maximum along a given axis.
   - ```python
     numpy.ndarray.max(axis, ...)
     ```

In [5]:
arr_2d_3 = np.array([[5, 7, 1, 6], [9, 2, 4, 3]])

# max
max_1 = arr_2d_3.max(axis=None)
max_2 = arr_2d_3.max(axis=0)
max_3 = arr_2d_3.max(axis=1)

# log
print(f"max_1: {max_1}")
print(f"max_2: {max_2}")
print(f"max_3: {max_3}")

max_1: 9
max_2: [9 7 4 6]
max_3: [7 9]


## argmin
   - Return indices of the min values along a given axis.
   - ```python
     numpy.ndarray.argmin(axis, ...)
     ```

In [6]:
arr_2d_4 = np.array([[5, 7, 1, 6], [9, 2, 4, 3]])

# argmin
argmin_1 = arr_2d_4.argmin()
argmin_2 = arr_2d_4.argmin(0)
argmin_3 = arr_2d_4.argmin(1)

# log
print(f"argmin_1: {argmin_1}")
print(f"argmin_2: {argmin_2}")
print(f"argmin_3: {argmin_3}")

argmin_1: 2
argmin_2: [0 1 0 1]
argmin_3: [2 1]


## argmax
   - Return indices of the max values along a given axis.
   - ```python
     numpy.ndarray.argmax(axis, ...)
     ```

In [7]:
arr_2d_5 = np.array([[5, 7, 1, 6], [9, 2, 4, 3]])

# argmax
argmax_1 = arr_2d_5.argmax(axis=None)
argmax_2 = arr_2d_5.argmax(axis=0)
argmax_3 = arr_2d_5.argmax(axis=1)

# log
print(f"argmax_1: {argmax_1}")
print(f"argmax_2: {argmax_2}")
print(f"argmax_3: {argmax_3}")

argmax_1: 4
argmax_2: [1 0 1 0]
argmax_3: [1 0]


## sum
   - Return the sum along a given axis.
   - ```python
     numpy.ndarray.sum(axis, ...)
     ```

In [8]:
arr_2d_6 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# sum
sum_1 = arr_2d_6.sum()
sum_2 = arr_2d_6.sum(0)
sum_3 = arr_2d_6.sum(1)

# log
print(f"sum_1: {sum_1}")
print(f"sum_2: {sum_2}")
print(f"sum_3: {sum_3}")

sum_1: 36
sum_2: [ 6  8 10 12]
sum_3: [10 26]


## mean
   - Return the average along a given axis.
   - ```python
     numpy.ndarray.mean(axis, ...)
     ```

In [9]:
arr_2d_7 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# mean
mean_1 = arr_2d_7.mean()
mean_2 = arr_2d_7.mean(0)
mean_3 = arr_2d_7.mean(1)

# log
print(f"mean_1: {mean_1}")
print(f"mean_2: {mean_2}")
print(f"mean_3: {mean_3}")

mean_1: 4.5
mean_2: [3. 4. 5. 6.]
mean_3: [2.5 6.5]


## var
   - Return the variance along a given axis.
   - ```python
     numpy.ndarray.var(axis, ...)
     ```

In [10]:
arr_2d_8 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# variance
var_1 = arr_2d_8.var()
var_2 = arr_2d_8.var(0)
var_3 = arr_2d_8.var(1)

# log
print(f"var_1: {var_1}")
print(f"var_2: {var_2}")
print(f"var_3: {var_3}")

var_1: 5.25
var_2: [4. 4. 4. 4.]
var_3: [1.25 1.25]


## std
   - Return the standard deviation along a given axis.
   - ```python
     numpy.ndarray.std(axis, ...)
     ```

In [11]:
arr_2d_9 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# standard deviation
std_1 = arr_2d_9.std(axis=None)
std_2 = arr_2d_9.std(axis=0)
std_3 = arr_2d_9.std(axis=1)

# log
print(f"std_1: {std_1}")
print(f"std_2: {std_2}")
print(f"std_3: {std_3}")

std_1: 2.29128784747792
std_2: [2. 2. 2. 2.]
std_3: [1.11803399 1.11803399]


## reshape
   - Returns an array in a new shape.
   - ```python
     numpy.ndarray.reshape(shape, ...)
     ```

In [12]:
arr_2d_10 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# reshape
reshape_1 = arr_2d_10.reshape((8,))
reshape_2 = arr_2d_10.reshape((2, 2, 2))
reshape_3 = arr_2d_10.reshape((2, 1, 4))
# reshape_4 = arr.reshape((2, 3))

# log
print(f"reshape_1 :\n{reshape_1}", end='\n\n')
print(f"reshape_2 :\n{reshape_2}", end='\n\n')
print(f"reshape_3 :\n{reshape_3}")

reshape_1 :
[1 2 3 4 5 6 7 8]

reshape_2 :
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

reshape_3 :
[[[1 2 3 4]]

 [[5 6 7 8]]]


## resize
   - Resizes the original array into a new shape.
   - ```python
     numpy.ndarray.resize(shape, ...)
     ```

In [13]:
arr_2d_11 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

arr_2d_11.resize((8,))
print(f"arr_2d_11 :\n{arr_2d_11}", end='\n\n')

arr_2d_11.resize((2, 2, 2))
print(f"arr_2d_11 :\n{arr_2d_11}", end='\n\n')

arr_2d_11.resize((2, 3))
print(f"arr_2d_11 :\n{arr_2d_11}", end='\n\n')

arr_2d_11.resize((2, 2))
print(f"arr_2d_11 :\n{arr_2d_11}")

arr_2d_11 :
[1 2 3 4 5 6 7 8]

arr_2d_11 :
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

arr_2d_11 :
[[1 2 3]
 [4 5 6]]

arr_2d_11 :
[[1 2]
 [3 4]]


## copy
   - Return a copy of the array.
   - ```python
     numpy.ndarray.copy(...)
     ```

In [14]:
arr_1d_2 = np.array([1, 2, 3, 4])

# copy
copy_1 = arr_1d_2
copy_2 = arr_1d_2.copy()

# index assignment
arr_1d_2[0] = 9

# log
print(f"arr_1d_2: {arr_1d_2}")
print(f"copy_1  : {copy_1}")
print(f"copy_2  : {copy_2}")

arr_1d_2: [9 2 3 4]
copy_1  : [9 2 3 4]
copy_2  : [1 2 3 4]


In [15]:
arr_2d_12 = np.array([[1, 2], [3, 4]])

# copy
copy_3 = arr_2d_12
copy_4 = arr_2d_12.copy()

# index assignment
arr_2d_12[0] = [3, 3]
arr_2d_12[1, 0] = 4

# log
print(f"arr_2d_12 :\n{arr_2d_12}", end='\n\n')
print(f"copy_3 :\n{copy_3}", end='\n\n')
print(f"copy_4 :\n{copy_4}", end='\n\n')

arr_2d_12 :
[[3 3]
 [4 4]]

copy_3 :
[[3 3]
 [4 4]]

copy_4 :
[[1 2]
 [3 4]]



## copy
   - Return a copy of the array and cast it to a specified type.
   - ```python
     numpy.ndarray.astype(axis, ...)
     ```

In [16]:
arr_1d_3 = np.array([9, 4, 7, 0])

# astype
astype_1 = arr_1d_3.astype(float)
astype_2 = arr_1d_3.astype(bool)
astype_3 = arr_1d_3.astype(str)

# log
print(f"astype_1: {astype_1}")
print(f"astype_2: {astype_2}")
print(f"astype_3: {astype_3}")

astype_1: [9. 4. 7. 0.]
astype_2: [ True  True  True False]
astype_3: ['9' '4' '7' '0']


In [17]:
arr_2d_13 = np.array([[4, 2, 5], [7, 2, 1]])

# astype
astype_3 = arr_2d_13.astype(float)
astype_4 = arr_2d_13.astype(bool)
astype_5 = arr_2d_13.astype(str)

# log
print(f"astype_3 :\n{astype_3}", end='\n\n')
print(f"astype_4 :\n{astype_4}", end='\n\n')
print(f"astype_5 :\n{astype_5}")

astype_3 :
[[4. 2. 5.]
 [7. 2. 1.]]

astype_4 :
[[ True  True  True]
 [ True  True  True]]

astype_5 :
[['4' '2' '5']
 ['7' '2' '1']]


## sort
   - Sort the original array.
   - ```python
     numpy.ndarray.sort(axis, ...)
     ```

In [18]:
arr_1d_4 = np.array([5, 2, 4, 1, 3])

# sort
arr_1d_4.sort()

# log
print(f"arr_1d_4: {arr_1d_4}")

arr_1d_4: [1 2 3 4 5]


In [19]:
arr_1d_5 = np.array([1.1, 1.01, 1.2, 1.02, 1.5])

# sort
arr_1d_5.sort()

# log
print(f"arr_1d_5: {arr_1d_5}")

arr_1d_5: [1.01 1.02 1.1  1.2  1.5 ]


In [20]:
arr_2d_14 = np.array([[3, 6, 2], [4, 1, 5]])

# sort
arr_2d_14.sort(0)

# log
print(f"arr_2d_14 :\n{arr_2d_14}")

arr_2d_14 :
[[3 1 2]
 [4 6 5]]


In [21]:
arr_2d_15 = np.array([[3, 2, 1], [6, 5, 4]])

# sort
arr_2d_15.sort(1)

# log
print(f"arr_2d_15 :\n{arr_2d_15}")

arr_2d_15 :
[[1 2 3]
 [4 5 6]]


## argsort
   - Return the indices that would sort this array.
   - ```python
     numpy.ndarray.argsort(axis, ...)
     ```

In [22]:
arr_1d_6 = np.array([9, 4, 7, 0, 6])

# argsort
argsort_1 = arr_1d_6.argsort()

# log
print(f"argsort_1          : {argsort_1}")
print(f"arr_1d_6[argsort_1]: {arr_1d_6[argsort_1]}")

argsort_1          : [3 1 4 2 0]
arr_1d_6[argsort_1]: [0 4 6 7 9]


In [23]:
arr_1d_7 = np.array([1.1, 1.01, 1.2, 1.02, 1.5])

# argsort
argsort_2 = arr_1d_7.argsort()

# log
print(f"argsort_2          : {argsort_2}")
print(f"arr_1d_7[argsort_2]: {arr_1d_7[argsort_2]}")

argsort_2          : [1 3 0 2 4]
arr_1d_7[argsort_2]: [1.01 1.02 1.1  1.2  1.5 ]


In [24]:
arr_2d_16 = np.array([[3, 6, 2], [4, 1, 5]])

# argsort for more than 1D arrays
sort_1 = np.take_along_axis(arr_2d_16, arr_2d_16.argsort(), axis=-1)

# log
print(f"sort_1 :\n{sort_1}")

sort_1 :
[[2 3 6]
 [1 4 5]]


In [25]:
arr_2d_17 = np.array([[3, 2, 1], [6, 5, 4]])

# argsort for more than 1D arrays
sort_2 = np.take_along_axis(arr_2d_17, arr_2d_17.argsort(), axis=-1)

# log
print(f"sort_2 :\n{sort_2}")

sort_2 :
[[1 2 3]
 [4 5 6]]


## prod
   - Return the cumulative product along a given axis.
   - ```python
     numpy.ndarray.prod(axis, ...)
     ```

In [26]:
arr_2d_18 = np.array([[1, 2], [3, 4]])

# prod
prod_1 = arr_2d_18.prod()
prod_2 = arr_2d_18.prod(0)
prod_3 = arr_2d_18.prod(1)

# log
print(f"prod_1 : {prod_1}")
print(f"prod_2 : {prod_2}")
print(f"prod_3 : {prod_3}")

prod_1 : 24
prod_2 : [3 8]
prod_3 : [ 2 12]


## dot
   - Return the dot product of two arrays.
   - ```python
     numpy.ndarray.dot(axis, ...)
     ```

In [27]:
arr_1d_8 = np.array([1, 2, 3, 4])
arr_2d_19 = np.array([[1, 2], [3, 4]])
arr_2d_20 = np.array([[1, 2, 3], [4, 5, 6]])

# dot
dot_1 = arr_1d_8.dot(arr_1d_8)
dot_2 = arr_2d_19.dot(arr_2d_19)
dot_3 = arr_2d_19.dot(arr_2d_20)
dot_4 = arr_2d_20.T.dot(arr_2d_19)
dot_5 = arr_2d_20.dot(arr_2d_20.T)

# log
print(f"dot_1 :\n{dot_1}", end='\n\n')
print(f"dot_2 :\n{dot_2}", end='\n\n')
print(f"dot_3 :\n{dot_3}", end='\n\n')
print(f"dot_3 :\n{dot_4}", end='\n\n')
print(f"dot_4 :\n{dot_5}")

dot_1 :
30

dot_2 :
[[ 7 10]
 [15 22]]

dot_3 :
[[ 9 12 15]
 [19 26 33]]

dot_3 :
[[13 18]
 [17 24]
 [21 30]]

dot_4 :
[[14 32]
 [32 77]]


## round
   - Return a rounded array with some decimals.
   - ```python
     numpy.ndarray.round(decimals, ...)
     ```

In [28]:
arr_2d_21 = np.array([[1.124, 2.53], [3.001, 4.2]])

# round
round_1 = arr_2d_21.round()
round_2 = arr_2d_21.round(1)
round_3 = arr_2d_21.round(2)

# log
print(f"round_1 :\n{round_1}", end='\n\n')
print(f"round_2 :\n{round_2}", end='\n\n')
print(f"round_3 :\n{round_3}")

round_1 :
[[1. 3.]
 [3. 4.]]

round_2 :
[[1.1 2.5]
 [3.  4.2]]

round_3 :
[[1.12 2.53]
 [3.   4.2 ]]


## flatten
   - Return a copy of the array which is flattened.
   - ```python
     numpy.ndarray.flatten(axis, ...)
     ```

In [29]:
arr_2d_22 = np.array([[1, 0, 3], [0, 4, 0]])

# flatten
flatten = arr_2d_22.flatten()

# index assignment
flatten[0] = 5

# log
print(f"flatten: {flatten}")

flatten: [5 0 3 0 4 0]


## ravel
   - Return a flattened view of the array.
   - ```python
     numpy.ndarray.ravel(axis, ...)
     ```

In [30]:
arr_2d_23 = np.array([[1, 0, 3], [0, 4, 0]])

# ravel
ravel = arr_2d_23.ravel()

# index assignment
ravel[1] = 5

# log
print(f"ravel: {ravel}")

ravel: [1 5 3 0 4 0]


## nonzero
   - Return the indices of the elements that are non-zero.
   - ```python
     numpy.ndarray.nonzero(axis, ...)
     ```

In [31]:
arr_1d_9 = np.array([1, 5, 2, 0, 8, 0, 0])

# nonzero
nonzero_1 = arr_1d_9.nonzero()
nonzero_2 = arr_1d_9.nonzero()

# log
print(f"nonzero_1            : {nonzero_1}")
print(f"arr_1d_9[nonzero_1] : {arr_1d_9[nonzero_1]}", end='\n\n')
print(f"nonzero_2            : {nonzero_2}")
print(f"arr_1d_9[nonzero_2] : {arr_1d_9[nonzero_2]}")

nonzero_1            : (array([0, 1, 2, 4]),)
arr_1d_9[nonzero_1] : [1 5 2 8]

nonzero_2            : (array([0, 1, 2, 4]),)
arr_1d_9[nonzero_2] : [1 5 2 8]


## fill
   - Fill the array with a scalar value.
   - ```python
     numpy.ndarray.fill(axis, ...)
     ```

In [32]:
arr_2d_24 = np.array([[1, 0, 2], [3, 0, 4]])

arr_2d_24.fill(1)
print(f"arr_2d_24 :\n{arr_2d_24}", end='\n\n')

arr_2d_24.fill(0)
print(f"arr_2d_24 :\n{arr_2d_24}")

arr_2d_24 :
[[1 1 1]
 [1 1 1]]

arr_2d_24 :
[[0 0 0]
 [0 0 0]]


## tolist
   - Return the array as a deep nested python list.
   - ```python
     numpy.ndarray.tolist()
     ```

In [33]:
arr_2d_25 = np.array([[13, 64, 12], [65, 23, 1]])

# list
tolist = arr_2d_25.tolist()

# log
print(f"tolist: {tolist}")

tolist: [[13, 64, 12], [65, 23, 1]]


## put
   - Replaces specified elements with given values.
   - ```python
     numpy.ndarray.put(axes)
     ```

In [34]:
arr_2d_26 = np.array([[13, 64, 12], [65, 23, 1]])

# put
arr_2d_26.put([0, 4], [-10, -5])

# log
print(f"arr_2d_26 :\n{arr_2d_26}")

arr_2d_26 :
[[-10  64  12]
 [ 65  -5   1]]


## clip
   - Return a clipped array in the range of [min, max].
   - ```python
     numpy.ndarray.clip(min, max, ...)
     ```

In [35]:
arr_2d_27 = np.array([[13, 64, 12], [65, 23, 1]])

# clip
clip_1 = arr_2d_27.clip(10)
clip_2 = arr_2d_27.clip(10, 30)

# log
print(f"clip_1 :\n{clip_1}", end='\n\n')
print(f"clip_2 :\n{clip_2}")

clip_1 :
[[13 64 12]
 [65 23 10]]

clip_2 :
[[13 30 12]
 [30 23 10]]


## transpose
   - Return a view of the array with axes transposed.
   - ```python
     numpy.ndarray.transpose(axes)
     ```

In [36]:
arr_2d_28 = np.array([[13, 64, 12], [65, 23, 1]])

# transpose
transpose_1 = arr_2d_28.transpose([1, 0])
transpose_2 = arr_2d_28.transpose()
transpose_3 = arr_2d_28.T
transpose_4 = arr_2d_28.transpose([0, 1])

# log
print(f"transpose_1 :\n{transpose_1}", end='\n\n')
print(f"transpose_1 :\n{transpose_1}", end='\n\n')
print(f"transpose_1 :\n{transpose_1}", end='\n\n')
print(f"transpose_1 :\n{transpose_1}")

transpose_1 :
[[13 65]
 [64 23]
 [12  1]]

transpose_1 :
[[13 65]
 [64 23]
 [12  1]]

transpose_1 :
[[13 65]
 [64 23]
 [12  1]]

transpose_1 :
[[13 65]
 [64 23]
 [12  1]]


## all
   - Return True if all elements evaluate to True.
   - ```python
     numpy.ndarray.all(axis, ...)
     ```

In [37]:
arr_1d_10 = np.array([1, 0, 1, 1])
arr_2d_29 = np.array([[0, 1, 1], [0, 1, 1]])
arr_2d_30 = np.array([[0, 0, 1], [1, 0, 1]])

# all
all_1 = arr_1d_10.all()
all_2 = arr_2d_29.all()
all_3 = arr_2d_29.all(0)
all_4 = arr_2d_29.all(1)
all_5 = arr_2d_30.all()
all_6 = arr_2d_30.all(0)
all_7 = arr_2d_30.all(1)

# log
print(f"all_1: {all_1}")
print(f"all_2: {all_2}")
print(f"all_3: {all_3}")
print(f"all_4: {all_4}")
print(f"all_5: {all_5}")
print(f"all_6: {all_6}")
print(f"all_7: {all_7}")

all_1: False
all_2: False
all_3: [False  True  True]
all_4: [False False]
all_5: False
all_6: [False False  True]
all_7: [False False]


## any
   - Return True if any of the elements evaluate to True.
   - ```python
     numpy.ndarray.any(axis, ...)
     ```

In [38]:
arr_1d_11 = np.array([1, 0, 1, 1])
arr_2d_31 = np.array([[0, 1, 1], [0, 1, 1]])
arr_2d_32 = np.array([[0, 0, 1], [1, 0, 1]])

# any
any_1 = arr_1d_11.any()
any_2 = arr_2d_31.any()
any_3 = arr_2d_31.any(0)
any_4 = arr_2d_31.any(1)
any_5 = arr_2d_32.any()
any_6 = arr_2d_32.any(0)
any_7 = arr_2d_32.any(1)

# log
print(f"any_1: {any_1}")
print(f"any_2: {any_2}")
print(f"any_3: {any_3}")
print(f"any_4: {any_4}")
print(f"any_5: {any_5}")
print(f"any_6: {any_6}")
print(f"any_7: {any_7}")

any_1: True
any_2: True
any_3: [False  True  True]
any_4: [ True  True]
any_5: True
any_6: [ True False  True]
any_7: [ True  True]
