# Dependencies

In [1]:
import numpy as np

In [2]:
# prevent printing the returned object in each cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'none'

# NumPy - Array Creation
Docs:
   - [numpy.org/doc/stable/reference/routines.array-creation.html](https://numpy.org/doc/stable/reference/routines.array-creation.html)

## zeros
   - Creates a new array filled with zeros.
   - ```python
     numpy.zeros(shape, dtype, ...)
     ```

In [3]:
zeros_1 = np.zeros(4)
zeros_2 = np.zeros((2, 3))
zeros_3 = np.zeros(shape=(2, 3, 2), dtype=np.int_)

# log
print(f"zeros_1 :\n{zeros_1}", end='\n\n')
print(f"zeros_2 :\n{zeros_2}", end='\n\n')
print(f"zeros_3 :\n{zeros_3}")

zeros_1 :
[0. 0. 0. 0.]

zeros_2 :
[[0. 0. 0.]
 [0. 0. 0.]]

zeros_3 :
[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]


## zeros_like
   - Creates a new array with the same shape and data type as an existing array, filled with zeros.
   - ```python
     numpy.zeros_like(a, dtype, shape, ...)
     ```

In [4]:
zeros_like_1 = np.zeros_like(zeros_1)
zeros_like_2 = np.zeros_like(zeros_2, bool, shape=(2, 2))
zeros_like_3 = np.zeros_like(a=zeros_3, dtype=int)

# log
print(f"zeros_like_1 :\n{zeros_like_1}", end='\n\n')
print(f"zeros_like_2 :\n{zeros_like_2}", end='\n\n')
print(f"zeros_like_3 :\n{zeros_like_3}")

zeros_like_1 :
[0. 0. 0. 0.]

zeros_like_2 :
[[False False]
 [False False]]

zeros_like_3 :
[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]


## ones
   - Creates a new array filled with ones.
   - ```python
     numpy.ones(shape, dtype, ...)
     ```

In [5]:
ones_1 = np.ones(4)
ones_2 = np.ones((2, 3))
ones_3 = np.ones(shape=(2, 3, 2), dtype=np.int_)


# log
print(f"ones_1 :\n{ones_1}", end='\n\n')
print(f"ones_2 :\n{ones_2}", end='\n\n')
print(f"ones_3 :\n{ones_3}")

ones_1 :
[1. 1. 1. 1.]

ones_2 :
[[1. 1. 1.]
 [1. 1. 1.]]

ones_3 :
[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


## ones_like
   - Creates a new array with the same shape and data type as an existing array, filled with ones.
   - ```python
     numpy.ones_like(a, dtype, shape, ...)
     ```

In [6]:
ones_like_1 = np.ones_like(ones_1)
ones_like_2 = np.ones_like(ones_2, bool, shape=3)
ones_like_3 = np.ones_like(a=ones_3, dtype=int)

# log
print(f"ones_like_1 :\n{ones_like_1}", end='\n\n')
print(f"ones_like_2 :\n{ones_like_2}", end='\n\n')
print(f"ones_like_3 :\n{ones_like_3}")

ones_like_1 :
[1. 1. 1. 1.]

ones_like_2 :
[ True  True  True]

ones_like_3 :
[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


## full
   - Creates a new array of a given shape and data type, filled with a specific value.
   - ```python
     numpy.full(shape, fill_value, dtype, ...)
     ```

In [7]:
full_1 = np.full(4, 0)
full_2 = np.full((2, 3), 1)
full_3 = np.full((2, 3, 2), fill_value=2)

# log
print(f"full_1 :\n{full_1}", end='\n\n')
print(f"full_2 :\n{full_2}", end='\n\n')
print(f"full_3 :\n{full_3}")

full_1 :
[0 0 0 0]

full_2 :
[[1 1 1]
 [1 1 1]]

full_3 :
[[[2 2]
  [2 2]
  [2 2]]

 [[2 2]
  [2 2]
  [2 2]]]


## full_like
   - Creates a new array with the same shape and data type as an existing array, filled with a specific value.
   - ```python
     numpy.full_like(a, fill_value, dtype, shape, ...)
     ```

In [8]:
full_like_1 = np.full_like(full_1, 2)
full_like_2 = np.full_like(full_2, 1)
full_like_3 = np.full_like(full_3, 0, dtype=float)

# log
print(f"full_like_1 :\n{full_like_1}", end='\n\n')
print(f"full_like_2 :\n{full_like_2}", end='\n\n')
print(f"full_like_3 :\n{full_like_3}")

full_like_1 :
[2 2 2 2]

full_like_2 :
[[1 1 1]
 [1 1 1]]

full_like_3 :
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


## empty
   - Creates a new uninitialized array with a given shape and data type (fast, but contains garbage values).
   - ```python
     numpy.empty(shape, dtype, ...)
     ```

In [9]:
empty_1 = np.empty(4)
empty_2 = np.empty((2, 3))
empty_3 = np.empty(shape=(2, 3, 2), dtype=np.int_)

# log
print(f"empty_1 :\n{empty_1}", end='\n\n')
print(f"empty_2 :\n{empty_2}", end='\n\n')
print(f"empty_3 :\n{empty_3}")

empty_1 :
[1. 1. 1. 1.]

empty_2 :
[[1. 1. 1.]
 [1. 1. 1.]]

empty_3 :
[[[4128860 6029375]
  [3801155 5570652]
  [6619251 7536754]]

 [[6357084 6881389]
  [6815858 4259932]
  [7340144 6357060]]]


## empty_like
   - Creates a new uninitialized array with the same shape and data type as an existing array (fast, but contains garbage values).
   - ```python
     numpy.zeros_like(prototype, dtype, shape, ...)
     ```

In [10]:
empty_like_1 = np.empty_like(empty_1)
empty_like_2 = np.empty_like(empty_2, float)
empty_like_3 = np.empty_like(prototype=empty_3, shape=(2, 3))

# log
print(f"empty_like_1 :\n{empty_like_1}", end='\n\n')
print(f"empty_like_2 :\n{empty_like_2}", end='\n\n')
print(f"empty_like_3 :\n{empty_like_3}")

empty_like_1 :
[1. 1. 1. 1.]

empty_like_2 :
[[1. 1. 1.]
 [1. 1. 1.]]

empty_like_3 :
[[-1 -1  0]
 [ 0  0  0]]


## arange
   - Creates an array with evenly spaced values within a specified range.
   - ```python
     numpy.arange([start, ]stop, [step, ]...)
     ```

In [11]:
arange_1 = np.arange(3)
arange_2 = np.arange(5)
arange_3 = np.arange(2, 5)
arange_4 = np.arange(0, 7, 2)
arange_5 = np.arange(0, 1, .1)

# log
print(f"arange_1: {arange_1}")
print(f"arange_2: {arange_2}")
print(f"arange_3: {arange_3}")
print(f"arange_4: {arange_4}")
print(f"arange_5: {arange_5}")

arange_1: [0 1 2]
arange_2: [0 1 2 3 4]
arange_3: [2 3 4]
arange_4: [0 2 4 6]
arange_5: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


## linspace
   - Creates an array with evenly spaced values over a specified interval.
   - ```python
     numpy.linspace(start, stop, num, endpoint, dtype, ...)
     ```

In [12]:
linspace_1 = np.linspace(0, 2, 3)
linspace_2 = np.linspace(0, 1, 5)
linspace_3 = np.linspace(0, 2, 3, dtype=int)
linspace_4 = np.linspace((0, 3), (2, 5), 3, axis=0)
linspace_5 = np.linspace((0, 3), (2, 5), 3, axis=1)

# log
print(f"linspace_1 :\n{linspace_1}", end='\n\n')
print(f"linspace_2 :\n{linspace_2}", end='\n\n')
print(f"linspace_3 :\n{linspace_3}", end='\n\n')
print(f"linspace_4 :\n{linspace_4}", end='\n\n')
print(f"linspace_5 :\n{linspace_5}")

linspace_1 :
[0. 1. 2.]

linspace_2 :
[0.   0.25 0.5  0.75 1.  ]

linspace_3 :
[0 1 2]

linspace_4 :
[[0. 3.]
 [1. 4.]
 [2. 5.]]

linspace_5 :
[[0. 1. 2.]
 [3. 4. 5.]]


## array
   - Creates a new array from various data sources (often creates a copy).
   - ```python
     numpy.array(object, dtype, copy, ...)
     ```

In [13]:
arr_1d_1 = np.array([1, 2, 3, 4])
arr_2d_1 = np.array([[1, 2, 3], [4, 5, 6]])
arr_3d_1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# log
print(f"arr_1d_1 :\n{arr_1d_1}", end='\n\n')
print(f"arr_2d_1 :\n{arr_2d_1}", end='\n\n')
print(f"arr_3d_1 :\n{arr_3d_1}")

arr_1d_1 :
[1 2 3 4]

arr_2d_1 :
[[1 2 3]
 [4 5 6]]

arr_3d_1 :
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## asarray
   - Creates a new array from various data sources, trying to avoid copying data if possible.
   - ```python
     numpy.asarray(a, dtype, ...)
     ```

In [14]:
list_1d_1 = [1, 2, 3, 4]
arr_1d_2 = np.array([1, 2, 3, 4])

# asarray: avoids copy if possible
asarr_1d_1 = np.asarray(list_1d_1)
asarr_1d_2 = np.asarray(arr_1d_2)

# index assignment
list_1d_1[0] = 0
arr_1d_2[0] = 0

# log
print(f"asarr_1d_1: {asarr_1d_1}")
print(f"asarr_1d_2: {asarr_1d_2}")

asarr_1d_1: [1 2 3 4]
asarr_1d_2: [0 2 3 4]


## eye
   - Creates a square identity matrix (ones on the diagonal, zeros elsewhere).
   - ```python
     numpy.eye(N, M, k, dtype, ...)
     ```

In [15]:
eye_1 = np.eye(3)
eye_2 = np.eye(3, 4)
eye_3 = np.eye(N=2, M=3)
eye_4 = np.eye(3, 3, 0)
eye_5 = np.eye(3, 3, 1)
eye_6 = np.eye(3, 3, -1)

# log
print(f"eye_1 :\n{eye_1}", end='\n\n')
print(f"eye_2 :\n{eye_2}", end='\n\n')
print(f"eye_3 :\n{eye_3}", end='\n\n')
print(f"eye_4 :\n{eye_4}", end='\n\n')
print(f"eye_5 :\n{eye_5}")

eye_1 :
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

eye_2 :
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]

eye_3 :
[[1. 0. 0.]
 [0. 1. 0.]]

eye_4 :
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

eye_5 :
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


## copy
   - Creates a copy of an existing array.
   - ```python
     numpy.copy(a, ...)
     ```

In [16]:
arr_2d_2 = np.array([[1, 2, 3], [4, 5, 6]])
arr_2d_3 = arr_2d_2

# index assignment
arr_2d_2[1, 0] = -1
arr_2d_3[0] = [3, 2, 1]

# log
print(f"arr_2d_2 :\n{arr_2d_2}", end='\n\n')
print(f"arr_2d_3 :\n{arr_2d_3}", end='\n\n')

arr_2d_2 :
[[ 3  2  1]
 [-1  5  6]]

arr_2d_3 :
[[ 3  2  1]
 [-1  5  6]]



In [17]:
arr_2d_4 = np.array([[1, 2, 3], [4, 5, 6]])
arr_2d_5 = np.copy(arr_2d_4)

# index assignment
arr_2d_4[1, 0] = 0
arr_2d_5[0] = [3, 2, 1]

# log
print(f"arr_2d_4 :\n{arr_2d_4}", end='\n\n')
print(f"arr_2d_5 :\n{arr_2d_5}", end='\n\n')

arr_2d_4 :
[[1 2 3]
 [0 5 6]]

arr_2d_5 :
[[3 2 1]
 [4 5 6]]

