📝 **Author:** Amirhossein Heydari - 📧 **Email:** AmirhosseinHeydari78@gmail.com - 📍 **Linktree:** [linktr.ee/mr_pylin](https://linktr.ee/mr_pylin)

---

# Dependencies

In [1]:
import numpy as np

# NumPy - Array Creation
   - Array creation routines in NumPy provide various methods to create arrays with different properties and initial values.

📝 Doc:
   - Array creation routines: [numpy.org/doc/stable/reference/routines.array-creation.html](https://numpy.org/doc/stable/reference/routines.array-creation.html)

## From Shape or Value

<table style="margin: 0 auto;">
   <thead>
      <tr>
         <th style="text-align: center;">Function</th>
         <th style="text-align: center;">Description</th>
         <th style="text-align: center;">Details</th>
      </tr>
   </thead>
   <tbody>
      <tr>
         <td><code>np.zeros</code></td>
         <td>Return a new array of given shape and type, filled with zeros</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.zeros.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.zeros_like</code></td>
         <td>Return an array of zeros with the same shape and type as a given array</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.zeros_like.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.ones</code></td>
         <td>Return a new array of given shape and type, filled with ones</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.ones.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.ones_like</code></td>
         <td>Return an array of ones with the same shape and type as a given array</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.ones_like.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.full</code></td>
         <td>Return a new array of given shape and type, filled with fill_value</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.full.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.full_like</code></td>
         <td>Return a full array with the same shape and type as a given array</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.full_like.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.empty</code></td>
         <td>Return a new array of given shape and type, without initializing entries</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.empty.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.empty_like</code></td>
         <td>Return a new array with the same shape and type as a given array</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.empty_like.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.eye</code></td>
         <td>Return a 2-D array with ones on the diagonal and zeros elsewhere</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.eye.html">link</a></td>
      </tr>
   </tbody>
</table>

### numpy.zeros

In [2]:
zeros_1 = np.zeros(4)
zeros_2 = np.zeros((2, 3))
zeros_3 = np.zeros(shape=(2, 3, 2), dtype=np.int_)

# log
print(f"zeros_1 :\n{zeros_1}", end=f"\n{'-' * 50}\n")
print(f"zeros_2 :\n{zeros_2}", end=f"\n{'-' * 50}\n")
print(f"zeros_3 :\n{zeros_3}")

zeros_1 :
[0. 0. 0. 0.]
--------------------------------------------------
zeros_2 :
[[0. 0. 0.]
 [0. 0. 0.]]
--------------------------------------------------
zeros_3 :
[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]


### numpy.zeros_like

In [3]:
zeros_like_1 = np.zeros_like(zeros_1)
zeros_like_2 = np.zeros_like(zeros_2, bool, shape=(2, 2))
zeros_like_3 = np.zeros_like(a=zeros_3, dtype=int)

# log
print(f"zeros_like_1 :\n{zeros_like_1}", end=f"\n{'-' * 50}\n")
print(f"zeros_like_2 :\n{zeros_like_2}", end=f"\n{'-' * 50}\n")
print(f"zeros_like_3 :\n{zeros_like_3}")

zeros_like_1 :
[0. 0. 0. 0.]
--------------------------------------------------
zeros_like_2 :
[[False False]
 [False False]]
--------------------------------------------------
zeros_like_3 :
[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]


### numpy.ones

In [4]:
ones_1 = np.ones(4)
ones_2 = np.ones((2, 3))
ones_3 = np.ones(shape=(2, 3, 2), dtype=np.int_)


# log
print(f"ones_1 :\n{ones_1}", end=f"\n{'-' * 50}\n")
print(f"ones_2 :\n{ones_2}", end=f"\n{'-' * 50}\n")
print(f"ones_3 :\n{ones_3}")

ones_1 :
[1. 1. 1. 1.]
--------------------------------------------------
ones_2 :
[[1. 1. 1.]
 [1. 1. 1.]]
--------------------------------------------------
ones_3 :
[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


### numpy.ones_like

In [5]:
ones_like_1 = np.ones_like(ones_1)
ones_like_2 = np.ones_like(ones_2, bool, shape=3)
ones_like_3 = np.ones_like(a=ones_3, dtype=int)

# log
print(f"ones_like_1 :\n{ones_like_1}", end=f"\n{'-' * 50}\n")
print(f"ones_like_2 :\n{ones_like_2}", end=f"\n{'-' * 50}\n")
print(f"ones_like_3 :\n{ones_like_3}")

ones_like_1 :
[1. 1. 1. 1.]
--------------------------------------------------
ones_like_2 :
[ True  True  True]
--------------------------------------------------
ones_like_3 :
[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


### numpy.full

In [6]:
full_1 = np.full(4, 0)
full_2 = np.full((2, 3), 1)
full_3 = np.full((2, 3, 2), fill_value=2)

# log
print(f"full_1 :\n{full_1}", end=f"\n{'-' * 50}\n")
print(f"full_2 :\n{full_2}", end=f"\n{'-' * 50}\n")
print(f"full_3 :\n{full_3}")

full_1 :
[0 0 0 0]
--------------------------------------------------
full_2 :
[[1 1 1]
 [1 1 1]]
--------------------------------------------------
full_3 :
[[[2 2]
  [2 2]
  [2 2]]

 [[2 2]
  [2 2]
  [2 2]]]


### numpy.full_like

In [7]:
full_like_1 = np.full_like(full_1, 2)
full_like_2 = np.full_like(full_2, 1)
full_like_3 = np.full_like(full_3, 0, dtype=float)

# log
print(f"full_like_1 :\n{full_like_1}", end=f"\n{'-' * 50}\n")
print(f"full_like_2 :\n{full_like_2}", end=f"\n{'-' * 50}\n")
print(f"full_like_3 :\n{full_like_3}")

full_like_1 :
[2 2 2 2]
--------------------------------------------------
full_like_2 :
[[1 1 1]
 [1 1 1]]
--------------------------------------------------
full_like_3 :
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


### numpy.empty

In [8]:
empty_1 = np.empty(4)
empty_2 = np.empty((2, 3))
empty_3 = np.empty(shape=(2, 3, 2), dtype=np.int_)

# log
print(f"empty_1 :\n{empty_1}", end=f"\n{'-' * 50}\n")
print(f"empty_2 :\n{empty_2}", end=f"\n{'-' * 50}\n")
print(f"empty_3 :\n{empty_3}")

empty_1 :
[1. 1. 1. 1.]
--------------------------------------------------
empty_2 :
[[1. 1. 1.]
 [1. 1. 1.]]
--------------------------------------------------
empty_3 :
[[[4128860 6029375]
  [3801155 5570652]
  [6619251 7536754]]

 [[6357084 6881389]
  [6815858 4259932]
  [7340144 6357060]]]


### numpy.empty_like

In [9]:
empty_like_1 = np.empty_like(empty_1)
empty_like_2 = np.empty_like(empty_2, float)
empty_like_3 = np.empty_like(prototype=empty_3, shape=(2, 3))

# log
print(f"empty_like_1 :\n{empty_like_1}", end=f"\n{'-' * 50}\n")
print(f"empty_like_2 :\n{empty_like_2}", end=f"\n{'-' * 50}\n")
print(f"empty_like_3 :\n{empty_like_3}")

empty_like_1 :
[1. 1. 1. 1.]
--------------------------------------------------
empty_like_2 :
[[1. 1. 1.]
 [1. 1. 1.]]
--------------------------------------------------
empty_like_3 :
[[ -734228164    81272836 -2125560053]
 [-1758162866  -734228164    81272836]]


### numpy.eye

In [10]:
eye_1 = np.eye(3)
eye_2 = np.eye(3, 4)
eye_3 = np.eye(N=2, M=3)
eye_4 = np.eye(3, 3, 0)
eye_5 = np.eye(3, 3, 1)
eye_6 = np.eye(3, 3, -1)

# log
print(f"eye_1 :\n{eye_1}", end=f"\n{'-' * 50}\n")
print(f"eye_2 :\n{eye_2}", end=f"\n{'-' * 50}\n")
print(f"eye_3 :\n{eye_3}", end=f"\n{'-' * 50}\n")
print(f"eye_4 :\n{eye_4}", end=f"\n{'-' * 50}\n")
print(f"eye_5 :\n{eye_5}")

eye_1 :
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
--------------------------------------------------
eye_2 :
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
--------------------------------------------------
eye_3 :
[[1. 0. 0.]
 [0. 1. 0.]]
--------------------------------------------------
eye_4 :
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
--------------------------------------------------
eye_5 :
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


## From Existing Data

<table style="margin: 0 auto;">
   <thead>
      <tr>
         <th style="text-align: center;">Function</th>
         <th style="text-align: center;">Description</th>
         <th style="text-align: center;">Details</th>
      </tr>
   </thead>
   <tbody>
      <tr>
         <td><code>np.array</code></td>
         <td>Create an array</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.array.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.asarray</code></td>
         <td>Convert the input to an array</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.asarray.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.astype</code></td>
         <td>Copies an array to a specified data type</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.astype.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.copy</code></td>
         <td>Return an array copy of the given object</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.copy.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.fromfile</code></td>
         <td>Construct an array from data in a text or binary file</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.fromfile.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.loadtxt</code></td>
         <td>Load data from a text file</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html">link</a></td>
      </tr>
   </tbody>
</table>

### numpy.array
   - Always creates a new array, even if the input is already a NumPy array.
   - It's useful when you need a new array that is independent of the original data.

In [11]:
arr_1d_1 = np.array([1, 2, 3, 4])
arr_2d_1 = np.array([[1, 2, 3], [4, 5, 6]])
arr_3d_1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# log
print(f"arr_1d_1 :\n{arr_1d_1}", end=f"\n{'-' * 50}\n")
print(f"arr_2d_1 :\n{arr_2d_1}", end=f"\n{'-' * 50}\n")
print(f"arr_3d_1 :\n{arr_3d_1}")

arr_1d_1 :
[1 2 3 4]
--------------------------------------------------
arr_2d_1 :
[[1 2 3]
 [4 5 6]]
--------------------------------------------------
arr_3d_1 :
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### numpy.asarray
   - Converts the input to an array, but does not create a copy if the input is already a NumPy array with the same dtype.
   - It's useful when you want to avoid unnecessary copies and work directly with the original data.

In [18]:
list_1d_1 = [1, 2, 3, 4]
arr_1d_2 = np.array([1, 2, 3, 4])

# asarray
asarr_1d_1 = np.asarray(list_1d_1)
asarr_1d_2 = np.asarray(arr_1d_2)

# index assignment
list_1d_1[0] = 0
arr_1d_2[0] = 0

# log
print(f"asarr_1d_1: {asarr_1d_1}")
print(f"asarr_1d_2: {asarr_1d_2}")

asarr_1d_1: [1 2 3 4]
asarr_1d_2: [0 2 3 4]


### numpy.copy

In [13]:
arr_2d_2 = np.array([[1, 2, 3], [4, 5, 6]])
arr_2d_3 = arr_2d_2

# index assignment
arr_2d_2[1, 0] = -1
arr_2d_3[0] = [3, 2, 1]

# log
print(f"arr_2d_2 :\n{arr_2d_2}", end=f"\n{'-' * 50}\n")
print(f"arr_2d_3 :\n{arr_2d_3}", end=f"\n{'-' * 50}\n")

arr_2d_2 :
[[ 3  2  1]
 [-1  5  6]]
--------------------------------------------------
arr_2d_3 :
[[ 3  2  1]
 [-1  5  6]]
--------------------------------------------------


In [14]:
arr_2d_4 = np.array([[1, 2, 3], [4, 5, 6]])
arr_2d_5 = np.copy(arr_2d_4)

# index assignment
arr_2d_4[1, 0] = 0
arr_2d_5[0] = [3, 2, 1]

# log
print(f"arr_2d_4 :\n{arr_2d_4}", end=f"\n{'-' * 50}\n")
print(f"arr_2d_5 :\n{arr_2d_5}", end=f"\n{'-' * 50}\n")

arr_2d_4 :
[[1 2 3]
 [0 5 6]]
--------------------------------------------------
arr_2d_5 :
[[3 2 1]
 [4 5 6]]
--------------------------------------------------


## Numerical Ranges

<table style="margin: 0 auto;">
   <thead>
      <tr>
         <th style="text-align: center;">Function</th>
         <th style="text-align: center;">Description</th>
         <th style="text-align: center;">Details</th>
      </tr>
   </thead>
   <tbody>
      <tr>
         <td><code>np.arange</code></td>
         <td>Return evenly spaced values within a given interval</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.arange.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.linspace</code></td>
         <td>Return evenly spaced numbers over a specified interval</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.linspace.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.meshgrid</code></td>
         <td>Return a tuple of coordinate matrices from coordinate vectors</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.meshgrid.html">link</a></td>
      </tr>
   </tbody>
</table>

### numpy.arange

In [15]:
arange_1 = np.arange(3)
arange_2 = np.arange(5)
arange_3 = np.arange(2, 5)
arange_4 = np.arange(0, 7, 2)
arange_5 = np.arange(0, 1, .1)

# log
print(f"arange_1: {arange_1}")
print(f"arange_2: {arange_2}")
print(f"arange_3: {arange_3}")
print(f"arange_4: {arange_4}")
print(f"arange_5: {arange_5}")

arange_1: [0 1 2]
arange_2: [0 1 2 3 4]
arange_3: [2 3 4]
arange_4: [0 2 4 6]
arange_5: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


### numpy.linspace

In [16]:
linspace_1 = np.linspace(0, 2, 3)
linspace_2 = np.linspace(0, 1, 5)
linspace_3 = np.linspace(0, 2, 3, dtype=int)
linspace_4 = np.linspace((0, 3), (2, 5), 3, axis=0)
linspace_5 = np.linspace((0, 3), (2, 5), 3, axis=1)

# log
print(f"linspace_1 :\n{linspace_1}", end=f"\n{'-' * 50}\n")
print(f"linspace_2 :\n{linspace_2}", end=f"\n{'-' * 50}\n")
print(f"linspace_3 :\n{linspace_3}", end=f"\n{'-' * 50}\n")
print(f"linspace_4 :\n{linspace_4}", end=f"\n{'-' * 50}\n")
print(f"linspace_5 :\n{linspace_5}")

linspace_1 :
[0. 1. 2.]
--------------------------------------------------
linspace_2 :
[0.   0.25 0.5  0.75 1.  ]
--------------------------------------------------
linspace_3 :
[0 1 2]
--------------------------------------------------
linspace_4 :
[[0. 3.]
 [1. 4.]
 [2. 5.]]
--------------------------------------------------
linspace_5 :
[[0. 1. 2.]
 [3. 4. 5.]]


### numpy.meshgrid
   - It is primarily used to create coordinate grids for vectorized evaluations of functions over a grid.

In [17]:
# define the coordinate arrays
x = np.linspace(0, 2, 3)
y = np.linspace(0, 1, 5)

# create the meshgrid
X, Y = np.meshgrid(x, y)

# log
print(f"X :\n{X}", end=f"\n{'-' * 50}\n")
print(f"Y :\n{Y}", end=f"\n{'-' * 50}\n")

# example of using the meshgrid to evaluate a function
Z = np.sin(X) + np.cos(Y)
print(f"Z :\n{Z}")

X :
[[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]
--------------------------------------------------
Y :
[[0.   0.   0.  ]
 [0.25 0.25 0.25]
 [0.5  0.5  0.5 ]
 [0.75 0.75 0.75]
 [1.   1.   1.  ]]
--------------------------------------------------
Z :
[[1.         1.84147098 1.90929743]
 [0.96891242 1.81038341 1.87820985]
 [0.87758256 1.71905355 1.78687999]
 [0.73168887 1.57315985 1.6409863 ]
 [0.54030231 1.38177329 1.44959973]]
