📝 **Author:** Amirhossein Heydari - 📧 **Email:** AmirhosseinHeydari78@gmail.com - 📍 **Linktree:** [linktr.ee/mr_pylin](https://linktr.ee/mr_pylin)

---

# Dependencies

In [1]:
import numpy as np

In [2]:
rng = np.random.default_rng(seed=42)

# NumPy - Mathematics
Docs:
   - [numpy.org/doc/stable/reference/routines.math.html](https://numpy.org/doc/stable/reference/routines.math.html)

## Trigonometric functions
   - sin
   - cos
   - tan
   - arcsin | asin
   - arccos | acos
   - arctan | atan
   - rad2deg | degrees
   - deg2rad | radians
   - ...

In [3]:
arr_1d_1 = np.array([0, np.pi / 2, np.pi])

# sin
sin_1 = np.sin(arr_1d_1)

# cos
cos_1 = np.cos(arr_1d_1)

# tan
tan_1 = np.tan(arr_1d_1)

# arcsin
arcsin_1 = np.arcsin(sin_1)

# arccos
arccos_1 = np.arccos(cos_1)

# arctan
arctan_1 = np.arctan(tan_1)

# log
print(f"sin_1    : {sin_1}")
print(f"cos_1    : {cos_1}")
print(f"tan_1    : {tan_1}")
print(f"arcsin_1 : {arcsin_1}")
print(f"arccos_1 : {arccos_1}")
print(f"arctan_1 : {arctan_1}")

sin_1    : [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos_1    : [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan_1    : [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
arcsin_1 : [0.00000000e+00 1.57079633e+00 1.22464680e-16]
arccos_1 : [0.         1.57079633 3.14159265]
arctan_1 : [ 0.00000000e+00  1.57079633e+00 -1.22464680e-16]


In [4]:
# radian to degree
degrees_1 = np.degrees([0, np.pi / 2, np.pi])
rad2deg_1 = np.rad2deg([0, np.pi / 2, np.pi])

# degree to radian
radians_1 = np.radians([0, 90, 180])
deg2rad_1 = np.deg2rad([0, 90, 180])

# log
print(f"degrees_1 : {degrees_1}")
print(f"rad2deg_1 : {rad2deg_1}")
print(f"radians_1 : {radians_1}")
print(f"deg2rad_1 : {deg2rad_1}")

degrees_1 : [  0.  90. 180.]
rad2deg_1 : [  0.  90. 180.]
radians_1 : [0.         1.57079633 3.14159265]
deg2rad_1 : [0.         1.57079633 3.14159265]


## Hyperbolic functions
   - sinh
   - cosh
   - tanh
   - ...

In [5]:
arr_1d_2 = np.array([0, np.pi / 2, np.pi])

# sinh
sinh_1 = np.sinh(arr_1d_1)

# cosh
cosh_1 = np.cosh(arr_1d_1)

# tanh
tanh_1 = np.tanh(arr_1d_1)

# arcsinh
arcsinh_1 = np.arcsinh(sinh_1)

# arccosh
arccosh_1 = np.arccosh(cosh_1)

# arctanh
arctanh_1 = np.arctanh(tanh_1)

# log
print(f"sinh_1    : {sinh_1}")
print(f"cosh_1    : {cosh_1}")
print(f"tanh_1    : {tanh_1}")
print(f"arcsinh_1 : {arcsinh_1}")
print(f"arccosh_1 : {arccosh_1}")
print(f"arctanh_1 : {arctanh_1}")

sinh_1    : [ 0.          2.3012989  11.54873936]
cosh_1    : [ 1.          2.50917848 11.59195328]
tanh_1    : [0.         0.91715234 0.99627208]
arcsinh_1 : [0.         1.57079633 3.14159265]
arccosh_1 : [0.         1.57079633 3.14159265]
arctanh_1 : [0.         1.57079633 3.14159265]


## Rounding
   - round : Evenly round to the given number of decimals
   - rint : Round elements of the array to the nearest integer
   - fix : Round to nearest integer towards zero
   - floor : Return the floor of the input, element-wise
   - ceil : Return the ceiling of the input, element-wise
   - trunc : Return the truncated value of the input, element-wise

In [6]:
arr_1d_3 = np.array([-1.9541, -1.1161, 0.5, 1.2345, 1.6664])

round_1 = np.round(arr_1d_2, 3)
rint_1 = np.rint(arr_1d_3)
fix_1 = np.fix(arr_1d_3)
floor_1 = np.floor(arr_1d_3)
ceil_1 = np.ceil(arr_1d_3)
trunc_1 = np.trunc(arr_1d_3)  # same results as np.fix

# log
print(f"round_1  : {round_1}")
print(f"rint_1   : {rint_1}")
print(f"fix_1    : {fix_1}")
print(f"floor_1  : {floor_1}")
print(f"ceil_1   : {ceil_1}")
print(f"trunc_1  : {trunc_1}")

round_1  : [0.    1.571 3.142]
rint_1   : [-2. -1.  0.  1.  2.]
fix_1    : [-1. -1.  0.  1.  1.]
floor_1  : [-2. -2.  0.  1.  1.]
ceil_1   : [-1. -1.  1.  2.  2.]
trunc_1  : [-1. -1.  0.  1.  1.]


## Sums, products, differences

In [7]:
arr_1d_4 = np.array([1, 3, 4, 2])
arr_2d_1 = np.array([[2, 5], [6, 0]])

# sum
sum_1 = np.sum(arr_1d_4)
sum_2 = np.sum(arr_2d_1)
sum_3 = np.sum(arr_2d_1, axis= 0)
sum_4 = np.sum(arr_2d_1, axis= 1)

# cumsum
cumsum_1 = np.cumsum(arr_1d_4)
cumsum_2 = np.cumsum(arr_2d_1)
cumsum_3 = np.cumsum(arr_2d_1, axis= 0)
cumsum_4 = np.cumsum(arr_2d_1, axis= 1)

# log
print(f"sum_1 :\n{sum_1}", end='\n\n')
print(f"sum_2 :\n{sum_2}", end='\n\n')
print(f"sum_3 :\n{sum_3}", end='\n\n')
print(f"sum_4 :\n{sum_4}", end='\n\n')
print(f"cumsum_1 :\n{cumsum_1}", end='\n\n')
print(f"cumsum_2 :\n{cumsum_2}", end='\n\n')
print(f"cumsum_3 :\n{cumsum_3}", end='\n\n')
print(f"cumsum_4 :\n{cumsum_4}")

sum_1 :
10

sum_2 :
13

sum_3 :
[8 5]

sum_4 :
[7 6]

cumsum_1 :
[ 1  4  8 10]

cumsum_2 :
[ 2  7 13 13]

cumsum_3 :
[[2 5]
 [8 5]]

cumsum_4 :
[[2 7]
 [6 6]]


In [8]:
arr_1d_5 = np.array([1, 3, 4, 2])
arr_2d_2 = np.array([[2, 5], [6, 1]])

# prod
prod_1 = np.prod(arr_1d_5)
prod_2 = np.prod(arr_2d_2)
prod_3 = np.prod(arr_2d_2, axis= 0)
prod_4 = np.prod(arr_2d_2, axis= 1)

# cumprod
cumprod_1 = np.cumprod(arr_1d_5)
cumprod_2 = np.cumprod(arr_2d_2)
cumprod_3 = np.cumprod(arr_2d_2, axis= 0)
cumprod_4 = np.cumprod(arr_2d_2, axis= 1)

# log
print(f"prod_1 :\n{prod_1}", end='\n\n')
print(f"prod_2 :\n{prod_2}", end='\n\n')
print(f"prod_3 :\n{prod_3}", end='\n\n')
print(f"prod_4 :\n{prod_4}", end='\n\n')
print(f"cumprod_1 :\n{cumprod_1}", end='\n\n')
print(f"cumprod_2 :\n{cumprod_2}", end='\n\n')
print(f"cumprod_3 :\n{cumprod_3}", end='\n\n')
print(f"cumprod_4 :\n{cumprod_4}")

prod_1 :
24

prod_2 :
60

prod_3 :
[12  5]

prod_4 :
[10  6]

cumprod_1 :
[ 1  3 12 24]

cumprod_2 :
[ 2 10 60 60]

cumprod_3 :
[[ 2  5]
 [12  5]]

cumprod_4 :
[[ 2 10]
 [ 6  6]]


In [9]:
arr_1d_6 = np.array([1, 3, 4, 2, -1])
arr_2d_3 = np.array([[2, 5, 1], [6, 0, 2]])
arr_3d_1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])


# diff
diff_1 = np.diff(arr_1d_6)
diff_2 = np.diff(arr_2d_3, axis= 0)
diff_3 = np.diff(arr_2d_3, axis= 1)

# ediff1d
ediff1d_1 = np.ediff1d(arr_1d_6)
ediff1d_2 = np.ediff1d(arr_2d_3)
ediff1d_3 = np.ediff1d(arr_3d_1)

# gradient
gradient_1 = np.gradient(arr_1d_6)
gradient_2 = np.gradient(arr_2d_3)
gradient_3 = np.gradient(arr_3d_1)

# log
print(f"diff_1:\n{diff_1}", end='\n\n')
print(f"diff_2:\n{diff_2}", end='\n\n')
print(f"diff_3:\n{diff_3}", end='\n\n')
print(f"ediff1d_1:\n{ediff1d_1}", end='\n\n')
print(f"ediff1d_2:\n{ediff1d_2}", end='\n\n')
print(f"ediff1d_3:\n{ediff1d_3}", end='\n\n')
print(f"gradient_1:\n{gradient_1}", end='\n\n')
print(f"gradient_2:\n{gradient_2}", end='\n\n')
print(f"gradient_3:\n{gradient_3}")

diff_1:
[ 2  1 -2 -3]

diff_2:
[[ 4 -5  1]]

diff_3:
[[ 3 -4]
 [-6  2]]

ediff1d_1:
[ 2  1 -2 -3]

ediff1d_2:
[ 3 -4  5 -6  2]

ediff1d_3:
[1 1 1 1 1 1 1]

gradient_1:
[ 2.   1.5 -0.5 -2.5 -3. ]

gradient_2:
(array([[ 4., -5.,  1.],
       [ 4., -5.,  1.]]), array([[ 3. , -0.5, -4. ],
       [-6. , -2. ,  2. ]]))

gradient_3:
(array([[[4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.]]]), array([[[2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.]]]), array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]]))


In [10]:
arr_1d_7 = np.array([1, 3, 4])
arr_1d_8 = np.array([2, 3, 5])

# cross product
cross_1 = np.cross(arr_1d_7, arr_1d_8)

# log
print(f"cross_1: {cross_1}")

cross_1: [ 3  3 -3]


## Exponents and logarithms

In [11]:
arr_1d_9 = np.array([1, 2, 3, 4])

# exp
exp_1 = np.exp(arr_1d_9)

# expm1
expm1_1 = np.expm1(arr_1d_9)

# exp2
exp2_1 = np.exp2(arr_1d_9)

# log
print(f"exp_1  : {exp_1}")
print(f"expm1_1: {expm1_1}")
print(f"exp2_1 : {exp2_1}")

exp_1  : [ 2.71828183  7.3890561  20.08553692 54.59815003]
expm1_1: [ 1.71828183  6.3890561  19.08553692 53.59815003]
exp2_1 : [ 2.  4.  8. 16.]


In [12]:
arr_1d_10 = np.array([1000, 2000, 3000])

# log
log_1 = np.log(arr_1d_10)

# log10
log10_1 = np.log10(arr_1d_10)

# log2
log2_1 = np.log2(arr_1d_10)

# log1p
log1p_1 = np.log1p(arr_1d_10)

# log
print(f"log_1   : {log_1}")
print(f"log10_1 : {log10_1}")
print(f"log2_1  : {log2_1}")
print(f"log1p_1 : {log1p_1}")

log_1   : [6.90775528 7.60090246 8.00636757]
log10_1 : [3.         3.30103    3.47712125]
log2_1  : [ 9.96578428 10.96578428 11.55074679]
log1p_1 : [6.90875478 7.60140233 8.00670085]


## Cardinal Sinus

In [13]:
arr_1d_11 = np.array([0, 5, 100])

# sinc
sinc_1 = np.sinc(arr_1d_11)

# log
print(f"sinc_1: {sinc_1}")

sinc_1: [1.00000000e+00 3.89817183e-17 6.25283714e-18]


## Rational routines

In [14]:
# lowest common multiple
lcm_1 = np.lcm(3, 4)

# log
print(f"lcm_1: {lcm_1}")

lcm_1: 12


In [15]:
# greatest common divisor
gcd_1 = np.gcd(48, 81)

# log
print(f"gcd_1: {gcd_1}")

gcd_1: 3


## Arithmetic operations

In [16]:
scalar = 4
arr_1d_13 = np.array([1, 2, 3, 4])
arr_1d_14 = np.array([3, 4, 1, 2])

# add (element-wise)
add_1 = np.add(arr_1d_13, scalar)     # arr_1d_13 + scalar
add_2 = np.add(arr_1d_13, arr_1d_14)  # arr_1d_13 + arr_1d_14

# subtract (element-wise)
subtract_1 = np.subtract(arr_1d_13, scalar)     # arr_1d_13 - scalar
subtract_2 = np.subtract(arr_1d_13, arr_1d_14)  # arr_1d_13 - arr_1d_14

# multiply (element-wise)
multiply_1 = np.multiply(arr_1d_13, scalar)     # arr_1d_13 * scalar
multiply_2 = np.multiply(arr_1d_13, arr_1d_14)  # arr_1d_13 * arr_1d_14

# divide (element-wise)
divide_1 = np.divide(arr_1d_13, scalar)     # arr_1d_13 / scalar
divide_2 = np.divide(arr_1d_13, arr_1d_14)  # arr_1d_13 / arr_1d_14

# power (element-wise)
power_1 = np.power(arr_1d_13, scalar)     # arr_1d_13 ** scalar
power_2 = np.power(arr_1d_13, arr_1d_14)  # arr_1d_13 ** arr_1d_14

# negative (element-wise)
negative_1 = np.negative(arr_1d_13)  # -arr_1d_13
negative_2 = np.negative(arr_1d_14)  # -arr_1d_14

# floor_divide (element-wise)
floor_divide_1 = np.floor_divide(arr_1d_13, scalar)     # arr_1d_13 // scalar
floor_divide_2 = np.floor_divide(arr_1d_13, arr_1d_14)  # arr_1d_13 // arr_1d_14

# remainder (element-wise) [equal to np.mod]
remainder_1 = np.remainder(arr_1d_13, scalar)     # arr_1d_13 % scalar
remainder_2 = np.remainder(arr_1d_13, arr_1d_14)  # arr_1d_13 % arr_1d_14

# divmod (element-wise)
divmod_1 = np.divmod(arr_1d_13, scalar)
divmod_2 = np.divmod(arr_1d_13, arr_1d_14)


# log
print(f"add_1          : {add_1}")
print(f"add_2          : {add_2}")
print(f"subtract_1     : {subtract_1}")
print(f"subtract_2     : {subtract_2}")
print(f"multiply_1     : {multiply_1}")
print(f"multiply_2     : {multiply_2}")
print(f"divide_1       : {divide_1}")
print(f"divide_2       : {divide_2}")
print(f"power_1        : {power_1}")
print(f"power_2        : {power_2}")
print(f"negative_1     : {negative_1}")
print(f"negative_2     : {negative_2}")
print(f"floor_divide_1 : {floor_divide_1}")
print(f"floor_divide_2 : {floor_divide_2}")
print(f"remainder_1    : {remainder_1}")
print(f"remainder_2    : {remainder_2}")
print(f"divmod_1       : {divmod_1}")
print(f"divmod_2       : {divmod_2}")

add_1          : [5 6 7 8]
add_2          : [4 6 4 6]
subtract_1     : [-3 -2 -1  0]
subtract_2     : [-2 -2  2  2]
multiply_1     : [ 4  8 12 16]
multiply_2     : [3 8 3 8]
divide_1       : [0.25 0.5  0.75 1.  ]
divide_2       : [0.33333333 0.5        3.         2.        ]
power_1        : [  1  16  81 256]
power_2        : [ 1 16  3 16]
negative_1     : [-1 -2 -3 -4]
negative_2     : [-3 -4 -1 -2]
floor_divide_1 : [0 0 0 1]
floor_divide_2 : [0 0 3 2]
remainder_1    : [1 2 3 0]
remainder_2    : [1 2 0 0]
divmod_1       : (array([0, 0, 0, 1]), array([1, 2, 3, 0]))
divmod_2       : (array([0, 0, 3, 2]), array([1, 2, 0, 0]))


## Handling complex numbers

In [17]:
arr_1d_15 = np.array([1+2j, -1j, 2, 2-1j])

# real
real_1 = np.real(arr_1d_15)

# imag
imag_1 = np.imag(arr_1d_15)

# conjugate
conj_1 = np.conjugate(arr_1d_15)

# angle
angle_1 = np.angle(arr_1d_15)

# log
print(f"real_1 : {real_1}")
print(f"imag_1 : {imag_1}")
print(f"conj_1 : {conj_1}")
print(f"angle_1: {angle_1}")

real_1 : [ 1. -0.  2.  2.]
imag_1 : [ 2. -1.  0. -1.]
conj_1 : [ 1.-2.j -0.+1.j  2.-0.j  2.+1.j]
angle_1: [ 1.10714872 -1.57079633  0.         -0.46364761]


## Extrema finding

In [18]:
arr_1d_16 = rng.random(size=5)
arr_1d_17 = rng.random(size=5)

# max
max_1 = np.max(arr_1d_16)
max_2 = np.max(arr_1d_17)

# min
min_1 = np.min(arr_1d_16)
min_2 = np.min(arr_1d_17)

# maximum
maximum_1 = np.maximum(arr_1d_16, 0.5)
maximum_2 = np.maximum(arr_1d_16, arr_1d_17)

# minimum
minimum_1 = np.minimum(arr_1d_16, 0.5)
minimum_2 = np.minimum(arr_1d_16, arr_1d_17)

# log
print(f"arr_1d_16: {arr_1d_16}")
print(f"arr_1d_17: {arr_1d_17}", end='\n\n')
print(f"max_1     : {max_1}")
print(f"max_2     : {max_2}")
print(f"min_1     : {min_1}")
print(f"min_2     : {min_2}")
print(f"maximum_1 : {maximum_1}")
print(f"maximum_2 : {maximum_2}")
print(f"minimum_1 : {minimum_1}")
print(f"minimum_2 : {minimum_2}")

arr_1d_16: [0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
arr_1d_17: [0.97562235 0.7611397  0.78606431 0.12811363 0.45038594]

max_1     : 0.8585979199113825
max_2     : 0.9756223516367559
min_1     : 0.09417734788764953
min_2     : 0.12811363267554587
maximum_1 : [0.77395605 0.5        0.85859792 0.69736803 0.5       ]
maximum_2 : [0.97562235 0.7611397  0.85859792 0.69736803 0.45038594]
minimum_1 : [0.5        0.43887844 0.5        0.5        0.09417735]
minimum_2 : [0.77395605 0.43887844 0.78606431 0.12811363 0.09417735]


## Miscellaneous

In [19]:
arr_1d_18 = np.array([124, 534, 234, 123])

# sqrt
sqrt_1 = np.sqrt(arr_1d_18)

# cbrt
cbrt_1 = np.cbrt(arr_1d_18)


# log
print(f"sqrt_1: {sqrt_1}")
print(f"cbrt_1: {cbrt_1}")

sqrt_1: [11.13552873 23.10844002 15.29705854 11.09053651]
cbrt_1: [4.98663095 8.11298025 6.16224015 4.97318983]


In [20]:
arr_1d_19 = rng.random(size=5) - .5

# absolute
absolute_1 = np.absolute(arr_1d_19)

# sign
sign_1 = np.sign(arr_1d_19)

# log
print(f"arr_1d_19: {arr_1d_19}", end='\n\n')
print(f"absolute_1: {absolute_1}")
print(f"sign_1    : {sign_1}")

arr_1d_19: [-0.12920198  0.42676499  0.14386512  0.32276161 -0.0565858 ]

absolute_1: [0.12920198 0.42676499 0.14386512 0.32276161 0.0565858 ]
sign_1    : [-1.  1.  1.  1. -1.]


In [21]:
signal = np.array([1, 2, 3])
filter = np.array([0, 1, 0.5])

# convolve
convolve_1 = np.convolve(signal, filter)                 # signal = [0, 0, 1, 2, 3, 0, 0]
convolve_2 = np.convolve(signal, filter, mode= 'same')   # signal = [0, 1, 2, 3, 0]
convolve_3 = np.convolve(signal, filter, mode= 'valid')  # signal = [1, 2, 3]

# log
print(f"convolve_1: {convolve_1}")
print(f"convolve_2: {convolve_2}")
print(f"convolve_3: {convolve_3}")

convolve_1: [0.  1.  2.5 4.  1.5]
convolve_2: [1.  2.5 4. ]
convolve_3: [2.5]


In [22]:
arr_1d_20 = np.array([-5, -3, 0, 3, 5])

# clip
clip_1 = np.clip(arr_1d_20, -2, 2)

# log
print(f"clip_1: {clip_1}")

clip_1: [-2 -2  0  2  2]
