# Dependencies

In [14]:
import numpy as np

In [15]:
# prevent printing the returned object in each cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'none'

# NumPy - Sort, Search, Count
Doc:
   - [numpy.org/doc/stable/reference/routines.sort.html](https://numpy.org/doc/stable/reference/routines.sort.html)

## Sorting
   - quick sort: [javatpoint.com/quick-sort](https://www.javatpoint.com/quick-sort)
   - merge sort: [javatpoint.com/merge-sort](https://www.javatpoint.com/merge-sort)
   - heap sort : [javatpoint.com/heap-sort](https://www.javatpoint.com/heap-sort)

In [16]:
arr_1d_1 = np.random.randint(low=1, high=99, size=(10))
arr_2d_1 = np.random.randint(low=1, high=99, size=(3, 4))

# sort
sort_1 = np.sort(arr_1d_1)
sort_2 = np.sort(arr_1d_1, kind='mergesort')
sort_3 = np.sort(arr_1d_1, kind='heapsort')
sort_4 = np.sort(arr_2d_1, axis=None)
sort_5 = np.sort(arr_2d_1, axis=0)
sort_6 = np.sort(arr_2d_1, axis=1)

# log
print(f"arr_1d_1: {arr_1d_1}", end='\n\n')
print(f"arr_2d_1:\n{arr_2d_1}", end='\n\n')
print('-' * 50)
print(f"sort_1:\n{sort_1}", end='\n\n')
print(f"sort_2:\n{sort_2}", end='\n\n')
print(f"sort_3:\n{sort_3}", end='\n\n')
print(f"sort_4:\n{sort_4}", end='\n\n')
print(f"sort_5:\n{sort_5}", end='\n\n')
print(f"sort_6:\n{sort_6}")

arr_1d_1: [74 68 55 28 70 95 13 59 49 96]

arr_2d_1:
[[80 18 85 44]
 [56 80 70 45]
 [58 73 70 47]]

--------------------------------------------------
sort_1:
[13 28 49 55 59 68 70 74 95 96]

sort_2:
[13 28 49 55 59 68 70 74 95 96]

sort_3:
[13 28 49 55 59 68 70 74 95 96]

sort_4:
[18 44 45 47 56 58 70 70 73 80 80 85]

sort_5:
[[56 18 70 44]
 [58 73 70 45]
 [80 80 85 47]]

sort_6:
[[18 44 80 85]
 [45 56 70 80]
 [47 58 70 73]]


In [17]:
arr_1d_2 = np.random.randint(low=1, high=99, size=(10))
arr_1d_3 = np.arange(stop=10)
arr_2d_2 = np.random.randint(low=1, high=99, size=(3, 4))

# argsort
argsort_1 = np.argsort(arr_1d_2)
argsort_2 = np.argsort(arr_2d_2, axis=None)
argsort_3 = np.argsort(arr_2d_2, axis=0)
argsort_4 = np.argsort(arr_2d_2, axis=1)

# sort by index
sort_1 = arr_1d_2[argsort_1]
sort_2 = arr_1d_3[argsort_1]
sort_3 = arr_2d_2.flatten()[argsort_2]
sort_4 = np.take_along_axis(arr=arr_2d_2, indices=argsort_3, axis=0)
sort_5 = np.take_along_axis(arr=arr_2d_2, indices=argsort_4, axis=1)

# log
print(f"arr_1d_2:\n{arr_1d_2}", end='\n\n')
print(f"arr_1d_3:\n{arr_1d_3}", end='\n\n')
print(f"arr_2d_2:\n{arr_2d_2}", end='\n\n')
print('-' * 50)
print(f"argsort_1:\n{argsort_1}", end='\n\n')
print(f"argsort_2:\n{argsort_2}", end='\n\n')
print(f"argsort_3:\n{argsort_3}", end='\n\n')
print(f"argsort_4:\n{argsort_4}", end='\n\n')
print('-' * 50)
print(f"sort_1:\n{sort_1}", end='\n\n')
print(f"sort_2:\n{sort_2}", end='\n\n')
print(f"sort_3:\n{sort_3}", end='\n\n')
print(f"sort_4:\n{sort_4}", end='\n\n')
print(f"sort_5:\n{sort_5}")

arr_1d_2:
[66 97 42 77 73 78 18 20 68 68]

arr_1d_3:
[0 1 2 3 4 5 6 7 8 9]

arr_2d_2:
[[23 30 95 69]
 [15 47 11 20]
 [27 63 97 68]]

--------------------------------------------------
argsort_1:
[6 7 2 0 9 8 4 3 5 1]

argsort_2:
[ 6  4  7  0  8  1  5  9 11  3  2 10]

argsort_3:
[[1 0 1 1]
 [0 1 0 2]
 [2 2 2 0]]

argsort_4:
[[0 1 3 2]
 [2 0 3 1]
 [0 1 3 2]]

--------------------------------------------------
sort_1:
[18 20 42 66 68 68 73 77 78 97]

sort_2:
[6 7 2 0 9 8 4 3 5 1]

sort_3:
[11 15 20 23 27 30 47 63 68 69 95 97]

sort_4:
[[15 30 11 20]
 [23 47 95 68]
 [27 63 97 69]]

sort_5:
[[23 30 69 95]
 [11 15 20 47]
 [27 63 68 97]]


In [18]:
names = np.array(['Alice', 'Bob', 'Charlie', 'David'])
grades = np.array([90, 85, 90, 85])
ages = np.array([20, 21, 19, 20])

# lexsort
indices_1 = np.lexsort((ages, grades))
sort_names_1 = names[indices_1]
sort_grades_1 = grades[indices_1]
sort_ages_1 = ages[indices_1]

indices_2 = np.lexsort((grades, ages))
sort_names_2 = names[indices_2]
sort_grades_2 = grades[indices_2]
sort_ages_2 = ages[indices_2]

# log
print(f"indices_1     : {indices_1}")
print(f"sort_names_1  : {sort_names_1}")
print(f"sort_grades_1 : {sort_grades_1}")
print(f"sort_ages_1   : {sort_ages_1}", end='\n\n')
print(f"indices_2     : {indices_2}")
print(f"sort_names_2  : {sort_names_2}")
print(f"sort_grades_2 : {sort_grades_2}")
print(f"sort_ages_2   : {sort_ages_2}")

indices_1     : [3 1 2 0]
sort_names_1  : ['David' 'Bob' 'Charlie' 'Alice']
sort_grades_1 : [85 85 90 90]
sort_ages_1   : [20 21 19 20]

indices_2     : [2 3 0 1]
sort_names_2  : ['Charlie' 'David' 'Alice' 'Bob']
sort_grades_2 : [90 85 90 85]
sort_ages_2   : [19 20 20 21]


In [19]:
data = np.array(
    [
        ('Alice', 90, 20),
        ('Bob', 85, 21),
        ('Charlie', 90, 19),
        ('David', 85, 20)
    ],
    dtype=[('name', 'U10'), ('grade', 'i4'), ('age', 'i4')]
)

# lexsort
indices_1 = np.lexsort((data['age'], data['grade']))
sort_data_1 = names[indices_1]

indices_2 = np.lexsort((data['grade'], data['age']))
sort_data_2 = names[indices_2]

# log
print(f"indices_1   : {indices_1}")
print(f"sort_data_1 : {sort_data_1}", end='\n\n')
print(f"indices_2   : {indices_2}")
print(f"sort_data_2 : {sort_data_2}")

indices_1   : [3 1 2 0]
sort_data_1 : ['David' 'Bob' 'Charlie' 'Alice']

indices_2   : [2 3 0 1]
sort_data_2 : ['Charlie' 'David' 'Alice' 'Bob']


In [20]:
arr_1d_4 = np.array([1, 5, 7, 7, 3, 5, 6, 2, 1, 9, 6, 4])

# partition
partition_1 = np.partition(arr_1d_4, kth=-1)

# argpartition
argpartition_1 = np.argpartition(arr_1d_4, kth=-1)
partition_2 = arr_1d_4[argpartition_1]

# log
print(f"partition_1   : {partition_1}")
print(f"argpartition_1: {argpartition_1}")
print(f"partition_2   : {partition_2}")

partition_1   : [1 1 2 3 4 5 5 6 6 7 7 9]
argpartition_1: [ 0  8  7  4 11  1  5  6 10  3  2  9]
partition_2   : [1 1 2 3 4 5 5 6 6 7 7 9]


## Searching

In [21]:
arr_1d_5 = np.random.randint(low=0, high=99, size=(10))
arr_2d_4 = np.random.randint(low=0, high=99, size=(3, 4))

# argmax
argmax_1 = np.argmax(arr_1d_5)
argmax_2 = np.argmax(arr_1d_5)
argmax_3 = np.argmax(arr_2d_4, axis=0)
argmax_4 = np.argmax(arr_2d_4, axis=1)

# argmin
argmin_1 = np.argmin(arr_1d_5)
argmin_2 = np.argmin(arr_1d_5)
argmin_3 = np.argmin(arr_2d_4, axis=0)
argmin_4 = np.argmin(arr_2d_4, axis=1)

# log
print(f"arr_1d_5:\n{arr_1d_5}", end='\n\n')
print(f"arr_2d_4:\n{arr_2d_4}")
print('-' * 50)
print(f"argmax_1: {argmax_1}")
print(f"argmax_2: {argmax_2}")
print(f"argmax_3: {argmax_3}")
print(f"argmax_4: {argmax_4}")
print(f"argmin_1: {argmin_1}")
print(f"argmin_2: {argmin_2}")
print(f"argmin_3: {argmin_3}")
print(f"argmin_4: {argmin_4}")

arr_1d_5:
[45 80 93 81 97 64 61  2 31 88]

arr_2d_4:
[[48 34 48 34]
 [82 82  7 86]
 [66  5 30 42]]
--------------------------------------------------
argmax_1: 4
argmax_2: 4
argmax_3: [1 1 0 1]
argmax_4: [0 3 0]
argmin_1: 7
argmin_2: 7
argmin_3: [0 2 1 0]
argmin_4: [1 2 1]


In [22]:
arr_1d_6 = np.random.randint(low=0, high=99, size=(10))
arr_2d_5 = np.random.randint(low=0, high=99, size=(3, 4))

# where
where_1 = np.where(arr_1d_6 > 50)
where_2 = np.where(arr_1d_6 > 50, 1, 0)
where_3 = np.where(arr_1d_6 > 50, -1, arr_1d_6)
where_4 = np.where(arr_2d_5 < 50)
where_5 = np.where(arr_2d_5 < 50, 1, 0)
where_6 = np.where(arr_2d_5 < 50, -1, arr_2d_5)

# argwhere
argwhere_1 = np.argwhere(arr_1d_6 > 50)
argwhere_2 = np.argwhere(arr_2d_5 > 50)

# log
print(f"arr_1d_6:\n{arr_1d_6}", end='\n\n')
print(f"arr_2d_5:\n{arr_2d_5}")
print('-' * 50)
print(f"where_1:\n{where_1}", end='\n\n')
print(f"where_2:\n{where_2}", end='\n\n')
print(f"where_3:\n{where_3}", end='\n\n')
print(f"where_4:\n{where_4}", end='\n\n')
print(f"where_5:\n{where_5}", end='\n\n')
print(f"where_6:\n{where_6}", end='\n\n')
print(f"argwhere_1:\n{argwhere_1}", end='\n\n')
print(f"argwhere_2:\n{argwhere_2}")

arr_1d_6:
[56 30 34 70 67  3 18  9 84 11]

arr_2d_5:
[[28 56 95 48]
 [90 23 87 94]
 [45 41 19 85]]
--------------------------------------------------
where_1:
(array([0, 3, 4, 8]),)

where_2:
[1 0 0 1 1 0 0 0 1 0]

where_3:
[-1 30 34 -1 -1  3 18  9 -1 11]

where_4:
(array([0, 0, 1, 2, 2, 2]), array([0, 3, 1, 0, 1, 2]))

where_5:
[[1 0 0 1]
 [0 1 0 0]
 [1 1 1 0]]

where_6:
[[-1 56 95 -1]
 [90 -1 87 94]
 [-1 -1 -1 85]]

argwhere_1:
[[0]
 [3]
 [4]
 [8]]

argwhere_2:
[[0 1]
 [0 2]
 [1 0]
 [1 2]
 [1 3]
 [2 3]]


In [23]:
arr_1d_7 = np.array([5, 3, 6, 8, 2, 4, 0])
arr_2d_6 = np.array([[5, 3, 1], [6, 4, 2]])

# nonzero
nonzero_1 = np.nonzero(arr_1d_7)
nonzero_2 = np.nonzero(arr_1d_7 < 4)
nonzero_3 = np.nonzero(arr_2d_6)
nonzero_4 = np.nonzero(arr_2d_6 < 4)

# log
print(f"nonzero_1: {nonzero_1}")
print(f"nonzero_2: {nonzero_2}")
print(f"nonzero_3: {nonzero_3}")
print(f"nonzero_4: {nonzero_4}")

nonzero_1: (array([0, 1, 2, 3, 4, 5]),)
nonzero_2: (array([1, 4, 6]),)
nonzero_3: (array([0, 0, 0, 1, 1, 1]), array([0, 1, 2, 0, 1, 2]))
nonzero_4: (array([0, 0, 1]), array([1, 2, 2]))


In [24]:
arr_1d_8 = np.array([1, 2, 5, 6])

# searchsorted
searchsorted_1 = np.searchsorted(arr_1d_8, v=3)
searchsorted_2 = np.searchsorted(arr_1d_8, v=4)
searchsorted_3 = np.searchsorted(arr_1d_8, v=7)

# log
print(f"searchsorted_1: {searchsorted_1}")
print(f"searchsorted_2: {searchsorted_2}")
print(f"searchsorted_3: {searchsorted_3}")

searchsorted_1: 2
searchsorted_2: 2
searchsorted_3: 4


In [25]:
arr_1d_9 = np.array([6, 3, 4, 7, 1, 2, 7, 9, 0, 3, 4])
arr_2d_7 = np.array([[5, 3, 1], [2, 4, 5]])

# extract
extract_1 = np.extract(arr_1d_9 < 4, arr_1d_9)
extract_2 = np.extract(arr_2d_7 % 2, arr_2d_7)

# log
print(f"extract_1: {extract_1}")
print(f"extract_2: {extract_2}")

extract_1: [3 1 2 0 3]
extract_2: [5 3 1 5]


## Counting

In [26]:
arr_1d_10 = np.array([6, 3, 4, 0, 1, 2, 7, 9, 0, 3, 4])

# count_nonzero
count_nonzero_1 = np.count_nonzero(arr_1d_10)
count_nonzero_2 = np.count_nonzero(arr_1d_10 % 2)

# log
print(f"count_nonzero_1: {count_nonzero_1}")
print(f"count_nonzero_2: {count_nonzero_2}")

count_nonzero_1: 9
count_nonzero_2: 5
