# Dependencies

In [1]:
import numpy as np

In [2]:
# prevent printing the returned object in each cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'none'

# NumPy - Sort, Search, Count
Doc:
   - [https://numpy.org/doc/stable/reference/routines.sort.html](https://numpy.org/doc/stable/reference/routines.sort.html)

## Sorting
   - quick sort: [javatpoint.com/quick-sort](https://www.javatpoint.com/quick-sort)
   - merge sort: [javatpoint.com/merge-sort](https://www.javatpoint.com/merge-sort)
   - heap sort : [javatpoint.com/heap-sort](https://www.javatpoint.com/heap-sort)

In [13]:
arr_1d_1 = np.random.randint(low=1, high=99, size=(10))
arr_2d_1 = np.random.randint(low=1, high=99, size=(3, 4))

# sort
sort_1 = np.sort(arr_1d_1)
sort_2 = np.sort(arr_1d_1, kind='mergesort')
sort_3 = np.sort(arr_1d_1, kind='heapsort')
sort_4 = np.sort(arr_2d_1, axis=None)
sort_5 = np.sort(arr_2d_1, axis=0)
sort_6 = np.sort(arr_2d_1, axis=1)

# log
print(f"arr_1d_1: {arr_1d_1}", end='\n\n')
print(f"arr_2d_1:\n{arr_2d_1}", end='\n\n')
print('-' * 50)
print(f"sort_1:\n{sort_1}", end='\n\n')
print(f"sort_2:\n{sort_2}", end='\n\n')
print(f"sort_3:\n{sort_3}", end='\n\n')
print(f"sort_4:\n{sort_4}", end='\n\n')
print(f"sort_5:\n{sort_5}", end='\n\n')
print(f"sort_6:\n{sort_6}")

arr_1d_1: [91 12 15 64 81 39 34 44 59  4]

arr_2d_1:
[[55 96 83 94]
 [93 78 11 58]
 [66 64 55 38]]

--------------------------------------------------
sort_1:
[ 4 12 15 34 39 44 59 64 81 91]

sort_2:
[ 4 12 15 34 39 44 59 64 81 91]

sort_3:
[ 4 12 15 34 39 44 59 64 81 91]

sort_4:
[11 38 55 55 58 64 66 78 83 93 94 96]

sort_5:
[[55 64 11 38]
 [66 78 55 58]
 [93 96 83 94]]

sort_6:
[[55 83 94 96]
 [11 58 78 93]
 [38 55 64 66]]


In [39]:
arr_1d_2 = np.random.randint(low=1, high=99, size=(10))
arr_1d_3 = np.arange(stop=10)
arr_2d_2 = np.random.randint(low=1, high=99, size=(3, 4))

# argsort
argsort_1 = np.argsort(arr_1d_2)
argsort_2 = np.argsort(arr_2d_2, axis=None)
argsort_3 = np.argsort(arr_2d_2, axis=0)
argsort_4 = np.argsort(arr_2d_2, axis=1)

# sort by index
sort_1 = arr_1d_2[argsort_1]
sort_2 = arr_1d_3[argsort_1]
sort_3 = arr_2d_2.flatten()[argsort_2]
sort_4 = np.take_along_axis(arr=arr_2d_2, indices=argsort_3, axis=0)
sort_5 = np.take_along_axis(arr=arr_2d_2, indices=argsort_4, axis=1)

# log
print(f"arr_1d_2:\n{arr_1d_2}", end='\n\n')
print(f"arr_1d_3:\n{arr_1d_3}", end='\n\n')
print(f"arr_2d_2:\n{arr_2d_2}", end='\n\n')
print('-' * 50)
print(f"argsort_1:\n{argsort_1}", end='\n\n')
print(f"argsort_2:\n{argsort_2}", end='\n\n')
print(f"argsort_3:\n{argsort_3}", end='\n\n')
print(f"argsort_4:\n{argsort_4}", end='\n\n')
print('-' * 50)
print(f"sort_1:\n{sort_1}", end='\n\n')
print(f"sort_2:\n{sort_2}", end='\n\n')
print(f"sort_3:\n{sort_3}", end='\n\n')
print(f"sort_4:\n{sort_4}", end='\n\n')
print(f"sort_5:\n{sort_5}")

arr_1d_2:
[50 18 79 88 55 74 95 11 82 92]

arr_1d_3:
[0 1 2 3 4 5 6 7 8 9]

arr_2d_2:
[[24 52 73 11]
 [33 10 53 34]
 [91 72 45 62]]

--------------------------------------------------
argsort_1:
[7 1 0 4 5 2 8 3 9 6]

argsort_2:
[ 5  3  0  4  7 10  1  6 11  9  2  8]

argsort_3:
[[0 1 2 0]
 [1 0 1 1]
 [2 2 0 2]]

argsort_4:
[[3 0 1 2]
 [1 0 3 2]
 [2 3 1 0]]

--------------------------------------------------
sort_1:
[11 18 50 55 74 79 82 88 92 95]

sort_2:
[7 1 0 4 5 2 8 3 9 6]

sort_3:
[10 11 24 33 34 45 52 53 62 72 73 91]

sort_4:
[[24 10 45 11]
 [33 52 53 34]
 [91 72 73 62]]

sort_5:
[[11 24 52 73]
 [10 33 34 53]
 [45 62 72 91]]


In [44]:
names = np.array(['Alice', 'Bob', 'Charlie', 'David'])
grades = np.array([90, 85, 90, 85])
ages = np.array([20, 21, 19, 20])

# lexsort
indices_1 = np.lexsort((ages, grades))
sort_names_1 = names[indices_1]
sort_grades_1 = grades[indices_1]
sort_ages_1 = ages[indices_1]

indices_2 = np.lexsort((grades, ages))
sort_names_2 = names[indices_2]
sort_grades_2 = grades[indices_2]
sort_ages_2 = ages[indices_2]

# log
print(f"indices_1     : {indices_1}")
print(f"sort_names_1  : {sort_names_1}")
print(f"sort_grades_1 : {sort_grades_1}")
print(f"sort_ages_1   : {sort_ages_1}", end='\n\n')
print(f"indices_2     : {indices_2}")
print(f"sort_names_2  : {sort_names_2}")
print(f"sort_grades_2 : {sort_grades_2}")
print(f"sort_ages_2   : {sort_ages_2}")

indices_1     : [3 1 2 0]
sort_names_1  : ['David' 'Bob' 'Charlie' 'Alice']
sort_grades_1 : [85 85 90 90]
sort_ages_1   : [20 21 19 20]

indices_2     : [2 3 0 1]
sort_names_2  : ['Charlie' 'David' 'Alice' 'Bob']
sort_grades_2 : [90 85 90 85]
sort_ages_2   : [19 20 20 21]


In [46]:
data = np.array(
    [
        ('Alice', 90, 20),
        ('Bob', 85, 21),
        ('Charlie', 90, 19),
        ('David', 85, 20)
    ],
    dtype=[('name', 'U10'), ('grade', 'i4'), ('age', 'i4')]
)

# lexsort
indices_1 = np.lexsort((data['age'], data['grade']))
sort_data_1 = names[indices_1]

indices_2 = np.lexsort((data['grade'], data['age']))
sort_data_2 = names[indices_2]

# log
print(f"indices_1   : {indices_1}")
print(f"sort_data_1 : {sort_data_1}", end='\n\n')
print(f"indices_2   : {indices_2}")
print(f"sort_data_2 : {sort_data_2}")

indices_1   : [3 1 2 0]
sort_data_1 : ['David' 'Bob' 'Charlie' 'Alice']

indices_2   : [2 3 0 1]
sort_data_2 : ['Charlie' 'David' 'Alice' 'Bob']


In [56]:
arr_1d_4 = np.array([1, 5, 7, 7, 3, 5, 6, 2, 1, 9, 6, 4])

# partition
partition_1 = np.partition(arr_1d_4, kth=-1)

# argpartition
argpartition_1 = np.argpartition(arr_1d_4, kth=-1)
partition_2 = arr_1d_4[argpartition_1]

# log
print(f"partition_1   : {partition_1}")
print(f"argpartition_1: {argpartition_1}")
print(f"partition_2   : {partition_2}")

partition_1   : [3 1 1 2 4 5 5 6 7 6 7 9]
argpartition_1: [ 4  0  8  7 11  5  1 10  2  6  3  9]
partition_2   : [3 1 1 2 4 5 5 6 7 6 7 9]


## Searching

In [59]:
arr_1d_5 = np.random.randint(low=0, high=99, size=(10))
arr_2d_4 = np.random.randint(low=0, high=99, size=(3, 4))

# argmax
argmax_1 = np.argmax(arr_1d_5)
argmax_2 = np.argmax(arr_1d_5)
argmax_3 = np.argmax(arr_2d_4, axis=0)
argmax_4 = np.argmax(arr_2d_4, axis=1)

# argmin
argmin_1 = np.argmin(arr_1d_5)
argmin_2 = np.argmin(arr_1d_5)
argmin_3 = np.argmin(arr_2d_4, axis=0)
argmin_4 = np.argmin(arr_2d_4, axis=1)

# log
print(f"arr_1d_5:\n{arr_1d_5}", end='\n\n')
print(f"arr_2d_4:\n{arr_2d_4}")
print('-' * 50)
print(f"argmax_1: {argmax_1}")
print(f"argmax_2: {argmax_2}")
print(f"argmax_3: {argmax_3}")
print(f"argmax_4: {argmax_4}")
print(f"argmin_1: {argmin_1}")
print(f"argmin_2: {argmin_2}")
print(f"argmin_3: {argmin_3}")
print(f"argmin_4: {argmin_4}")

arr_1d_5:
[53  5 41 10 46  7  3 90 60 97]

arr_2d_4:
[[33 12 90 68]
 [84 74 67 17]
 [30 73 46 53]]
--------------------------------------------------
argmax_1: 9
argmax_2: 9
argmax_3: [1 1 0 0]
argmax_4: [2 0 1]
argmin_1: 6
argmin_2: 6
argmin_3: [2 0 2 1]
argmin_4: [1 3 0]


In [78]:
arr_1d_6 = np.random.randint(low=0, high=99, size=(10))
arr_2d_5 = np.random.randint(low=0, high=99, size=(3, 4))

# where
where_1 = np.where(arr_1d_6 > 50)
where_2 = np.where(arr_1d_6 > 50, 1, 0)
where_3 = np.where(arr_1d_6 > 50, -1, arr_1d_6)
where_4 = np.where(arr_2d_5 < 50)
where_5 = np.where(arr_2d_5 < 50, 1, 0)
where_6 = np.where(arr_2d_5 < 50, -1, arr_2d_5)

# argwhere
argwhere_1 = np.argwhere(arr_1d_6 > 50)
argwhere_2 = np.argwhere(arr_2d_5 > 50)

# log
print(f"arr_1d_6:\n{arr_1d_6}", end='\n\n')
print(f"arr_2d_5:\n{arr_2d_5}")
print('-' * 50)
print(f"where_1:\n{where_1}", end='\n\n')
print(f"where_2:\n{where_2}", end='\n\n')
print(f"where_3:\n{where_3}", end='\n\n')
print(f"where_4:\n{where_4}", end='\n\n')
print(f"where_5:\n{where_5}", end='\n\n')
print(f"where_6:\n{where_6}", end='\n\n')
print(f"argwhere_1:\n{argwhere_1}", end='\n\n')
print(f"argwhere_2:\n{argwhere_2}")

arr_1d_6:
[30 71 42 71 91 61 20 63 37 19]

arr_2d_5:
[[46 96 63 37]
 [95 28 32  1]
 [87 66  3 96]]
--------------------------------------------------
where_1:
(array([1, 3, 4, 5, 7], dtype=int64),)

where_2:
[0 1 0 1 1 1 0 1 0 0]

where_3:
[30 -1 42 -1 -1 -1 20 -1 37 19]

where_4:
(array([0, 0, 1, 1, 1, 2], dtype=int64), array([0, 3, 1, 2, 3, 2], dtype=int64))

where_5:
[[1 0 0 1]
 [0 1 1 1]
 [0 0 1 0]]

where_6:
[[-1 96 63 -1]
 [95 -1 -1 -1]
 [87 66 -1 96]]

argwhere_1:
[[1]
 [3]
 [4]
 [5]
 [7]]

argwhere_2:
[[0 1]
 [0 2]
 [1 0]
 [2 0]
 [2 1]
 [2 3]]


In [80]:
arr_1d_7 = np.array([5, 3, 6, 8, 2, 4, 0])
arr_2d_6 = np.array([[5, 3, 1], [6, 4, 2]])

# nonzero
nonzero_1 = np.nonzero(arr_1d_7)
nonzero_2 = np.nonzero(arr_1d_7 < 4)
nonzero_3 = np.nonzero(arr_2d_6)
nonzero_4 = np.nonzero(arr_2d_6 < 4)

# log
print(f"nonzero_1: {nonzero_1}")
print(f"nonzero_2: {nonzero_2}")
print(f"nonzero_3: {nonzero_3}")
print(f"nonzero_4: {nonzero_4}")

nonzero_1: (array([0, 1, 2, 3, 4, 5], dtype=int64),)
nonzero_2: (array([1, 4, 6], dtype=int64),)
nonzero_3: (array([0, 0, 0, 1, 1, 1], dtype=int64), array([0, 1, 2, 0, 1, 2], dtype=int64))
nonzero_4: (array([0, 0, 1], dtype=int64), array([1, 2, 2], dtype=int64))


In [81]:
arr_1d_8 = np.array([1, 2, 5, 6])

# searchsorted
searchsorted_1 = np.searchsorted(arr_1d_8, v=3)
searchsorted_2 = np.searchsorted(arr_1d_8, v=4)
searchsorted_3 = np.searchsorted(arr_1d_8, v=7)

# log
print(f"searchsorted_1: {searchsorted_1}")
print(f"searchsorted_2: {searchsorted_2}")
print(f"searchsorted_3: {searchsorted_3}")

searchsorted_1: 2
searchsorted_2: 2
searchsorted_3: 4


In [83]:
arr_1d_9 = np.array([6, 3, 4, 7, 1, 2, 7, 9, 0, 3, 4])
arr_2d_7 = np.array([[5, 3, 1], [2, 4, 5]])

# extract
extract_1 = np.extract(arr_1d_9 < 4, arr_1d_9)
extract_2 = np.extract(arr_2d_7 % 2, arr_2d_7)

# log
print(f"extract_1: {extract_1}")
print(f"extract_2: {extract_2}")

extract_1: [3 1 2 0 3]
extract_2: [5 3 1 5]


## Counting

In [86]:
arr_1d_10 = np.array([6, 3, 4, 0, 1, 2, 7, 9, 0, 3, 4])

# count_nonzero
count_nonzero_1 = np.count_nonzero(arr_1d_10)
count_nonzero_2 = np.count_nonzero(arr_1d_10 % 2)

# log
print(f"count_nonzero_1: {count_nonzero_1}")
print(f"count_nonzero_2: {count_nonzero_2}")

count_nonzero_1: 9
count_nonzero_2: 5
