📝 **Author:** Amirhossein Heydari - 📧 **Email:** AmirhosseinHeydari78@gmail.com - 📍 **Linktree:** [linktr.ee/mr_pylin](https://linktr.ee/mr_pylin)

---

# Dependencies

In [40]:
import numpy as np

In [41]:
rng = np.random.default_rng(seed=42)

# NumPy - Sort, Search, Count
📝 Doc:
   - Sorting, searching, and counting: [numpy.org/doc/stable/reference/routines.sort.html](https://numpy.org/doc/stable/reference/routines.sort.html)

## Sorting

<table style="margin: 0 auto;">
   <thead>
      <tr>
         <th style="text-align: center;">Function</th>
         <th style="text-align: center;">Description</th>
         <th style="text-align: center;">Details</th>
      </tr>
   </thead>
   <tbody>
      <tr>
         <td><code>np.sort</code></td>
         <td>Return a sorted copy of an array</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.sort.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.lexsort</code></td>
         <td>Perform an indirect stable sort using a sequence of keys</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.lexsort.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.argsort</code></td>
         <td>Returns the indices that would sort an array</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.argsort.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.ndarray.sort</code></td>
         <td>Sort an array in-place</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.ndarray.sort.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.partition</code></td>
         <td>Return a partitioned copy of an array</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.partition.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.argpartition</code></td>
         <td>Perform an indirect partition along the given axis using the algorithm specified by the <em>kind</em> keyword</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.argpartition.html">link</a></td>
      </tr>
   </tbody>
</table>

📝 Sort Details:
   - quick sort: [javatpoint.com/quick-sort](https://www.javatpoint.com/quick-sort)
   - merge sort: [javatpoint.com/merge-sort](https://www.javatpoint.com/merge-sort)
   - heap sort : [javatpoint.com/heap-sort](https://www.javatpoint.com/heap-sort)

In [42]:
arr_1d_1 = rng.integers(low=1, high=99, size=(10))
arr_2d_1 = rng.integers(low=1, high=99, size=(3, 4))

# sort
sort_1 = np.sort(arr_1d_1)
sort_2 = np.sort(arr_1d_1, kind='mergesort')
sort_3 = np.sort(arr_1d_1, kind='heapsort')
sort_4 = np.sort(arr_2d_1, axis=None)
sort_5 = np.sort(arr_2d_1, axis=0)
sort_6 = np.sort(arr_2d_1, axis=1)

# log
print(f"arr_1d_1: {arr_1d_1}", end=f"\n{'-' * 50}\n")
print(f"arr_2d_1:\n{arr_2d_1}", end=f"\n{'-' * 50}\n")
print(f"sort_1:\n{sort_1}", end=f"\n{'-' * 50}\n")
print(f"sort_2:\n{sort_2}", end=f"\n{'-' * 50}\n")
print(f"sort_3:\n{sort_3}", end=f"\n{'-' * 50}\n")
print(f"sort_4:\n{sort_4}", end=f"\n{'-' * 50}\n")
print(f"sort_5:\n{sort_5}", end=f"\n{'-' * 50}\n")
print(f"sort_6:\n{sort_6}")

arr_1d_1: [ 9 76 65 44 43 85  9 69 20 10]
--------------------------------------------------
arr_2d_1:
[[52 96 73 75]
 [71 78 51 13]
 [83 45 50 37]]
--------------------------------------------------
sort_1:
[ 9  9 10 20 43 44 65 69 76 85]
--------------------------------------------------
sort_2:
[ 9  9 10 20 43 44 65 69 76 85]
--------------------------------------------------
sort_3:
[ 9  9 10 20 43 44 65 69 76 85]
--------------------------------------------------
sort_4:
[13 37 45 50 51 52 71 73 75 78 83 96]
--------------------------------------------------
sort_5:
[[52 45 50 13]
 [71 78 51 37]
 [83 96 73 75]]
--------------------------------------------------
sort_6:
[[52 73 75 96]
 [13 51 71 78]
 [37 45 50 83]]


In [43]:
arr_1d_2 = rng.integers(low=1, high=99, size=(10))
arr_1d_3 = np.arange(stop=10)
arr_2d_2 = rng.integers(low=1, high=99, size=(3, 4))

# argsort
argsort_1 = np.argsort(arr_1d_2)
argsort_2 = np.argsort(arr_2d_2, axis=None)
argsort_3 = np.argsort(arr_2d_2, axis=0)
argsort_4 = np.argsort(arr_2d_2, axis=1)

# sort by index
sort_1 = arr_1d_2[argsort_1]
sort_2 = arr_1d_3[argsort_1]
sort_3 = arr_2d_2.flatten()[argsort_2]
sort_4 = np.take_along_axis(arr=arr_2d_2, indices=argsort_3, axis=0)
sort_5 = np.take_along_axis(arr=arr_2d_2, indices=argsort_4, axis=1)

# log
print(f"arr_1d_2:\n{arr_1d_2}", end=f"\n{'-' * 50}\n")
print(f"arr_1d_3:\n{arr_1d_3}", end=f"\n{'-' * 50}\n")
print(f"arr_2d_2:\n{arr_2d_2}", end=f"\n{'-' * 50}\n")
print(f"argsort_1:\n{argsort_1}", end=f"\n{'-' * 50}\n")
print(f"argsort_2:\n{argsort_2}", end=f"\n{'-' * 50}\n")
print(f"argsort_3:\n{argsort_3}", end=f"\n{'-' * 50}\n")
print(f"argsort_4:\n{argsort_4}", end=f"\n{'-' * 50}\n")
print(f"sort_1:\n{sort_1}", end=f"\n{'-' * 50}\n")
print(f"sort_2:\n{sort_2}", end=f"\n{'-' * 50}\n")
print(f"sort_3:\n{sort_3}", end=f"\n{'-' * 50}\n")
print(f"sort_4:\n{sort_4}", end=f"\n{'-' * 50}\n")
print(f"sort_5:\n{sort_5}")

arr_1d_2:
[18 91 77 64 40 81 54 44 45 23]
--------------------------------------------------
arr_1d_3:
[0 1 2 3 4 5 6 7 8 9]
--------------------------------------------------
arr_2d_2:
[[10 55 88  7]
 [85 82 28 62]
 [17 75 69 35]]
--------------------------------------------------
argsort_1:
[0 9 4 7 8 6 3 2 5 1]
--------------------------------------------------
argsort_2:
[ 3  0  8  6 11  1  7 10  9  5  4  2]
--------------------------------------------------
argsort_3:
[[0 0 1 0]
 [2 2 2 2]
 [1 1 0 1]]
--------------------------------------------------
argsort_4:
[[3 0 1 2]
 [2 3 1 0]
 [0 3 2 1]]
--------------------------------------------------
sort_1:
[18 23 40 44 45 54 64 77 81 91]
--------------------------------------------------
sort_2:
[0 9 4 7 8 6 3 2 5 1]
--------------------------------------------------
sort_3:
[ 7 10 17 28 35 55 62 69 75 82 85 88]
--------------------------------------------------
sort_4:
[[10 55 28  7]
 [17 75 69 35]
 [85 82 88 62]]
------------------

In [44]:
names = np.array(['Alice', 'Bob', 'Charlie', 'David'])
grades = np.array([90, 85, 90, 85])
ages = np.array([20, 21, 19, 20])

# lexsort
indices_1 = np.lexsort((ages, grades))
sort_names_1 = names[indices_1]
sort_grades_1 = grades[indices_1]
sort_ages_1 = ages[indices_1]

indices_2 = np.lexsort((grades, ages))
sort_names_2 = names[indices_2]
sort_grades_2 = grades[indices_2]
sort_ages_2 = ages[indices_2]

# log
print(f"indices_1     : {indices_1}")
print(f"sort_names_1  : {sort_names_1}")
print(f"sort_grades_1 : {sort_grades_1}")
print(f"sort_ages_1   : {sort_ages_1}", end=f"\n{'-' * 50}\n")
print(f"indices_2     : {indices_2}")
print(f"sort_names_2  : {sort_names_2}")
print(f"sort_grades_2 : {sort_grades_2}")
print(f"sort_ages_2   : {sort_ages_2}")

indices_1     : [3 1 2 0]
sort_names_1  : ['David' 'Bob' 'Charlie' 'Alice']
sort_grades_1 : [85 85 90 90]
sort_ages_1   : [20 21 19 20]
--------------------------------------------------
indices_2     : [2 3 0 1]
sort_names_2  : ['Charlie' 'David' 'Alice' 'Bob']
sort_grades_2 : [90 85 90 85]
sort_ages_2   : [19 20 20 21]


In [45]:
data = np.array(
    [
        ('Alice', 90, 20),
        ('Bob', 85, 21),
        ('Charlie', 90, 19),
        ('David', 85, 20)
    ],
    dtype=[('name', 'U10'), ('grade', 'i4'), ('age', 'i4')]
)

# lexsort
indices_1 = np.lexsort((data['age'], data['grade']))
sort_data_1 = names[indices_1]

indices_2 = np.lexsort((data['grade'], data['age']))
sort_data_2 = names[indices_2]

# log
print(f"indices_1   : {indices_1}")
print(f"sort_data_1 : {sort_data_1}", end=f"\n{'-' * 50}\n")
print(f"indices_2   : {indices_2}")
print(f"sort_data_2 : {sort_data_2}")

indices_1   : [3 1 2 0]
sort_data_1 : ['David' 'Bob' 'Charlie' 'Alice']
--------------------------------------------------
indices_2   : [2 3 0 1]
sort_data_2 : ['Charlie' 'David' 'Alice' 'Bob']


In [46]:
arr_1d_4 = np.array([1, 5, 7, 7, 3, 5, 6, 2, 1, 9, 6, 4])

# partition
partition_1 = np.partition(arr_1d_4, kth=-1)

# argpartition
argpartition_1 = np.argpartition(arr_1d_4, kth=-1)
partition_2 = arr_1d_4[argpartition_1]

# log
print(f"partition_1   : {partition_1}")
print(f"argpartition_1: {argpartition_1}")
print(f"partition_2   : {partition_2}")

partition_1   : [1 1 2 3 4 5 5 6 6 7 7 9]
argpartition_1: [ 0  8  7  4 11  1  5  6 10  3  2  9]
partition_2   : [1 1 2 3 4 5 5 6 6 7 7 9]


## Searching

<table style="margin: 0 auto;">
   <thead>
      <tr>
         <th style="text-align: center;">Function</th>
         <th style="text-align: center;">Description</th>
         <th style="text-align: center;">Details</th>
      </tr>
   </thead>
   <tbody>
      <tr>
         <td><code>np.argmax</code></td>
         <td>Returns the indices of the maximum values along an axis</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.argmax.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.argmin</code></td>
         <td>Returns the indices of the minimum values along an axis</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.argmin.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.argwhere</code></td>
         <td>Find the indices of array elements that are non-zero, grouped by element</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.argwhere.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.nonzero</code></td>
         <td>Return the indices of the elements that are non-zero</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.nonzero.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.where</code></td>
         <td>Return elements chosen from x or y depending on condition</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.where.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.searchsorted</code></td>
         <td>Find indices where elements should be inserted to maintain order</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.searchsorted.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.extract</code></td>
         <td>Return the elements of an array that satisfy some condition</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.extract.html">link</a></td>
      </tr>
   </tbody>
</table>

In [47]:
arr_1d_5 = rng.integers(low=0, high=99, size=(10))
arr_2d_4 = rng.integers(low=0, high=99, size=(3, 4))

# argmax
argmax_1 = np.argmax(arr_1d_5)
argmax_2 = np.argmax(arr_1d_5)
argmax_3 = np.argmax(arr_2d_4, axis=0)
argmax_4 = np.argmax(arr_2d_4, axis=1)

# argmin
argmin_1 = np.argmin(arr_1d_5)
argmin_2 = np.argmin(arr_1d_5)
argmin_3 = np.argmin(arr_2d_4, axis=0)
argmin_4 = np.argmin(arr_2d_4, axis=1)

# log
print(f"arr_1d_5:\n{arr_1d_5}", end=f"\n{'-' * 50}\n")
print(f"arr_2d_4:\n{arr_2d_4}")
print(f"argmax_1: {argmax_1}")
print(f"argmax_2: {argmax_2}")
print(f"argmax_3: {argmax_3}")
print(f"argmax_4: {argmax_4}")
print(f"argmin_1: {argmin_1}")
print(f"argmin_2: {argmin_2}")
print(f"argmin_3: {argmin_3}")
print(f"argmin_4: {argmin_4}")

arr_1d_5:
[ 6 96 44 88 67 77 75 19 36 46]
--------------------------------------------------
arr_2d_4:
[[49  4 54 15]
 [73 67 91 73]
 [36 95 40 32]]
argmax_1: 1
argmax_2: 1
argmax_3: [1 2 1 1]
argmax_4: [2 2 1]
argmin_1: 0
argmin_2: 0
argmin_3: [2 0 2 0]
argmin_4: [1 1 3]


In [48]:
arr_1d_6 = rng.integers(low=0, high=99, size=(10))
arr_2d_5 = rng.integers(low=0, high=99, size=(3, 4))

# where
where_1 = np.where(arr_1d_6 > 50)
where_2 = np.where(arr_1d_6 > 50, 1, 0)
where_3 = np.where(arr_1d_6 > 50, -1, arr_1d_6)
where_4 = np.where(arr_2d_5 < 50)
where_5 = np.where(arr_2d_5 < 50, 1, 0)
where_6 = np.where(arr_2d_5 < 50, -1, arr_2d_5)

# argwhere
argwhere_1 = np.argwhere(arr_1d_6 > 50)
argwhere_2 = np.argwhere(arr_2d_5 > 50)

# log
print(f"arr_1d_6:\n{arr_1d_6}", end=f"\n{'-' * 50}\n")
print(f"arr_2d_5:\n{arr_2d_5}")
print(f"where_1:\n{where_1}", end=f"\n{'-' * 50}\n")
print(f"where_2:\n{where_2}", end=f"\n{'-' * 50}\n")
print(f"where_3:\n{where_3}", end=f"\n{'-' * 50}\n")
print(f"where_4:\n{where_4}", end=f"\n{'-' * 50}\n")
print(f"where_5:\n{where_5}", end=f"\n{'-' * 50}\n")
print(f"where_6:\n{where_6}", end=f"\n{'-' * 50}\n")
print(f"argwhere_1:\n{argwhere_1}", end=f"\n{'-' * 50}\n")
print(f"argwhere_2:\n{argwhere_2}")

arr_1d_6:
[89 36  7 46 78 18 45 12 67 47]
--------------------------------------------------
arr_2d_5:
[[32 22 55 66]
 [93 43 15 82]
 [62 69  9 30]]
where_1:
(array([0, 4, 8]),)
--------------------------------------------------
where_2:
[1 0 0 0 1 0 0 0 1 0]
--------------------------------------------------
where_3:
[-1 36  7 46 -1 18 45 12 -1 47]
--------------------------------------------------
where_4:
(array([0, 0, 1, 1, 2, 2]), array([0, 1, 1, 2, 2, 3]))
--------------------------------------------------
where_5:
[[1 1 0 0]
 [0 1 1 0]
 [0 0 1 1]]
--------------------------------------------------
where_6:
[[-1 -1 55 66]
 [93 -1 -1 82]
 [62 69 -1 -1]]
--------------------------------------------------
argwhere_1:
[[0]
 [4]
 [8]]
--------------------------------------------------
argwhere_2:
[[0 2]
 [0 3]
 [1 0]
 [1 3]
 [2 0]
 [2 1]]


In [49]:
arr_1d_7 = np.array([5, 3, 6, 8, 2, 4, 0])
arr_2d_6 = np.array([[5, 3, 1], [6, 4, 2]])

# nonzero
nonzero_1 = np.nonzero(arr_1d_7)
nonzero_2 = np.nonzero(arr_1d_7 < 4)
nonzero_3 = np.nonzero(arr_2d_6)
nonzero_4 = np.nonzero(arr_2d_6 < 4)

# log
print(f"nonzero_1: {nonzero_1}")
print(f"nonzero_2: {nonzero_2}")
print(f"nonzero_3: {nonzero_3}")
print(f"nonzero_4: {nonzero_4}")

nonzero_1: (array([0, 1, 2, 3, 4, 5]),)
nonzero_2: (array([1, 4, 6]),)
nonzero_3: (array([0, 0, 0, 1, 1, 1]), array([0, 1, 2, 0, 1, 2]))
nonzero_4: (array([0, 0, 1]), array([1, 2, 2]))


In [50]:
arr_1d_8 = np.array([1, 2, 5, 6])

# searchsorted
searchsorted_1 = np.searchsorted(arr_1d_8, v=3)
searchsorted_2 = np.searchsorted(arr_1d_8, v=4)
searchsorted_3 = np.searchsorted(arr_1d_8, v=7)

# log
print(f"searchsorted_1: {searchsorted_1}")
print(f"searchsorted_2: {searchsorted_2}")
print(f"searchsorted_3: {searchsorted_3}")

searchsorted_1: 2
searchsorted_2: 2
searchsorted_3: 4


In [51]:
arr_1d_9 = np.array([6, 3, 4, 7, 1, 2, 7, 9, 0, 3, 4])
arr_2d_7 = np.array([[5, 3, 1], [2, 4, 5]])

# extract
extract_1 = np.extract(arr_1d_9 < 4, arr_1d_9)
extract_2 = np.extract(arr_2d_7 % 2, arr_2d_7)

# log
print(f"extract_1: {extract_1}")
print(f"extract_2: {extract_2}")

extract_1: [3 1 2 0 3]
extract_2: [5 3 1 5]


## Counting

<table style="margin: 0 auto;">
   <thead>
      <tr>
         <th style="text-align: center;">Function</th>
         <th style="text-align: center;">Description</th>
         <th style="text-align: center;">Details</th>
      </tr>
   </thead>
   <tbody>
      <tr>
         <td><code>np.count_nonzero</code></td>
         <td>Counts the number of non-zero values in the array <code>a</code></td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.count_nonzero.html">link</a></td>
      </tr>
   </tbody>
</table>

In [52]:
arr_1d_10 = np.array([6, 3, 4, 0, 1, 2, 7, 9, 0, 3, 4])

# count_nonzero
count_nonzero_1 = np.count_nonzero(arr_1d_10)
count_nonzero_2 = np.count_nonzero(arr_1d_10 % 2)

# log
print(f"count_nonzero_1: {count_nonzero_1}")
print(f"count_nonzero_2: {count_nonzero_2}")

count_nonzero_1: 9
count_nonzero_2: 5
