📝 **Author:** Amirhossein Heydari - 📧 **Email:** <amirhosseinheydari78@gmail.com> - 📍 **Origin:** [mr-pylin/numpy-workshop](https://github.com/mr-pylin/numpy-workshop)

---


# Dependencies


In [1]:
import numpy as np

# NumPy - Linear Algebra

📝 Doc:

- Linear algebra (`numpy.linalg`): [numpy.org/doc/stable/reference/routines.linalg.html](https://numpy.org/doc/stable/reference/routines.linalg.html)


## Matrix and vector products

<table style="margin: 0 auto;">
  <thead>
    <tr>
      <th style="text-align: center;">Function</th>
      <th style="text-align: center;">Operator</th>
      <th style="text-align: center;">Description</th>
      <th style="text-align: center;">Details</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><code>np.dot</code></td>
      <td style="text-align: center;">-</td>
      <td>Dot product of two arrays</td>
      <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.dot.html">link</a></td>
    </tr>
    <tr>
      <td><code>np.vdot</code></td>
      <td style="text-align: center;">-</td>
      <td>Return the dot product of two vectors</td>
      <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.vdot.html">link</a></td>
    </tr>
    <tr>
      <td><code>np.vecdot</code></td>
      <td style="text-align: center;">-</td>
      <td>Vector dot product of two arrays</td>
      <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.vecdot.html">link</a></td>
    </tr>
    <tr>
      <td><code>np.inner</code></td>
      <td style="text-align: center;">-</td>
      <td>Inner product of two arrays</td>
      <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.inner.html">link</a></td>
    </tr>
    <tr>
      <td><code>np.outer</code></td>
      <td style="text-align: center;">-</td>
      <td>Compute the outer product of two vectors</td>
      <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.outer.html">link</a></td>
    </tr>
    <tr>
      <td><code>np.matmul</code></td>
      <td style="text-align: center;"><code>@</code></td>
      <td>Matrix product of two arrays</td>
      <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.matmul.html">link</a></td>
    </tr>
    <tr>
      <td><code>np.tensordot</code></td>
      <td style="text-align: center;">-</td>
      <td>Compute tensor dot product along specified axes</td>
      <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.tensordot.html">link</a></td>
    </tr>
    <tr>
      <td><code>np.einsum</code></td>
      <td style="text-align: center;">-</td>
      <td>Evaluates the Einstein summation convention on the operands</td>
      <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.einsum.html">link</a></td>
    </tr>
    <tr>
      <td><code>np.kron</code></td>
      <td style="text-align: center;">-</td>
      <td>Kronecker product of two arrays</td>
      <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.kron.html">link</a></td>
    </tr>
  </tbody>
</table>


### Dot/Scalar Product

Let $\mathbf{u}$ and $\mathbf{v}$ be two vectors:
$$\mathbf{u} = \begin{bmatrix} u_1 \\ u_2 \\ \vdots \\ u_n \end{bmatrix}, \quad \mathbf{v} = \begin{bmatrix} v_1 \\ v_2 \\ \vdots \\ v_n \end{bmatrix}$$

The dot product of $\mathbf{u}$ and $\mathbf{v}$ is:
$$\mathbf{u} \cdot \mathbf{v} = u_1 v_1 + u_2 v_2 + \cdots + u_n v_n$$

This can be written as $\mathbf{u}^T \mathbf{v}$ (the multiplication of two matrices):
$$\mathbf{u}^T \mathbf{v} = \begin{bmatrix} u_1 & u_2 & \cdots & u_n \end{bmatrix} \begin{bmatrix} v_1 \\ v_2 \\ \vdots \\ v_n \end{bmatrix}$$


In [2]:
arr_1d_1 = np.array([1, 2, 3])
arr_1d_2 = np.array([4, 5, 6])

# np.dot on 1D arrays performs the dot product
dot_1 = np.dot(arr_1d_1, arr_1d_2)
dot_2 = np.dot(arr_1d_2, arr_1d_1)

# log
print(f"dot_1: {dot_1}")
print(f"dot_2: {dot_2}")

dot_1: 32
dot_2: 32


### Dot Product for 2D Arrays

For matrices, the dot product is usually referred to as matrix multiplication.


In [3]:
arr_2d_1 = np.array([[1, 2], [3, 4]])
arr_2d_2 = np.array([[3, 1], [2, 4]])

# np.dot on 2D arrays performs the matrix multiplication [using <np.matmul(a, b)> or <a @ b> is preferred]
dot_3 = np.dot(arr_2d_1, arr_2d_2)
dot_4 = np.dot(arr_2d_2, arr_2d_1)

# log
print(f"dot_3:\n{dot_3}", end=f"\n{'-' * 50}\n")
print(f"dot_4:\n{dot_4}")

dot_3:
[[ 7  9]
 [17 19]]
--------------------------------------------------
dot_4:
[[ 6 10]
 [14 20]]


### np.vdot vs np.dot

- `np.vdot` conjugates the first argument if it is complex. Unlike `np.dot`, it always returns a scalar.


In [4]:
arr_0d_1 = np.array(2)
arr_1d_3 = np.array([1, 2, 3])

# np.vdot on arrays which one of them is scalar, performs the multiply [using <np.multiply(a, b)> or <a * b> is preferred]
dot_5 = np.dot(arr_0d_1, arr_1d_3)
dot_6 = np.dot(arr_1d_3, arr_0d_1)

# log
print(f"dot_5: {dot_5}")
print(f"dot_6: {dot_6}")

dot_5: [2 4 6]
dot_6: [2 4 6]


In [5]:
arr_1d_4 = np.array([1, 2 - 1j, 3])
arr_1d_5 = np.array([3, 2 + 1j, 1])
arr_2d_3 = np.array([[1, 2], [3, 4]])
arr_2d_4 = np.array([[3, 1], [2, 4]])

# np.vdot vs np.dot
vdot_1 = np.vdot(arr_1d_4, arr_1d_5)  # complex conjugate of the first argument is used
dot_7 = np.dot(arr_1d_4, arr_1d_5)

vdot_2 = np.vdot(arr_2d_3, arr_2d_4)
dot_8 = np.dot(arr_2d_3, arr_2d_4)

# log
print(f"vdot_1: {vdot_1}")
print(f"dot_7 : {dot_7}")
print("-" * 50)
print(f"vdot_2: {vdot_2}", end=f"\n{'-' * 50}\n")
print(f"dot_8 :\n{dot_8}")

vdot_1: (9+4j)
dot_7 : (11+0j)
--------------------------------------------------
vdot_2: 27
--------------------------------------------------
dot_8 :
[[ 7  9]
 [17 19]]


### Inner Product

Inner Product of 1D arrays is the same concept as dot/scalar product.


In [6]:
arr_1d_6 = np.array([1, 2, 3])
arr_1d_7 = np.array([4, 5, 6])

# np.inner on 1D arrays does the same calculation as np.dot
inner_1 = np.inner(arr_1d_6, arr_1d_7)
dot_9 = np.dot(arr_1d_6, arr_1d_7)

# log
print(f"inner_1: {inner_1}")
print(f"dot_9  : {dot_9}")

inner_1: 32
dot_9  : 32


### Inner Product for 2d Arrays

Computes the inner product of each pair of rows from the first matrix with each row from the second matrix.


In [7]:
arr_2d_5 = np.array([[1, 2], [3, 4]])
arr_2d_6 = np.array([[3, 1], [2, 4]])

# np.inner performs different operations on 2D arrays than np.dot
inner_2 = np.inner(arr_2d_5, arr_2d_6)
dot_10 = np.dot(arr_2d_5, arr_2d_6)

# log
print(f"inner_2:\n{inner_2}", end=f"\n{'-' * 50}\n")
print(f"dot_10 :\n{dot_10}")

inner_2:
[[ 5 10]
 [13 22]]
--------------------------------------------------
dot_10 :
[[ 7  9]
 [17 19]]


### Outer Product

Let $\mathbf{u}$ and $\mathbf{v}$ be two vectors:
$$\mathbf{u} = \begin{bmatrix} u_1 \\ u_2 \\ \vdots \\ u_n \end{bmatrix}, \quad \mathbf{v} = \begin{bmatrix} v_1 \\ v_2 \\ \vdots \\ v_n \end{bmatrix}$$

The outer product of $\mathbf{u}$ and $\mathbf{v}$ is:
$$\mathbf{u} \otimes \mathbf{v} = \begin{bmatrix} u_1 v_1 & u_1 v_2 & \cdots & u_1 v_n \\ u_2 v_1 & u_2 v_2 & \cdots & u_2 v_n \\ \vdots & \vdots & \ddots & \vdots \\ u_n v_1 & u_n v_2 & \cdots & u_n v_n \end{bmatrix}$$

This can be written as $\mathbf{u} \mathbf{v}^T$ (the multiplication of two matrices):
$$\mathbf{u} \mathbf{v}^T = \begin{bmatrix} u_1 \\ u_2 \\ \vdots \\ u_n \end{bmatrix} \begin{bmatrix} v_1 & v_2 & \cdots & v_n \end{bmatrix}$$


In [8]:
arr_1d_8 = np.array([1, 2, 3])
arr_1d_9 = np.array([4, 5, 6])

# outer
outer_1 = np.outer(arr_1d_8, arr_1d_9)

# log
print(f"outer_1:\n{outer_1}")

outer_1:
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


### Outer Product for 2D Arrays

Flattens the matrices into 1D arrays and then computes the outer product of these flattened arrays


In [9]:
arr_2d_7 = np.array([[1, 2], [3, 4]])
arr_2d_8 = np.array([[3, 1], [2, 4]])

# outer
outer_2 = np.outer(arr_2d_7, arr_2d_8)

# log
print(f"outer_2:\n{outer_2}")

outer_2:
[[ 3  1  2  4]
 [ 6  2  4  8]
 [ 9  3  6 12]
 [12  4  8 16]]


### Matrix Multiplication

Let $\mathbf{A}$ and $\mathbf{B}$ be two matrices:
$$\mathbf{A} = \begin{bmatrix} a_{11} & a_{12} & \cdots & a_{1n} \\ a_{21} & a_{22} & \cdots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{m1} & a_{m2} & \cdots & a_{mn} \end{bmatrix}, \quad \mathbf{B} = \begin{bmatrix} b_{11} & b_{12} & \cdots & b_{1p} \\ b_{21} & b_{22} & \cdots & b_{2p} \\ \vdots & \vdots & \ddots & \vdots \\ b_{n1} & b_{n2} & \cdots & b_{np} \end{bmatrix}$$

The matrix multiplication of $\mathbf{A}$ and $\mathbf{B}$ is:
$$\mathbf{C} = \mathbf{A} \cdot \mathbf{B} = \begin{bmatrix} c_{11} & c_{12} & \cdots & c_{1p} \\ c_{21} & c_{22} & \cdots & c_{2p} \\ \vdots & \vdots & \ddots & \vdots \\ c_{m1} & c_{m2} & \cdots & c_{mp} \end{bmatrix}$$

where each element $c_{ij}$ of the resulting matrix $\mathbf{C}$ is computed as:
$$c_{ij} = \sum_{k=1}^{n} a_{ik} b_{kj}$$


In [10]:
arr_2d_9 = np.array([[1, 2], [3, 4]])
arr_2d_10 = np.array([[5, 6], [7, 8]])

# matmul
matmul_1 = np.matmul(arr_2d_9, arr_2d_10)
matmul_2 = arr_2d_9 @ arr_2d_10

matmul_3 = np.matmul(arr_2d_10, arr_2d_9)
matmul_4 = arr_2d_10 @ arr_2d_9

# log
print(f"matmul_1:\n{matmul_1}", end=f"\n{'-' * 50}\n")
print(f"matmul_2:\n{matmul_2}", end=f"\n{'-' * 50}\n")
print(f"matmul_3:\n{matmul_3}", end=f"\n{'-' * 50}\n")
print(f"matmul_4:\n{matmul_4}")

matmul_1:
[[19 22]
 [43 50]]
--------------------------------------------------
matmul_2:
[[19 22]
 [43 50]]
--------------------------------------------------
matmul_3:
[[23 34]
 [31 46]]
--------------------------------------------------
matmul_4:
[[23 34]
 [31 46]]


In [11]:
image_1 = np.array([[1, 2], [3, 4]])
fourier_2x2_forward_basis_images_1 = np.array([[[[1, 1], [1, 1]], [[1, -1], [1, -1]]], [[[1, 1], [-1, -1]], [[1, -1], [-1, 1]]]])
fourier_2x2_inverse_basis_images_1 = np.conj(fourier_2x2_forward_basis_images_1).transpose(0, 1, 3, 2)

# tensordot
fourier_coefficients_1 = np.tensordot(fourier_2x2_forward_basis_images_1, image_1, axes=([2, 3], [0, 1]))
reconstructed_image_1 = np.tensordot(fourier_2x2_forward_basis_images_1, fourier_coefficients_1, axes=([2, 3], [0, 1])) / np.prod(image_1.shape)

fourier_coefficients_2 = np.fft.fft2(image_1)
reconstructed_image_2 = np.fft.ifft2(fourier_coefficients_2).real.clip(0, 4)

# log
print(f"fourier_coefficients_1:\n{fourier_coefficients_1}", end=f"\n{'-' * 50}\n")
print(f"fourier_coefficients_2:\n{fourier_coefficients_2}", end=f"\n{'-' * 50}\n")
print(f"reconstructed_image_1:\n{reconstructed_image_1}", end=f"\n{'-' * 50}\n")
print(f"reconstructed_image_2:\n{reconstructed_image_2}")

fourier_coefficients_1:
[[10 -2]
 [-4  0]]
--------------------------------------------------
fourier_coefficients_2:
[[10.+0.j -2.+0.j]
 [-4.+0.j  0.+0.j]]
--------------------------------------------------
reconstructed_image_1:
[[1. 2.]
 [3. 4.]]
--------------------------------------------------
reconstructed_image_2:
[[1. 2.]
 [3. 4.]]


### Einstein Summation

Provides a way to perform tensor operations efficiently using Einstein summation notation


In [12]:
arr_2d_11 = np.array([[1, 2], [3, 4]])
arr_2d_12 = np.array([[5, 6], [7, 8]])

# einsum
einsum_1 = np.einsum("ij,jk->ik", arr_2d_11, arr_2d_12)

# log
print(f"einsum_1:\n{einsum_1}")

einsum_1:
[[19 22]
 [43 50]]


### Kronecker Product

the Kronecker product, sometimes denoted by ⊗, is an operation on two matrices that produces a block matrix.

Let $\mathbf{A}$ and $\mathbf{B}$ be two matrices:
$$\mathbf{A} = \begin{bmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{bmatrix}, \quad \mathbf{B} = \begin{bmatrix} b_{11} & b_{12} \\ b_{21} & b_{22} \end{bmatrix}$$

The Kronecker product of $\mathbf{A}$ and $\mathbf{B}$ is:
$$\mathbf{A} \otimes \mathbf{B} = \begin{bmatrix}
a_{11} \mathbf{B} & a_{12} \mathbf{B} \\
a_{21} \mathbf{B} & a_{22} \mathbf{B}
\end{bmatrix}$$

Expanding this, we get:
$$\mathbf{A} \otimes \mathbf{B} = \begin{bmatrix}
a_{11} \begin{bmatrix} b_{11} & b_{12} \\ b_{21} & b_{22} \end{bmatrix} &
a_{12} \begin{bmatrix} b_{11} & b_{12} \\ b_{21} & b_{22} \end{bmatrix} \\
a_{21} \begin{bmatrix} b_{11} & b_{12} \\ b_{21} & b_{22} \end{bmatrix} &
a_{22} \begin{bmatrix} b_{11} & b_{12} \\ b_{21} & b_{22} \end{bmatrix}
\end{bmatrix} = \begin{bmatrix}
a_{11} b_{11} & a_{11} b_{12} & a_{12} b_{11} & a_{12} b_{12} \\
a_{11} b_{21} & a_{11} b_{22} & a_{12} b_{21} & a_{12} b_{22} \\
a_{21} b_{11} & a_{21} b_{12} & a_{22} b_{11} & a_{22} b_{12} \\
a_{21} b_{21} & a_{21} b_{22} & a_{22} b_{21} & a_{22} b_{22}
\end{bmatrix}$$


In [13]:
arr_1d_10 = np.array([1, 2])
arr_1d_11 = np.array([1, 2])

# kron
kron_1 = np.kron(arr_1d_10, arr_1d_11)

# log
print(f"kron_1: {kron_1}")

kron_1: [1 2 2 4]


In [14]:
arr_2d_13 = np.array([[1, 2], [3, 4]])
arr_2d_14 = np.array([[1, 1], [1, 1]])

# kron
kron_2 = np.kron(arr_2d_13, arr_2d_14)

# log
print(f"kron_2:\n{kron_2}")

kron_2:
[[1 1 2 2]
 [1 1 2 2]
 [3 3 4 4]
 [3 3 4 4]]


## Decompositions

<table style="margin: 0 auto;">
  <thead>
    <tr>
      <th style="text-align: center;">Function</th>
      <th style="text-align: center;">Description</th>
      <th style="text-align: center;">Details</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><code>np.linalg.cholesky</code></td>
      <td>Cholesky decomposition</td>
      <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.linalg.cholesky.html">link</a></td>
    </tr>
    <tr>
      <td><code>np.linalg.qr</code></td>
      <td>Compute the qr factorization of a matrix</td>
      <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.linalg.qr.html">link</a></td>
    </tr>
    <tr>
      <td><code>np.linalg.svd</code></td>
      <td>Returns the singular values of a matrix (or a stack of matrices) <code>x</code></td>
      <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.linalg.svd.html">link</a></td>
    </tr>
  </tbody>
</table>


In [15]:
arr_2d_15 = np.array([[4, 2], [2, 3]])

# Compute Cholesky decomposition of a positive-definite matrix
cholesky_1 = np.linalg.cholesky(arr_2d_15)

# log
print(f"cholesky_1:\n{cholesky_1}")

cholesky_1:
[[2.         0.        ]
 [1.         1.41421356]]


In [16]:
arr_2d_16 = np.array([[1, 2], [3, 4]])

# Compute QR decomposition
Q, R = np.linalg.qr(arr_2d_16)

# log
print(f"Q:\n{Q}\n")
print(f"R:\n{R}")

Q:
[[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]

R:
[[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]


In [17]:
arr_2d_17 = np.array([[1, 2], [3, 4]])

# Compute SVD
U, S, Vt = np.linalg.svd(arr_2d_17)

# Log
print(f"U:\n{U}\n")
print(f"S:\n{S}\n")
print(f"Vt:\n{Vt}")

U:
[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]

S:
[5.4649857  0.36596619]

Vt:
[[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


## Matrix eigenvalues

<table style="margin: 0 auto;">
  <thead>
    <tr>
      <th style="text-align: center;">Function</th>
      <th style="text-align: center;">Description</th>
      <th style="text-align: center;">Details</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><code>np.linalg.eig</code></td>
      <td>Compute the eigenvalues and right eigenvectors of a square array</td>
      <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html">link</a></td>
    </tr>
    <tr>
      <td><code>np.linalg.eigh</code></td>
      <td>Return the eigenvalues and eigenvectors of a complex Hermitian (conjugate symmetric) or a real symmetric matrix</td>
      <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.linalg.eigh.html">link</a></td>
    </tr>
    <tr>
      <td><code>np.linalg.eigvals</code></td>
      <td>Compute the eigenvalues of a general matrix</td>
      <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.linalg.eigvals.html">link</a></td>
    </tr>
    <tr>
      <td><code>np.linalg.eigvalsh</code></td>
      <td>Compute the eigenvalues of a complex Hermitian or real symmetric matrix</td>
      <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.linalg.eigvalsh.html">link</a></td>
    </tr>
  </tbody>
</table>


## Norms and other numbers

<table style="margin: 0 auto;">
  <thead>
    <tr>
      <th style="text-align: center;">Function</th>
      <th style="text-align: center;">Description</th>
      <th style="text-align: center;">Details</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><code>np.linalg.norm</code></td>
      <td>Matrix or vector norm</td>
      <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html">link</a></td>
    </tr>
    <tr>
      <td><code>np.linalg.det</code></td>
      <td>Compute the determinant of an array</td>
      <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html">link</a></td>
    </tr>
    <tr>
      <td><code>np.linalg.matrix_rank</code></td>
      <td>Return matrix rank of array using SVD method</td>
      <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.linalg.matrix_rank.html">link</a></td>
    </tr>
    <tr>
      <td><code>np.trace</code></td>
      <td>Return the sum along diagonals of the array</td>
      <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.trace.html">link</a></td>
    </tr>
  </tbody>
</table>


In [18]:
arr_1d_12 = np.array([3, 4])
arr_2d_18 = np.array([[1, 2], [3, 4]])

# norm
norm_1 = np.linalg.norm(arr_1d_12, ord=1)
norm_2 = np.linalg.norm(arr_1d_12, ord=2)
norm_3 = np.linalg.norm(arr_1d_12, ord=np.inf)
norm_4 = np.linalg.norm(arr_2d_18, ord="fro")

# log
print(f"norm_1 (L_1       norm): {norm_1}")
print(f"norm_2 (L_2       norm): {norm_2}")
print(f"norm_3 (L_inf     norm): {norm_3}")
print(f"norm_4 (Frobenius norm): {norm_4}")

norm_1 (L_1       norm): 7.0
norm_2 (L_2       norm): 5.0
norm_3 (L_inf     norm): 4.0
norm_4 (Frobenius norm): 5.477225575051661


In [19]:
arr_2d_19 = np.array([[1, 2], [3, 4]])

# determinants
determinant_1 = np.linalg.det(arr_2d_19)

# log
print(f"determinant_1: {determinant_1}")

determinant_1: -2.0000000000000004


In [20]:
arr_2d_20 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# trace
trace_1 = np.linalg.trace(arr_2d_20)

# log
print(f"trace_1: {trace_1}")

trace_1: 15


In [21]:
arr_2d_21 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# rank
rank_1 = np.linalg.matrix_rank(arr_2d_21)

# log
print(f"rank_1: {rank_1}")

rank_1: 2


## Solving equations and inverting matrices

<table style="margin: 0 auto;">
  <thead>
    <tr>
      <th style="text-align: center;">Function</th>
      <th style="text-align: center;">Description</th>
      <th style="text-align: center;">Details</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><code>np.linalg.solve</code></td>
      <td>Solve a linear matrix equation, or system of linear scalar equations</td>
      <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html">link</a></td>
    </tr>
    <tr>
      <td><code>np.linalg.lstsq</code></td>
      <td>Return the least-squares solution to a linear matrix equation</td>
      <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.linalg.lstsq.html">link</a></td>
    </tr>
    <tr>
      <td><code>np.linalg.inv</code></td>
      <td>Compute the inverse of a matrix</td>
      <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html">link</a></td>
    </tr>
    <tr>
      <td><code>np.linalg.pinv</code></td>
      <td>Compute the (Moore-Penrose) pseudo-inverse of a matrix</td>
      <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/generated/numpy.linalg.pinv.html">link</a></td>
    </tr>
  </tbody>
</table>


Let $\mathbf{A}$ be an $m \times n$ matrix, $\mathbf{x}$ be an $n \times 1$ column vector, and $\mathbf{b}$ be an $m \times 1$ column vector. The system of linear equations can be written in matrix form as:

$$\mathbf{A} \mathbf{x} = \mathbf{b}$$

where:

$$\mathbf{A} = \begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix}, \quad
\mathbf{x} = \begin{bmatrix}
x_1 \\
x_2 \\
\vdots \\
x_n
\end{bmatrix}, \quad
\mathbf{b} = \begin{bmatrix}
b_1 \\
b_2 \\
\vdots \\
b_m
\end{bmatrix}$$
The $i$-th equation in the system is:
$$\sum_{j=1}^{n} a_{ij} x_j = b_i$$

Let $\mathbf{A}$ be an $m \times n$ matrix, $\mathbf{x}$ be an $n \times 1$ column vector, and $\mathbf{b}$ be an $m \times 1$ column vector. The system of linear equations can be written in matrix form as:

$$\mathbf{A} \mathbf{x} = \mathbf{b}$$

### Case 1: Square Matrix and Invertibility

If $\mathbf{A}$ is a square matrix (i.e., $m = n$) and invertible, the solution to the system can be obtained by multiplying both sides of the equation by the inverse of $\mathbf{A}$:

$$\mathbf{x} = \mathbf{A}^{-1} \mathbf{b}$$

where $\mathbf{A}^{-1}$ denotes the inverse of $\mathbf{A}$. The matrix $\mathbf{A}$ is invertible if and only if its determinant is non-zero:

$$\det(\mathbf{A}) \neq 0$$

Thus, the solution vector $\mathbf{x}$ is:

$$\mathbf{x} = \mathbf{A}^{-1} \mathbf{b}$$

### Case 2: Non-Square Matrix or Singular Matrix

If $\mathbf{A}$ is not a square matrix (i.e., $m \neq n$) or is a square but singular matrix (i.e., $\det(\mathbf{A}) = 0$), the inverse does not exist. In such cases, we use the Moore-Penrose pseudo-inverse to find a least-squares solution.

The Moore-Penrose pseudo-inverse of $\mathbf{A}$, denoted $\mathbf{A}^+$, is defined as:

$$\mathbf{A}^+ = (\mathbf{A}^\top \mathbf{A})^{-1} \mathbf{A}^\top$$

when $\mathbf{A}^\top \mathbf{A}$ is invertible. The solution vector $\mathbf{x}$ can then be approximated by:

$$\mathbf{x} = \mathbf{A}^+ \mathbf{b}$$

For general cases, where $\mathbf{A}^\top \mathbf{A}$ is not invertible, the pseudo-inverse can be computed using Singular Value Decomposition (SVD):

$$\mathbf{A} = \mathbf{U} \mathbf{\Sigma} \mathbf{V}^\top$$

where $\mathbf{\Sigma}$ is a diagonal matrix with singular values. The pseudo-inverse is given by:

$$\mathbf{A}^+ = \mathbf{V} \mathbf{\Sigma}^+ \mathbf{U}^\top$$

where $\mathbf{\Sigma}^+$ is the pseudo-inverse of $\mathbf{\Sigma}$.

Thus, the least-squares solution vector $\mathbf{x}$ is:

$$\mathbf{x} = \mathbf{A}^+ \mathbf{b}$$


In [22]:
A_1 = np.array([[3, 2], [1, 2]])
b_1 = np.array([5, 4])

# solve
x = np.linalg.solve(A_1, b_1)

# log
print(f"x: {x}")

x: [0.5  1.75]


In [23]:
A_2 = np.array([[1, 1], [1, 2], [1, 3]])
b_2 = np.array([1, 2, 3])

# solve using least square error
x, residuals, rank, s = np.linalg.lstsq(A_2, b_2, rcond=None)

# log
print(f"x: {x}")

x: [1.80069003e-16 1.00000000e+00]


In [24]:
A_3 = np.array([[1, 2], [3, 4]])

# inverse
A_inv = np.linalg.inv(A_3)
eye_1 = A_3 @ A_inv

# log
print(f"A_inv:\n{A_inv}\n")
print(f"eye_1:\n{eye_1}")

A_inv:
[[-2.   1. ]
 [ 1.5 -0.5]]

eye_1:
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [25]:
A_4 = np.array([[1, 2], [3, 4], [5, 6]])

# pseudo-inverse
A_pinv = np.linalg.pinv(A_4)
eye_2 = A_pinv @ A_4

# log
print(f"A_pinv:\n{A_pinv}\n")
print(f"eye_2:\n{eye_2}")

A_pinv:
[[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]

eye_2:
[[ 1.0000000e+00  0.0000000e+00]
 [-4.4408921e-16  1.0000000e+00]]
