📝 **Author:** Amirhossein Heydari - 📧 **Email:** AmirhosseinHeydari78@gmail.com - 📍 **Linktree:** [linktr.ee/mr_pylin](https://linktr.ee/mr_pylin)

---

# Dependencies

In [16]:
import numpy as np

# NumPy - Random Generator
📝 Doc:
   - Random `Generator`: [numpy.org/doc/stable/reference/random/generator.html](https://numpy.org/doc/stable/reference/random/generator.html)
   - Legacy random generation: [numpy.org/doc/stable/reference/random/legacy.html](https://numpy.org/doc/stable/reference/random/legacy.html)

## np.random.default_rng

<table style="margin: 0 auto;">
   <thead>
      <tr>
         <th style="text-align: center;">Function</th>
         <th style="text-align: center;">Description</th>
         <th style="text-align: center;">Details</th>
      </tr>
   </thead>
   <tbody>
      <tr>
         <td><code>np.random.default_rng</code></td>
         <td>Construct a new Generator with the default BitGenerator (PCG64)</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/random/generator.html#numpy.random.default_rng">link</a></td>
      </tr>
   </tbody>
</table>

   - Definition
      - It is a function in NumPy that provides a new, more flexible random number generator (RNG) system introduced in NumPy 1.17
      - It is designed to replace the older `np.random` module functions with a more modern and user-friendly interface
   - Key Features
      1. Modern RNG Algorithms
         - It uses the PCG64 (Permuted Congruential Generator with 64-bit state) RNG, which is a high-quality, fast, and robust algorithm
      1. Separate State
         - Each instance of the RNG has its own internal state, making it easier to manage and seed different instances independently
      1. Enhanced Flexibility
         - The RNG instance (`Generator` object) provides a wide range of methods for generating random numbers, including integers, floats, and more complex distributions
      1. Better Performance
         - The new RNG is generally faster and provides better statistical properties compared to the older `np.random` methods

In [17]:
# set the seed for reproducibility
seed = 42
rng = np.random.default_rng(seed)

# bit_generator
seed_seq = rng.bit_generator.seed_seq
state = rng.bit_generator.state

# log
print(f"seed_seq : {seed_seq}")
print(f"state    : {state}")

seed_seq : SeedSequence(
    entropy=42,
)
state    : {'bit_generator': 'PCG64', 'state': {'state': 274674114334540486603088602300644985544, 'inc': 332724090758049132448979897138935081983}, 'has_uint32': 0, 'uinteger': 0}


## Simple random data

<table style="margin: 0 auto;">
   <thead>
      <tr>
         <th style="text-align: center;">Function</th>
         <th style="text-align: center;">Description</th>
         <th style="text-align: center;">Details</th>
      </tr>
   </thead>
   <tbody>
      <tr>
         <td><code>np.integers</code></td>
         <td>Return random integers from low (inclusive) to high (exclusive), or if <code>endpoint=True</code>, low (inclusive) to high (inclusive)</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.integers.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.random</code></td>
         <td>Return random floats in the half-open interval <code>[0.0, 1.0)</code></td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.random.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.choice</code></td>
         <td>Generates a random sample from a given array</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.choice.html">link</a></td>
      </tr>
   </tbody>
</table>

In [18]:
# random integers : [low, high)
random_integers_1 = rng.integers(low=0, high=10, size=5)
random_integers_2 = rng.integers(low=0, high=10, size=(2, 3))

# log
print(f"random_integers_1:\n{random_integers_1}", end=f"\n{'-' * 50}\n")
print(f"random_integers_2:\n{random_integers_2}")

random_integers_1:
[0 7 6 4 4]
--------------------------------------------------
random_integers_2:
[[8 0 6]
 [2 0 5]]


In [19]:
# random floats : [0.0, 1.0)
random_floats_1 = rng.random(size=5)
random_floats_2 = rng.random(size=(2, 3))

# log
print(f"random_floats_1:\n{random_floats_1}", end=f"\n{'-' * 50}\n")
print(f"random_floats_2:\n{random_floats_2}")

random_floats_1:
[0.7611397  0.78606431 0.12811363 0.45038594 0.37079802]
--------------------------------------------------
random_floats_2:
[[0.92676499 0.64386512 0.82276161]
 [0.4434142  0.22723872 0.55458479]]


In [20]:
arr_1d_1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# generate a random sample from a given array
choice_1 = rng.choice(arr_1d_1, size=5, replace=True)
choice_2 = rng.choice(arr_1d_1, size=5, replace=False)
choice_3 = rng.choice(arr_1d_1, size=5, replace=True, p=[0.7, 0.1, 0.2, 0, 0, 0, 0, 0, 0])
choice_4 = rng.choice(arr_1d_1, size=5, replace=False, shuffle=True)

# log
print(f"choice_1: {choice_1}")
print(f"choice_2: {choice_2}")
print(f"choice_3: {choice_3}")
print(f"choice_4: {choice_4}")

choice_1: [9 8 1 8 8]
choice_2: [9 8 7 2 4]
choice_3: [2 1 1 1 1]
choice_4: [7 5 9 8 6]


## Permutations

<table style="margin: 0 auto;">
   <thead>
      <tr>
         <th style="text-align: center;">Function</th>
         <th style="text-align: center;">Description</th>
         <th style="text-align: center;">Details</th>
      </tr>
   </thead>
   <tbody>
      <tr>
         <td><code>np.shuffle</code></td>
         <td>Modify an array or sequence in-place by shuffling its contents</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.shuffle.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.permutation</code></td>
         <td>Randomly permute a sequence, or return a permuted range</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.permutation.html">link</a></td>
      </tr>
   </tbody>
</table>

In [21]:
arr_1d_2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_2d_1 = np.array([[1, 2, 5], [4, 5, 6]])
arr_2d_2 = np.array([[1, 2, 3], [4, 5, 6]])

# shuffle
shuffle_1 = rng.shuffle(arr_1d_2)
shuffle_2 = rng.shuffle(arr_2d_1, axis=0)
shuffle_3 = rng.shuffle(arr_2d_2, axis=1)

# log
print(f"arr_1d_2:\n{arr_1d_2}", end=f"\n{'-' * 50}\n")
print(f"arr_2d_1:\n{arr_2d_1}", end=f"\n{'-' * 50}\n")
print(f"arr_2d_2:\n{arr_2d_2}")

arr_1d_2:
[4 8 7 5 9 1 6 2 3]
--------------------------------------------------
arr_2d_1:
[[4 5 6]
 [1 2 5]]
--------------------------------------------------
arr_2d_2:
[[1 3 2]
 [4 6 5]]


In [22]:
arr_1d_4 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# premutation
permutation_1 = rng.permutation(arr_1d_4)

# log
print(f"permutation_1 : {permutation_1}")

permutation_1 : [4 6 5 1 9 7 3 2 8]


### Shuffling non-NumPy sequences

In [23]:
list_1 = ["A", "B", "C", "D", "E"]

# shuffle
rng.shuffle(list_1)  # in-place operation

# log
print(f"list_1: {list_1}")

list_1: ['B', 'D', 'A', 'C', 'E']


## Distributions

<table style="margin: 0 auto;">
   <thead>
      <tr>
         <th style="text-align: center;">Function</th>
         <th style="text-align: center;">Description</th>
         <th style="text-align: center;">Details</th>
      </tr>
   </thead>
   <tbody>
      <tr>
         <td><code>np.binomial</code></td>
         <td>Draw samples from a binomial distribution</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.binomial.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.chisquare</code></td>
         <td>Draw samples from a chi-square distribution</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.chisquare.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.exponential</code></td>
         <td>Draw samples from an exponential distribution</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.exponential.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.gamma</code></td>
         <td>Draw samples from a Gamma distribution</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.gamma.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.geometric</code></td>
         <td>Draw samples from the geometric distribution</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.geometric.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.normal</code></td>
         <td>Draw random samples from a normal (Gaussian) distribution</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.normal.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.poisson</code></td>
         <td>Draw samples from a Poisson distribution</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.poisson.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.power</code></td>
         <td>Draws samples in [0, 1] from a power distribution with positive exponent a - 1</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.power.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.rayleigh</code></td>
         <td>Draw samples from a Rayleigh distribution</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.rayleigh.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.standard_normal</code></td>
         <td>Draw samples from a standard Normal distribution (mean=0, stdev=1)</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.standard_normal.html">link</a></td>
      </tr>
      <tr>
         <td><code>np.uniform</code></td>
         <td>Draw samples from a uniform distribution</td>
         <td style="text-align: center;"><a href="https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.uniform.html">link</a></td>
      </tr>
   </tbody>
</table>

In [24]:
# normal
normal_samples_1 = rng.normal(loc=0, scale=1, size=5)

# log
print(f"normal_samples_1: {normal_samples_1}")

normal_samples_1: [0.2186886  0.87142878 0.22359555 0.67891356 0.06757907]


In [25]:
# uniform
uniform_samples_1 = rng.uniform(low=0, high=10, size=5)

# log
print(f"uniform_samples_1: {uniform_samples_1}")

uniform_samples_1: [7.86924378 6.64850857 7.05165379 7.80729031 4.58915776]


In [26]:
# binomial
binomial_samples_1 = rng.binomial(n=10, p=0.5, size=5)

# log
print(f"binomial_samples_1: {binomial_samples_1}")

binomial_samples_1: [5 3 3 6 5]


In [27]:
# exponential
exponential_samples_1 = rng.exponential(scale=1.0, size=5)

# log
print(f"exponential_samples_1: {exponential_samples_1}")

exponential_samples_1: [1.50780913 5.3098828  2.10666023 1.64486584 1.04349148]


In [28]:
# geometric
geometric_samples_1 = rng.geometric(p=0.5, size=5)

# log
print(f"geometric_samples_1: {geometric_samples_1}")

geometric_samples_1: [1 1 1 1 1]


In [29]:
# poisson
poisson_samples_1 = rng.poisson(lam=3.0, size=5)

# log
print(f"poisson_samples_1: {poisson_samples_1}")

poisson_samples_1: [2 3 4 0 2]


In [30]:
# rayleigh
rayleigh_samples_1 = rng.rayleigh(scale=1.0, size=5)

# log
print(f"rayleigh_samples_1: {rayleigh_samples_1}")

rayleigh_samples_1: [0.87878469 1.3674497  0.61199257 1.95872022 1.60745516]
