📝 **Author:** Amirhossein Heydari - 📧 **Email:** AmirhosseinHeydari78@gmail.com - 📍 **Linktree:** [linktr.ee/mr_pylin](https://linktr.ee/mr_pylin)

---

# Dependencies

In [1]:
import numpy as np

# NumPy - Miscellaneous
Doc:
   - [numpy.org/doc/stable/reference/routines.fft.html](https://numpy.org/doc/stable/reference/routines.fft.html)

## Common Bugs

### NumPy needs to know how many bytes to consider for array elements

In [2]:
arr_1d_1 = np.array(['a', 'b', 'c'])  # 1 Byte per element

# log
print(f"arr_1d_1.dtype  : {arr_1d_1.dtype}")
print(f"arr_1d_1.nbytes : {arr_1d_1.nbytes}")

arr_1d_1.dtype  : <U1
arr_1d_1.nbytes : 12


In [3]:
arr_1d_1[2] = 'de'  # 2 Bytes!

# log
print(f"arr_1d_1 : {arr_1d_1}")

arr_1d_1 : ['a' 'b' 'd']


### NDArray to Python List

In [4]:
arr_1d_2 = np.array([1, 2, 3, 4, 5])

In [5]:
# wrong conversion
list_1 = list(arr_1d_2)

# log
print(f"list_1          : {list_1}")
print(f"type(list_1)    : {type(list_1)}")
print(f"type(list_1[0]) : {type(list_1[0])}")

list_1          : [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]
type(list_1)    : <class 'list'>
type(list_1[0]) : <class 'numpy.int64'>


In [6]:
# correct conversion
list_2 = arr_1d_2.tolist()

# log
print(f"list_2          : {list_2}")
print(f"type(list_2)    : {type(list_2)}")
print(f"type(list_2[0]) : {type(list_2[0])}")

list_2          : [1, 2, 3, 4, 5]
type(list_2)    : <class 'list'>
type(list_2[0]) : <class 'int'>


### Soft Copy vs Hard Copy
   - Soft/Shallow Copy
      - A new object that references the original data
   - Hard/Deep Copy
      - A completely independent copy of the original data

In [7]:
arr_2d_1 = np.array([[1, 2], [3, 4]])

# a pointer/referencce to the original array
arr_2d_2 = arr_2d_1

# assignment
arr_2d_2[0] = [5, 6]
arr_2d_2[1, 0] = 0

# log
print(f"arr_2d_1:\n{arr_2d_1}\n")
print(f"arr_2d_2:\n{arr_2d_2}")

arr_2d_1:
[[5 6]
 [0 4]]

arr_2d_2:
[[5 6]
 [0 4]]


In [8]:
arr_2d_3 = np.array([[1, 2], [3, 4]])

# soft/shallow copy
arr_2d_4 = arr_2d_3[:]  # also arr_2d_3.view()

# assignment
arr_2d_4[0] = [5, 6]
arr_2d_4[1, 0] = 0

# log
print(f"arr_2d_3:\n{arr_2d_3}\n")
print(f"arr_2d_4:\n{arr_2d_4}")

arr_2d_3:
[[5 6]
 [0 4]]

arr_2d_4:
[[5 6]
 [0 4]]


In [9]:
arr_2d_5 = np.array([[1, 2], [3, 4]])

# hard/deep copy
arr_2d_6 = arr_2d_5.copy()

# assignment
arr_2d_6[0] = [5, 6]
arr_2d_6[1, 0] = 0

# log
print(f"arr_2d_5:\n{arr_2d_5}\n")
print(f"arr_2d_6:\n{arr_2d_6}")

arr_2d_5:
[[1 2]
 [3 4]]

arr_2d_6:
[[5 6]
 [0 4]]
